### ISSUE TITLE
TestNSCDiesSingleNode test failed sometimes.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1020]
## Expected Behavior

Test should pass always.

## Current Behavior

Test is failing some times.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

## Failure Logs

[TestNSCDiesSingleNode.txt](https://github.com/networkservicemesh/networkservicemesh/files/3127982/TestNSCDiesSingleNode.txt)

**Comment by denis-tingajkin** [comment]
I can start looking at this issue if you don't mind

**Comment by edwarnicke** [comment]
Still failing: https://circleci.com/gh/networkservicemesh/networkservicemesh/45209

Any progress on this?  Did you pick it up @denis-tingajkin

**Comment by lobkovilya** [comment]
@nickolaev could you please reopen this issue, because #1078 only extend logs during fail. It doesn't fix bug
