### ISSUE TITLE
Propose common logging mechanism and make logs cleaner

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/networkservicemesh#1053]
## Overview
There is no 'standard' way for making logging in project so all logs looks a little bit different. It can be solved by adding a common file to aggregate log formatting.

## References

>Good, I think we should have some log formatting to be consumed in some logging.go to be consistent in all places.

_Originally posted by @haiodo in https://github.com/networkservicemesh/networkservicemesh/pull/979_

**Comment by haiodo** [comment]
Also it would be nice to capture all pod logs and put them into artifact resources on CI.
