### ISSUE TITLE
Reduce image count

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/networkservicemesh#1061]
## Overview

There are multiple images that can be merged in few images with configurable entry point:
* common:
    * nsc
    * nsmd
   * ...
* vppagent-common:
    * vppagent-dataplane
    * vppagent-nsc
    * ...

Making such images can reduce the count of CircleCI build jobs and reduce the CI complexity.

## References

>@Bolodya1997 Would it make sense to collapse the build of various NSE containers into a single CircleCI job?

_Originally posted by @edwarnicke in https://github.com/networkservicemesh/networkservicemesh/pull/1013#issuecomment-487921878_

**Comment by nickolaev** [comment]
I don't like this proposal and I think it is a misinterpretation of the said comment. The said containers have very little in common and should not be merged.
@edwarnicke @haiodo please weigh in here.

**Comment by haiodo** [comment]
@nickolaev This was my idea, actually, to have common CI container we will use for CI, to not have examples, etc but have only testing and test container. 
Examples should resist into examples repository and do not confuse any of users.

Thoughts?

**Comment by haiodo** [comment]
It will simplify adding of any new applications required for CI testing more easy, just add compile into common ci docker image and pass as command for pod/container at start point in CI.

**Comment by nickolaev** [comment]
Well, are we saying we are going to distribute the whole NSM in 2 images - alpine and vppagent based? I get the point about simplifying the CI, but releasing a multi-entrypoint images is a serious design change and deserves a bit more discussion.
To me, except simplifying/speeding up the CI, I can't see any other advantages of such approach. But maybe I am missing something.
