### ISSUE TITLE
Healing failing intermittently on AWS

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1086]
## Expected Behavior

Testing to pass reliably in CI

## Current Behavior

TestDataplaneHealLocal, TestDataplaneHealLocalMemif, TestDataplaneHealRemote failing in CI on master: https://circleci.com/gh/networkservicemesh/networkservicemesh/46376

**Comment by haiodo** [comment]
Based on logs, Kubernetes doesn't have required number of nudes, and shows us 0 nodes available.
