### ISSUE TITLE
Incorrect helm charts causes a retry-loop

### ISSUE THREAD

**Issue by uablrek** [networkservicemesh/networkservicemesh#1094]
## Expected Behavior

Helm install should work

## Current Behavior

Helm install does not work and causes a retry-loop consuming a fair ammount of cpu.

## Failure Information (for bugs)

Discussed in this thread https://groups.google.com/forum/#!topic/networkservicemesh/HVh7araG0B0

Since the problem is identified this issue is more of a reference for a PR.

## Steps to Reproduce

```
helm install deployments/helm/nsm
helm install deployments/helm/icmp-responder
```

## Context

K3s and others

**Comment by nickolaev** [comment]
#1094 merged. Closing.
