### ISSUE TITLE
TestNSCAndICMPWebhookLocal failing in CI

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1097]
## Expected Behavior

CI should reliably pass on master

## Current Behavior

TestNSCAndICMPWebhookLocal is failing in CI: https://circleci.com/gh/networkservicemesh/networkservicemesh/47149

**Comment by denis-tingajkin** [comment]
Reproducible https://circleci.com/gh/networkservicemesh/networkservicemesh/48789?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
