### ISSUE TITLE
TestMovingConnectionMemif failing in packet CI

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1100]
## Expected Behavior

Tests should pass reliably in CI

## Current Behavior

https://circleci.com/gh/networkservicemesh/networkservicemesh/48157

**Comment by denis-tingajkin** [comment]
I guess the link to circleci is wrong. Can you check?

**Comment by denis-tingajkin** [comment]
I've run this test locally and the issue doesn't reproducible.
It's can be related to the `packet` loading. For this case, I'll reduce max NSC count and also enhance logs

**Comment by haiodo** [comment]
Logging added, locally is not reproducible.
