### ISSUE TITLE
Fix time.Tick() and other linter shown memory leaks.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1124]
## Expected Behavior

Application should not have memory leaks.

## Current Behavior

<- time.Tick() and others used in code caused memory leaks.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by Bolodya1997** [comment]
`<-time.After()` is OK so it can be used instead of `<-time.Tick()`

**Comment by haiodo** [comment]
This seems merged, so closing.
