### ISSUE TITLE
Packet-deploy fails sometimes

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1139]
## Expected Behavior
Successful deploy of instances to packet

## Current Behavior
https://circleci.com/gh/networkservicemesh/networkservicemesh/52267

## Possible solution 
Change location if deploy has been failed

**Comment by haiodo** [comment]
It seems we need to randomly check different zone.

**Comment by lobkovilya** [comment]
After increasing log level to *DEBUG* received such output:
[build_60836_step_110_container_0.txt](https://github.com/networkservicemesh/networkservicemesh/files/3239638/build_60836_step_110_container_0.txt)

**Comment by lobkovilya** [comment]
https://github.com/terraform-providers/terraform-provider-packet/issues/153
