### ISSUE TITLE
A pure kernel based forwarding plane

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#1169]
## Overview

Implement a new forwarding plane, which can completely replace the (improperly named) `vppagent-dataplane` DaemonSet. The goal is to use Linux kernel only means to interconnect pods on the same and remote nodes.

First target:
 * veth pair for pod-pod on the same host
 * inject the decapsulated VxLAN interface in the pod that needs a remote connection

That will create a minimum valuable implementation which can be used as a reference for future, better-optimized implementations.

**Comment by rdimitrov** [comment]
For reference, the following PRs are related to the context of this issue - https://github.com/networkservicemesh/networkservicemesh/pull/1214 and https://github.com/networkservicemesh/networkservicemesh/pull/1207

**Comment by rdimitrov** [comment]
The issue can surely be closed as the implementation is already merged with #1321 👍
