### ISSUE TITLE
TestExcludePrefixesMonitorFails fails intermittently

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/networkservicemesh#1171]
## Expected Behavior

`TestExcludePrefixesMonitorFails` should always pass.

## Current Behavior

`TestExcludePrefixesMonitorFails` fails sometimes.

## Failure Information (for bugs)

https://circleci.com/gh/networkservicemesh/networkservicemesh/58559

**Comment by lobkovilya** [comment]
Working on fix
