### ISSUE TITLE
Azure leaking resources 

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1174]
## Expected Behavior
All resources correctly cleaned up

## Current Behavior
For some reason, the cluster was not cleaned 

## Failure Information (for bugs)
Workflow that led to cluster leaking:
https://circleci.com/gh/networkservicemesh/networkservicemesh/59146

**Comment by lobkovilya** [comment]
Exactly the same problem is described here: https://discuss.circleci.com/t/could-not-parse-object-git-error/21193

**Comment by edwarnicke** [comment]
@haiodo Expects one job for tests will fix this.

**Comment by haiodo** [comment]
Seems done.
