### ISSUE TITLE
CNI plugin testing

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1176]
Now we test every pull request in 3 different clouds (and bare-metal clusters on packet). But seems like the main difference that makes sense for us is CNI plugins used on a particular cloud.

- GKE uses *Calico*
- EKS uses *AWS CNI Plugin*, has support of *Calico* as well
- AKS uses *Azure VNET CNI Plugins*

All those plugins are open-source and could be easily installed on every kubernetes cluster. Moreover, there are a number of other CNI plugins that we need to test with.

So I think we need to somehow rethink our CI. Probably it's better to move from cloud testing to bare-metal testing with different CNI plugins. Or cloud testing could be done only on master branch.

**Comment by nickolaev** [comment]
I would argue here that CNI is orthogonal to NSM. On the other hand, it is true that `nsmd-k8s` leverages whatever CNI is out there to talk K8s API. Everything else should be pretty much CNI independent. Even more, if there are other CNI dependencies we should outline and remove them.

**Comment by lobkovilya** [comment]
Yep, you are right NSM is orthogonal to CNI. But this is the thing that we are guaranteeing to users. 
As developers we had some issues with configuring VPP when we were deploying NSM on GKE, AKS and EKS. Because they are using different mechanisms to setup pod networking. That's why we had to configure additional routes on vpp pod, because vxlan did not work out-of-box on GKE for us. We had to configure arp-entries on vpp pod in order to satisfy EKS networking. And if I am correct that "pod networking setup" is determined by CNI plugin.

And there are other interesting CNI that for example use IPVLANs instead of bridge to setup pod networking (https://github.com/lyft/cni-ipvlan-vpc-k8s). So I believe that testing NSM on different CNI plugins is more important than testing on different clouds.

**Comment by nickolaev** [comment]
Do you consider the problems you talk about being specific to vpp-agent or are a generic forwarding plane issues? I.e. do you consider these to be issues with any future non-vpp implemetations?

**Comment by edwarnicke** [comment]
Ilya,

I would tend to agree with you that CNI is one area of concern wrt various
public clouds.  But some of the issues we've hit are actually orthogonal to
CNI plugins (like for example the absense of /dev/vhost-net on GKE).  So we
can't say that all of the important differences are CNI plugins.

I am also a bit curious if we are OK across different CRI choices... there
have been some questions about us working with non-docker CRIs, like CRIO
or containerd.

Ed

**Comment by nickolaev** [comment]
@edwarnicke containerd mostly works. KInd was migrated to it a couple of weeks ago and it works OK in the CI of the examples repo. However, @matrohon told me that some skydive component call directly Docker through the Unix socket and this is broken in Kind with containeed.

**Comment by edwarnicke** [comment]
OK, so there is a skydive issue (which will look like an NSM issue to folks
trying to use skydive with NSM).  We do not see an actual NSM issue though,
correct?

Ed
