### ISSUE TITLE
suggest to use shorter package name

### ISSUE THREAD

**Issue by thinkerou** [networkservicemesh/networkservicemesh#1184]
now the package name is `github.com/networkservicemesh/networkservicemesh`, maybe `github.com/networkservicemesh/nsm` is better package name. thanks!

**Comment by nickolaev** [comment]
Thanks for the suggestion. However I don't think it is a good practice to shorten names on github. Like there is `kubernetes/kubernetes/`. One way they do it is to use a shorter domain name, like `k8s.io/kubernetes`. I don't think this is feasible at this point though.

@fkautz  @edwarnicke @haiodo, thoughts?

**Comment by haiodo** [comment]
Hi I’m agree with @nikolaev and do not see any practical benefits for having short name. Thanks
