### ISSUE TITLE
"go: error loading module requirements" in sircleci jobs

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1203]
## Expected Behavior

All go modules correctly downloaded

## Current Behavior

Tests fail with error
`go: error loading module requirements` 

## Failure Information (for bugs)

Workflows with error:
https://circleci.com/gh/networkservicemesh/networkservicemesh/63817
https://circleci.com/gh/networkservicemesh/networkservicemesh/63675

## Context

Try to use `scripts/go-mod-download.sh` before running go scripts

**Comment by lobkovilya** [comment]
From [here](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away):

> `go mod vendor` - resets the main module's vendor directory to include all packages needed to build and test all of the module's packages based on the state of the go.mod files and Go source code.
> 
> By default, go commands like go build ignore the vendor directory when in module mode.
> 
> The `-mod=vendor` flag (e.g., `go build -mod=vendor`) instructs the go commands to use the main module's top-level vendor directory to satisfy dependencies. The go commands in this mode therefore ignore the dependency descriptions in go.mod and assume that the vendor directory holds the correct copies of dependencies. Note that only the main module's top-level vendor directory is used; vendor directories in other locations are still ignored.

I suppose it is a very useful mechanism for us. @haiodo @edwarnicke @nickolaev what do you think?

**Comment by denis-tingajkin** [comment]
we could use partial vendoring for utilities like linter. Its possible with using `godep` or `govendor`.
What do you think?

**Comment by nickolaev** [comment]
It's a cloud native world - design for failure :)

I don't like (1) as it implies adding vendored code in our tree, let's avoid that. (2) is probably my favourite, as it is very often a network/service flakiness that leads to these issues.  Maintaining a docker image as proposed in (3) might be an additional burden to carry with the project, but is a generally good idea.
(4) the linter has both a docker image and a pre-compiled binary, why not use those? E.g. downlaod the binary unarchive it and put it in the $PATH so make can find it.
