### ISSUE TITLE
Do not close dataplane if we update local-dst with local-dst on nsm request

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1222]
## Expected Behavior

We closing dataplane for case local-dst with local-dst in nsm 

## Current Behavior

We do not close dataplane for case local-dst with local-dst in nsm 

## Steps to Reproduce

Run TestNSEHealLocal
## Context
More information about the problem https://github.com/ligato/vpp-agent/issues/1373
Entry point: nsm.go:287

**Comment by haiodo** [comment]
Closing.
