### ISSUE TITLE
Spec: DNS Integration for NSM

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1224]
## Overview

Network Service Mesh needs to be able to provide a workload with DNS service from Network Services Without breaking K8s DNS

## Link to the Google Docs document

[Spec](https://docs.google.com/document/d/1_1ICFEh2M3_Q8MvAQXNngP9UNQLgYgPgr58KYzib4C0/edit)

**Comment by nickolaev** [comment]
To me, it is yes and no at the same time. Let me explain.

Yes - the problem with resolving service names once we get the link is real and certainly, this will be a huge use-case. Augmenting the pod with an additional local CoreDNS is a powerful idea and as discussed can benefit beyond NSM. For sure the results of our work and experimentation will be something to share across the broader community.

No - I don't like how we are baking more and more IPAM properties in our core API. We already have IP addresses, routes and now we add DNS? I mean, NSM was supposed to be protocol agnostic and I believe this should be a major virtue of it. I would prefer if we refactor `message ConnectionContext` to use `map <string, string>` and keep these abstracted. I know how protobuf optimizes the messages, and my point is more about concepts. Imagine if we have to add all the MPLS specifics or whatever future protocols we want to support.

One more point to note here. I prefer if our admission controller stays flexible. the monitoring client and the CoreDNS injector need be optional, possibly by adding an annotation. Then we'll probably have to figure out a way to maintain our set of side-cars, which is feasible of course.

So overall, great and exciting feature, but let's be careful with the implementation and not embed assumptions in the API.

**Comment by edwarnicke** [comment]
@nickolaev I understand the desire to keep the API simple, and share it.

We originally started out with the map <string,string> for ConnectionContext.  It has two small issues that led to moving to the more descriptive API:

1. Its easy for implementors to get the strings for the map wrong
2. It gets harder to do more structures values as map<string,string> as you wind up putting formating into the string value.

Do you have thoughts on those two issues?

I also would like our admission controller to stay flexible.  On the other side we want to keep in mind:
1. Optimize for the average case
2. Keep dev interaction with the system simple

The current ConnectionContext was intentionally designed to allow even for the case where there is no IPAM at all for the connection (no IP, no route) for the case where you were looking at a truly L2 service.  Would want to think through how we might handle the situations you describe.  What happens if we don't get DNSConfig from any of the Network Services that the Pod is connecting to?  I think in that case our worst case is that the Pod gets a per-Pod DNS cache, at a cost of about 10 mb of RAM according to the CoreDNS folks we talked to at Kubecon.

@nickolaev Thoughts on these considerations?

**Comment by nickolaev** [comment]
@edwarnicke OK I agree that map<string, string> is harder to maintain an error-prone to implement. Can we then segment the context, something like this:

```proto
message IPContext {
    string src_ip_addr = 1;             /* source ip address + prefix in format <address>/<prefix> */
    string dst_ip_addr = 2;             /* destination ip address + prefix in format <address>/<prefix> */

    bool src_ip_required = 3;           /* if specified src_ip is required from NSE. */
    bool dst_ip_required = 4;           /* if specified dst_ip is required from NSE */

    repeated Route routes = 5;          /* a list of routes via dst_ip_addr as gateway */
    repeated string excluded_prefixes = 6; /* a list of excluded passed to NSE */

    repeated IpNeighbor ip_neighbors  = 7; /* A list of ARP table neighbours addresses */

    repeated ExtraPrefixRequest extra_prefix_request = 8;   /* A request for NSE to provide extra prefixes */
    repeated string extra_prefixes = 9; /* A list of extra prefixes requested */
}

message ConnectionContext {
   IPContext ip_context = 1;  /* IP related context */
}
```

The topic of flexible admission controller can be easily solved by making it smarter. We can have more complex side-car, which is dynamically programmed by the admssion controller through changing the command line, or a config map maybe. There are options.

**Comment by edwarnicke** [comment]
@haiodo You initially structured the ConnectionContext.  What are your thoughts on @nickolaev 's suggestion?

**Comment by edwarnicke** [comment]
@nickolaev So would you suggest the 'DNSConfig' become the 'DNSContext' in your proposal?

**Comment by nickolaev** [comment]
Yes, that makes sense. Although one can argue that the DNS config should be part of IPContext but I can agree we keep it separte. +1

**Comment by haiodo** [comment]
Sorry guys, was stuck meditating on improving CI :-)

I'm agree just map gives ability to pass any unstructured data, and are protocol agnostic.
But yes it is very hard to work with, and I was added a bit of structuring to it.

I'm not sure we will eventually need to put any MPLS, etc stuff inside context since context finally should contain only stuff required for client local environment and should describe only POD local possible network infrastructure, and I suppose list in this case are bit less. Like IP, Routes, ARP/DNS and possible some more but not MPLS, etc.

I'm pretty ok with moving to IPContext and DNSContext.

Also from current look it looks even weird to include IPContext/DNSContext at all and pass to client.

One place when it is required right now is healing, recovery from client monitor, in this case It potentially will require all possible information, but it also could be retrieved by some other tricks, will write my thoughts on ResiliencyV2.

I suppose we cloud try to think to replace it with generic map and for remote case to have special protobuf file with this contexts defined in case of Remote connections.
