### ISSUE TITLE
NSC needs few attempts for ping to be passed after Dataplane Heal

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1225]
## Expected Behavior

Ping should be passed from first attempt after connection recovery done

## Current Behavior

First few ping attempts are failing after connection recovery done

## Failure Information (for bugs)

TestDataplaneHealMultiNodesRemote:
Nsc keeps old arp entries with wrong NSE hardware address and it makes few failed ping attempts before receiving correct arp entry.

## Steps to Reproduce

Change `fixture.CheckNsc ` to `kubetest.CheckNSC` in TestDataplaneHealMultiNodesRemote and run test

**Comment by edwarnicke** [comment]
Interesting corner case.  How long does it take to fully restore connectivity?

**Comment by denis-tingajkin** [comment]
Looks like simple typo in `Steps to reproduce`. Should be `Change kubetest.HealCheckerNsc to kubetest.CheckNSC...`
