### ISSUE TITLE
nsm.request() is too complicated

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/networkservicemesh#1241]
## Expected Behavior

All methods should pass `gocyclo` linter check. 

## Current Behavior

`nsm.request()` fails `gocyclo` linter check - it is too complicated.

## Comment requested issue

https://github.com/networkservicemesh/networkservicemesh/pull/1239#discussion_r293323893

**Comment by haiodo** [comment]
@Bolodya1997 should we close this issue already?

**Comment by Bolodya1997** [comment]
No, it is still too complicated.
