### ISSUE TITLE
controlplane/pkg/apis/registry/registry.proto seems to have picked up internal implementation details

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1243]
## Current Behavior

[registry.proto](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto) should not have K8s implementation convenience functions.  We have picked up things starting at:

https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L69

That looks like internal implementations details may have leaked into this top level public API.

## Failure Information (for bugs)

This issue is to capture discussion on what may or may not need to be factored out of registry.proto into a different proto file in a different directory.

## Context

Network Service Mesh has a small number of architecturally fundamental APIs:

[remote.NetworkService](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.proto#L33)
[remote.MonitorConnection](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto#L74)
[registry.NetworkServiceRegistry](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L60)
[registry.NetworkServiceDiscovery](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L65)

These APIs are intentionally kept self contained, simple, and small in number.

That are at the heart of the architecture.  We have other APIs (example: [local.NetworkService](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/networkservice/networkservice.proto#L33)) that are specific to the K8s environment.

It looks like some things have crept into registry.proto that may be either K8s specific or otherwise scope bleed for the registry API.  We should discuss them here to figure out what is what and where they should go :)

**Comment by haiodo** [comment]
I think we should move 

```protobuf
message ClusterConfiguration {
    string podSubnet = 1;
    string serviceSubnet = 2;
}

message SubnetExtendingResponse {
    enum SubnetType {
        POD = 0;
        SERVICE = 1;
    }
    SubnetType type = 1;
    string subnet = 2;
}

service ClusterInfo {
    rpc GetClusterConfiguration(google.protobuf.Empty) returns (ClusterConfiguration);
    rpc MonitorSubnets(google.protobuf.Empty) returns (stream SubnetExtendingResponse);
}
```

Into cluster specific stuff.

NsmRegistry, NetworkServiceEndpointList - are used and required for every NSM to ensure it has proper registrations in registry after/during restart/healing process.

@lobkovilya Did you remember why we need ClusterInfo here?

**Comment by onobrod** [comment]
We had an internal discussion about the issue and @haiodo suggested an idea about applying plugin architecture to Network Service Mesh. Created a proposal (https://github.com/networkservicemesh/networkservicemesh/issues/1339) where it is described how the plugin architecture can help us with this issue in particular. @edwarnicke could you please take a look?
