### ISSUE TITLE
Revisit SDK usage

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#1258]
## Overview

I've been trying to use the SDK for creating a new client, and I feel it is too complicated for this usage.

Some open questions for improvments :

- The OUTGOING_NSC_NAME and ADVERTISE_NSE_NAME seem to correspond to network services name. Could they be renamed to OUTGOING_NS_NAME and ADVERTISE_NS_NAME?

- Shouldn't we split the sdk with a client part and an endpoint part? for simplicity towards people how just want to consume the sdk from their client, or develop an endpoint?

- the OUTGOING_NSC_NAME/LABEL variable is redundant with the NS_NETWORKSERVICEMESH_IO variable, when NS_NETWORKSERVICEMESH_IO is used with a single entry. Could we only keep NS_NETWORKSERVICEMESH_IO, which is in line with the annotation used for asking nsm to create the inteface with the init container?

**Comment by haiodo** [comment]
I think we should move 

```protobuf
message ClusterConfiguration {
    string podSubnet = 1;
    string serviceSubnet = 2;
}

message SubnetExtendingResponse {
    enum SubnetType {
        POD = 0;
        SERVICE = 1;
    }
    SubnetType type = 1;
    string subnet = 2;
}

service ClusterInfo {
    rpc GetClusterConfiguration(google.protobuf.Empty) returns (ClusterConfiguration);
    rpc MonitorSubnets(google.protobuf.Empty) returns (stream SubnetExtendingResponse);
}
```

Into cluster specific stuff.

NsmRegistry, NetworkServiceEndpointList - are used and required for every NSM to ensure it has proper registrations in registry after/during restart/healing process.

@lobkovilya Did you remember why we need ClusterInfo here?

**Comment by matrohon** [comment]
@haiodo i'm not sure to understand your comment. How it relates to the issue?

**Comment by haiodo** [comment]
Ouch, I’ve put comment to wrong issue:-)

**Comment by edwarnicke** [comment]
@nickolaev

**Comment by nickolaev** [comment]
Yeah there is a stale PR to address env variable renaming: #931 and then we discussed it in #866.
The SDK is already split to client and endpoint pakcages one woudl use only what they need.

We can keep only one of these if we decide, that should not be an issue as long as we all agree to do it. It will require substantial changes all over the testing package but is feasible.
