### ISSUE TITLE
Mismatch version between CRDs and example yamls

### ISSUE THREAD

**Issue by john-a-joyce** [networkservicemesh/networkservicemesh#1272]
## Expected Behavior

Be able to run to create networkmesh services from the service definition yaml files in the examples repo.   e.g.  kubectl apply -f examples/icmp/k8s/icmp-responder.yaml

should successfully create a service.  

## Current Behavior

Trying to run some of the examples from networkservicemesh/examples and the service creation fails due to version mismatch between the service definition yaml files and the CRD.   The apply will fail.  

error: unable to recognize "STDIN": no matches for kind "NetworkService" in version "networkservicemesh.io/v1alpha1"
/root/go/src/networkservicemesh.io/examples/mk/targets.mk:41: recipe for target 'k8s-icmp-icmp-responder-deploy' failed
make: *** [k8s-icmp-icmp-responder-deploy] Error 1

Note- failure text was via make but using kubectl apply gets the same root error. 

## Failure Information (for bugs)

kubectl describe crd networkservices.networkservicemesh.io -n nsm-system
Name:         networkservices.networkservicemesh.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"networkservices.networkservicemesh....
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-06-20T19:24:45Z
  Generation:          1
  Resource Version:    9133135
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/networkservices.networkservicemesh.io
  UID:                 0f8226c9-9391-11e9-81c8-000af71a15b8
Spec:
  Group:  networkservicemesh.io
  Names:
    Kind:       NetworkService
    List Kind:  NetworkServiceList
    Plural:     networkservices
    Short Names:
      netsvc
      netsvcs
    Singular:  networkservice
  Scope:       Cluster
  Version:     v1
Status:
  Accepted Names:
    Kind:       NetworkService
    List Kind:  NetworkServiceList
    Plural:     networkservices
    Short Names:
      netsvc
      netsvcs
    Singular:  networkservice
  Conditions:
    Last Transition Time:  2019-06-20T19:24:45Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2019-06-20T19:24:45Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
Events:                    <none>
------------------------------------------------------------------------------

cat examples/icmp/k8s/icmp-responder.yaml ---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: icmp-responder
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: simple-endpoint
      route:
        - destination:
          destinationSelector:
            app: icmp-responder

## Steps to Reproduce

1.  use make "k8s-deploy-infra" to deploy the base infra and the CRDs
2.   kubectl apply -f examples/icmp/k8s/icmp-responder.yaml

## Context

* Kubernetes Version:
* etc.

**Comment by john-a-joyce** [comment]
It looks like issue was that my two branches were pulled at different dates and in between the CRD version was changed to v1alpha1

**Comment by edwarnicke** [comment]
@john-a-joyce Thanks for keeping an eagle eye out for this sort if thing :)
