### ISSUE TITLE
Create VppMemifConnect in SDK 

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1275]
## Overview

Currently the various parts that plug incoming NSM Connections into VPP are all monolithic command private things like:

[vppagentComposite](https://github.com/edwarnicke/examples/blob/master/examples/vpp-icmp/vppagent-endpoint/cmd/composite.go#L33)
[vppAgentXConnComposite](https://github.com/edwarnicke/examples/blob/master/examples/secure-intranet/vppagent-endpoint/cmd/composite.go#L36)

This is a valid way to do it, but it would be nice to have reusable components that could be composed together to do various NSM related VPP things.

This Issue is to write a VppAgentMemifConnect in the [SDK](https://github.com/networkservicemesh/networkservicemesh/tree/master/sdk) to simply take an incoming Connection and plug it into VPP as a memif interface.

This should probably be put in an sdk/vppagent/ subdirectory.

The VppAgentMemifConnect should persist the name of the interface it created into the Opaque data so it can be used by other CompositeEndpoints in the Chain.

VppAgentMemifConnect should assign an IP address to the interface if and only if the ConnectionContext has a DstIp.

The VppAgentMemifConnect should persist the resulting DataChange to Opaque data so it can be added to by other CompositeEndpoints in the Chain.

The VppAgentMemifConnect should *not* write the DataChange to vppagent.

**Comment by edwarnicke** [comment]
[Hint](https://github.com/edwarnicke/examples/blob/master/examples/vpp-icmp/vppagent-endpoint/cmd/vppagent.go#L18)

**Comment by onobrod** [comment]
@edwarnicke why do we need to have a composite especially to do memif connect? Isn't it better just to have a connect that looks at mechanism type? It looks redundantly to me to have memif specified as mechanism type in the NS config and also use memif connect endpoint. We have [LocalConnectionConverter](https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/pkg/converter/local_connection_converter.go) in dataplane, will it be better to have connect composite that uses it?

**Comment by edwarnicke** [comment]
@onobrod The NSE is the one that *actually* picks the type of connection.  You could do a generic that has a default list ordered [memif,kernel interface] (ie, pick memif by default if available), and that could be configured with the opposite order.
