### ISSUE TITLE
Use VppAgentMemifConnect in vpp-icmp example

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1277]
## Overview

Use VppAgentMemifConnect (#1275) and VppAgentFlush (#1276) in [vpp-icmp example](https://github.com/edwarnicke/examples/blob/master/examples/vpp-icmp/vppagent-endpoint/cmd/endpoint.go#L37).

**Comment by onobrod** [comment]
`vpp-icmp` will be updated to use `universal-cnf` in https://github.com/networkservicemesh/examples/pull/24 so no need to update it to use the composites
