### ISSUE TITLE
Create VppAgentXCon in SDK

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1279]
## Overview

Create a VppAgentXCon in SDK to cross connect the results of VppAgentClientConnect (#1278) and VppAgentMemifConnect (#1275) (similar to what is done in [the secure-intranet-example](https://github.com/edwarnicke/examples/blob/master/examples/secure-intranet/vppagent-endpoint/cmd/composite.go#L36)

**Comment by onobrod** [comment]
If I got the task right, we want to have few small composites which share one DataChange object and append it with parts of config (MemifConnect and ClientConnect appends source and destination interfaces, XConnect appends XconnectPairs). It brings a question how to properly share DataChange object between composites (currently each composite only share its opaque data, it is kinda different thing), but it is doable, I think. What bothers me more is that we can create composites which are coupled a lot and should be used in a very specific order (ClientConnect should be called just after NewClientEndpoint to get its opaque data, then MemifConnect should be called, then XConnect). Why is it a bad idea to have one XConnect which calls [CrossConnectConverter](https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/pkg/converter/cross_connect_converter.go) from dataplane? Do we want to have an opportunity to reuse ClientConnect and XConnect separately without other VppAgent* compoistes? Could you please explain more on this?

**Comment by edwarnicke** [comment]
A few points of modularity:

We don't want to couple every NSE to the vpp-agent dataplane code.  It does a specific and particular thing, and we don't want changes made there that serve the vpp-agent dataplane to break the SDK.

Yes, there is a particular order, but by breaking things into composites you allow the replacement of particular pieces of the chain, and insertion of new behaviors between pieces of the chain.  

As to sharing the DataChange... GetOpaque was designed to allow carrying that kind of object along the chain.
