### ISSUE TITLE
Wrong selecting clusters for testing tasks if two or more clusters required

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1307]
## Expected Behavior
take available clusters from every clusters group

## Current Behavior
count available clusters just from one group

## Context
https://github.com/networkservicemesh/networkservicemesh/blob/0a0b2e2bce6283b8cfdc2bf72e4829f119febcd5/test/cloudtest/pkg/commands/main.go#L396-L404

**Comment by haiodo** [comment]
Thanks, will fix.
