### ISSUE TITLE
Rename NewFlush in sdk/vppagent

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1322]
Currently we have a composite NewFlush that 'flushes' vpp config to the vppagent.
It has been noted by @nickolaev @haiodo that this is a terrible name, and we want to fix it ASAP.

Current suggestions are:

NewVppUpdate
NewVPPUpdateRequest
NewSendVppUpdate
NewProgramVPP

It should be easy to fix once we've settled on the new name choice.

**Comment by edwarnicke** [comment]
#1304

**Comment by nickolaev** [comment]
It is actually about renaming the whole composite. I think "VppUpdate" should be fine.

**Comment by onobrod** [comment]
As I see in #1324 @edwarnicke have renamed the composite to `Commit` already

**Comment by edwarnicke** [comment]
@nickolaev Thoughts on renaming it to vppagent.Commit ?
