### ISSUE TITLE
Create KernelConnect in /sdk/vppagent

### ISSUE THREAD

**Issue by onobrod** [networkservicemesh/networkservicemesh#1325]
## Overview

In PR https://github.com/networkservicemesh/networkservicemesh/pull/1304 MemifConnect composite was added into /sdk/vppagent. MemifConnect creates a DataChange with Memif interface and stores it in opaque data. We need to have a similar KernelConnect composite in SDK.

## References

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1275
PR https://github.com/networkservicemesh/networkservicemesh/pull/1304

**Comment by onobrod** [comment]
I think it may be better to wait until SDK refactoring will be merged: https://github.com/networkservicemesh/networkservicemesh/pull/1324/files

**Comment by edwarnicke** [comment]
+1
