### ISSUE TITLE
Create ClientKernelConnect in /sdk/vppagent

### ISSUE THREAD

**Issue by onobrod** [networkservicemesh/networkservicemesh#1326]
## Overview

In PR #1304 ClientMemifConnect composite was added into /sdk/vppagent. ClientMemifConnect reads created outgoing connection from opaque data, creates a DataChange with Memif interface for this connection and stores it in opaque data. We need to have a similar ClientKernelConnect composite in SDK.

## References

Issue #1278
PR #1304

**Comment by onobrod** [comment]
I think it may be better to do it after SDK refactoring will be merged: https://github.com/networkservicemesh/networkservicemesh/pull/1324

**Comment by edwarnicke** [comment]
+1
