### ISSUE TITLE
Admission webhook ignores wrong pod specs

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1336]
## Expected Behavior

Admission webhook return error if pod spec is wrong

## Current Behavior

Admission webhook ignores the wrong pod spec.

## Input config example
```
	v1.Pod{
		ObjectMeta: v12.ObjectMeta{
			Name: name,
			Annotations: map[string]string{
				"ns.networkservicemesh.io": "icmp-responder?app=icmp",
			},
		},
		TypeMeta: v12.TypeMeta{
			Kind: "Deployment",
		},
		Spec: v1.PodSpec{
			Containers: []v1.Container{
				{
					Name:            "alpine-img",
					Image:           "alpine:latest",
					ImagePullPolicy: v1.PullIfNotPresent,
					Command: []string{
						"tail", "-f", "/dev/null",
					},
				},
			},
			InitContainers: []v1.Container {
				{
					Name:            "nsm-init",
					Image:           "nsm-init:latest",
					ImagePullPolicy: v1.PullIfNotPresent,
				},
			},
		},
	}
```
## Steps to Reproduce

Deploy Input config example.

**Comment by denis-tingajkin** [comment]
@edwarnicke , @nickolaev , @haiodo 
My point is user should know that manually adding nsm-init-container is redundant if he has nsm annotation. For now, we ignoring case if the user has manually added nsm-init container and nsm annotation.
Is current behavior OK?
Please share your thoughts.

**Comment by nickolaev** [comment]
PR merged, thanks
