### ISSUE TITLE
Spec: NSM Plugin Architecture

### ISSUE THREAD

**Issue by onobrod** [networkservicemesh/networkservicemesh#1339]
## Overview

The spec describes how plugin concept can be applied to Network Service Mesh and why it can be useful

## Link to the Google Docs document

[Spec](https://docs.google.com/document/d/1ETSCcSqklOZAlMMfiWp3x1O4J1o8OKnSprKZu68BTWg/edit?usp=sharing)

**Comment by edwarnicke** [comment]
This seems to me to be a good idea.  Would it make sense to use a registration mechanism that looks similar in the dataplane as well?

**Comment by onobrod** [comment]
@edwarnicke they are already similar: both dataplane and plugin send their socket locations on registration. And in both scenarios NSM is a registrar. Dataplane registration is more complicated: it has also a liveness stream and unregister service (maybe we will need unregister service too).
