### ISSUE TITLE
Spec: Get rid of device plugin

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1347]
## Overview
The specification describes the problems related with the device plugin, and how to solve them.

## Link to the Google Docs document
https://docs.google.com/document/d/10GOMUQEPUsfcSQZMCuUzWHd5etL-CI4zOA7f0uTWOLE/edit?usp=sharing

**Comment by nickolaev** [comment]
I have added a number of remarks in the doc, but the main one would be - can we use the NSMgr pod to host this new admission hook instead of proliferating the number of pods we need to operate.

**Comment by matrohon** [comment]
a device plugin was also considered for using physical hardware. See #727 
Do we plan to manage those allocations with an admission web hook too?

**Comment by haiodo** [comment]
@nickolaev yes, my intention was to put it as side car for NSMgr.

**Comment by haiodo** [comment]
@matrohon device plugin should be used for physical hardware, it is intend of device plugins, but right now we use it for workspace allocation and this causes few issues, like performance and impossibility of detection of workspace is not used anymore.

**Comment by nickolaev** [comment]
NSMgr is not going to inject hardware devices in the pods, it should stay hardware agnostic. That is the job of the forwarder.

**Comment by matrohon** [comment]
@haiodo ok, thanks. In the #727 context, the deviceplugin still makes sense, since it is about using a specific hardware. @nickolaev is right, this kind of deviceplugin should work along with the nsm forwarder, probably as a second container in the same pod.
