### ISSUE TITLE
Rename environment variable JAEGER_SERVICE_PORT_JAEGER to JAEGER_SERVICE_PORT

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#1360]
Should we rename this? The name feels unnecessarily redundant.

**Comment by edwarnicke** [comment]
Or we could simply use the standard Jaeger env variables:

https://github.com/jaegertracing/jaeger-client-go#environment-variables

And [config.FromEnv()](https://github.com/jaegertracing/jaeger-client-go/blob/master/config/config_env.go#L53)

**Comment by edwarnicke** [comment]
Would need to be fixed [here](https://github.com/networkservicemesh/networkservicemesh/blob/master/pkg/tools/tools.go#L178)
