### ISSUE TITLE
TestVPNNSCRemote sometimes fails

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1386]
## Expected Behavior
The test is stable

## Current Behavior
The test is not stable

## Failure Information (for bugs)
1) https://circleci.com/gh/networkservicemesh/networkservicemesh/81881?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/81310?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by haiodo** [comment]
Failed in PR: https://circleci.com/gh/networkservicemesh/networkservicemesh/99305?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment]
fond this in logs
```
fatal error: concurrent map iteration and map write

goroutine 27 [running]:
runtime.throw(0x1390388, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0007feef0 sp=0xc0007feec0 pc=0x42bea2
runtime.mapiternext(0xc00067d9e0)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0007fef78 sp=0xc0007feef0 pc=0x40ea67
runtime.mapiterinit(0x11e8f00, 0xc000684780, 0xc00067d9e0)
	/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc0007fef98 sp=0xc0007fef78 pc=0x40e3d9
reflect.mapiterinit(0x11e8f00, 0xc000684780, 0x0)
	/usr/local/go/src/runtime/map.go:1343 +0x54 fp=0xc0007fefc8 sp=0xc0007fef98 pc=0x40f8f4
reflect.Value.MapKeys(0x11e8f00, 0xc000684728, 0x195, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1138 +0xc4 fp=0xc0007ff040 sp=0xc0007fefc8 pc=0x4849b4
github.com/golang/protobuf/proto.(*TextMarshaler).writeStruct(0x1fb003e, 0xc000876e20, 0x12b4d40, 0xc000684720, 0x199, 0x199, 0x1531de0)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/text.go:325 +0xc6d fp=0xc0007ff228 sp=0xc0007ff040 pc=0x739f5d

```

**Comment by denis-tingajkin** [comment]
looks like it is related to https://github.com/networkservicemesh/networkservicemesh/issues/1624

**Comment by denis-tingajkin** [comment]
@haiodo can we close this issue?
