### ISSUE TITLE
Tests sometimes not failed even if Expect expression was not passed

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1392]
## Expected Behavior

Tests should fail if **Expect** expression was not passed 

## Current Behavior

Tests are continued even if **Expect** expression was not passed 

## Failure Information (for bugs)

Using of depricated testing functions can be the cause of this issue
`// Testing.T tests.  It is now deprecated and you should use NewWithT() instead.`

## Failure Logs

https://81881-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/azure-1/036-TestVPNNSCRemote-run.log

Test wasn't failed after 
```time="2019-07-24T19:00:55Z" level=error msg="Timeout waiting for logs pattern NSE: channel has been successfully advertised, waiting for connection from NSM... in vppagent-firewall-nse-1```
with 
```Expect(false).To(BeTrue())```

**Comment by edwarnicke** [comment]
@artem-belov Is this fixed?

**Comment by artem-belov** [comment]
@edwarnicke I am not sure. I am keeping tracking circle ci tests for such issues. This issue is not regularly reproducible
