### ISSUE TITLE
Example icmp/vpn are failing intermittently

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1397]
## Expected Behavior

CI tests to run reliably, and not fail intermittently.

Example icmp/vpn fail intermittently:
https://circleci.com/gh/networkservicemesh/networkservicemesh/82822

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/83978?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/84180?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/87132

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/91897

**Comment by denis-tingajkin** [comment]
examples were moved to helm. Example icmp is stable for now. For example vpn we have another issue https://github.com/networkservicemesh/networkservicemesh/issues/1623

**Comment by haiodo** [comment]
Closing since it is duplicate to #1623
