### ISSUE TITLE
NsmMonitorCrossConnectClient throws `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#1398]
## Expected Behavior

Tests should not fail.

## Current Behavior

` TestHealRemoteNSE` failed at least once with:

```
fatal error: concurrent map writes
fatal error: concurrent map writes
```

## Failure Information (for bugs)

[Full log](https://circleci.com/gh/networkservicemesh/networkservicemesh/82890?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by onobrod** [comment]
Duplicate of https://github.com/networkservicemesh/networkservicemesh/issues/1237

**Comment by edwarnicke** [comment]
@nickolaev Mind if we close this as a duplicate of #1237
