### ISSUE TITLE
helm chart default container tag values are inconsistent with build target defaults

### ISSUE THREAD

**Issue by tiswanso** [networkservicemesh/networkservicemesh#1493]
## Expected Behavior

Using helm charts directly should use sensible default values.  The default tag value of `master` is inconsistent with the docker build machinery's default of `latest`.

NSM shouldn't assume users are using make targets to do NSM installation.  Many users have tooling that integrates directly with helm.

## Current Behavior

If my workflow is...
1.  Modify NSM infra
1.  `make k8s-build`
1.  `make k8s-save`
1.  `for img in $(ls scripts/vagrant/images/*.tar); do echo $img; docker load -i $img; done`
1.  Use helm to install without modifying tag, ie. `helm template deployments/helm/nsm --namespace nsm-system --set global.JaegerTracing=true | kubectl apply -f -`

...NSM would not run with the images I just built because the default tag value in the helm chart has changed to `master`.  

## Steps to Reproduce

See current behavior section above.

## Context

The issue is potentially reproduced for anyone who uses helm directly, rather than the new `make helm-*` targets.

**Comment by nickolaev** [comment]
@tiswanso well the charts that we publish should fetch the images from dockerhub, hence `master`. Our make targets `helm-install-nsm` etc, do incorporate the right machinery to deploy with helm and set the images tags to `latest` unless specified otherwise in `CONTAINER_TAG` env.

Maybe we need to document it better?

**Comment by pringlewood** [comment]
I also had this issue, after speaking to @edwarnicke I understand why the images are tagged with master. If the releases are semantically versioned then production deployments should be pinned against this version number.

In the quickstart guide, if you do make `make helm-install-nsm` without  doing  `make k8s-save` and `make k8s-load-images` then helm will pull images tagged latest from dockerhub
when you do 'make helm-install-nsm' it spits out the following helm command

```
helm install --name=nsm \
        --wait --timeout 300 \
        --set org="networkservicemesh",tag="latest" \
        --set forwardingPlane="vpp" \
        --set admission-webhook.org="networkservicemesh",admission-webhook.tag="latest" \
        --namespace="`cat "k8s/conf/namespace-nsm.yaml" | awk '/name:/ {print $2}'`" \
        deployments/helm/nsm
```

which gives you an image 3 months old.

I can attempt to fix this but need some direction, so some options:

1) Make circleci tag latest on every push to Dockerhub, change helm charts tag to latest 
2) Rework the quickstart guide to not use make to deploy helm resources and be explicit about the tag being master.
3) set the CONTAINER_TAG to master in the makefile, Could be problematic for people building images locally as these are tagged as latest in the local docker build.
