### ISSUE TITLE
Right after namespace creation "default" service account is not exist

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1495]
## Failure Information (for bugs)

TestExec: https://circleci.com/gh/networkservicemesh/networkservicemesh/89411?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

## Related issue
https://github.com/kubernetes/kubernetes/issues/66689

## Possible solution
Seems like `default` service account in newly created namespace appears not instantly, and we need some retry or wait until it will be created

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/100752?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by haiodo** [comment]
Closing since merged.
