### ISSUE TITLE
Create protobuf Connection that wraps local.Connection and remote.Connection

### ISSUE THREAD

**Issue by onobrod** [networkservicemesh/networkservicemesh#1497]
## Overview
Currently we have the `Connection` interface and two protobuf `Connection` messages (local and remote):
- interface: https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/nsm/connection/connection.go
- local: https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/connection.proto
- remote: https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto

The interface is useful to work with both connection types in methods like `Request()`. But there is no way to work with both connection types in gRPC methods since we cannot use an interface as an input parameter in gRPC.

There is a solution — we can implement a connection wrapper protobuf message which has oneof field. I've already done this:
https://github.com/networkservicemesh/networkservicemesh/blob/aa8a648ad10de425338cc5d0b3229db2626fd9fc/controlplane/pkg/apis/plugins/connection_plugin.proto#L9
https://github.com/networkservicemesh/networkservicemesh/blob/aa8a648ad10de425338cc5d0b3229db2626fd9fc/controlplane/pkg/apis/plugins/connection_plugin_helpers.go

As the next steps we may:
1) move the wrapper and the helpers into /apis/nsm/connection
2) rename the wrapper to Connection (also I suggest to rename 'conn' field into 'impl' — this naming looks more suitable)
3) implement all the methods which are defined in Connection interface
4) replace all interface usages with our wrapper and remove the interface (also need to rename all variables named 'wrapper' into 'connection' — only in plugins)

**Comment by onobrod** [comment]
+ same for request (local and remote)

**Comment by edwarnicke** [comment]
Lets talk more about this... these are separated intentionally.
