### ISSUE TITLE
Introduce RemoteMechanism 'LOCAL' and refactor NSMgr to use

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1510]
## Motivation

NSMgr has historically been complicated by the fact that we have two similar but intentionally distinct APIs:

local.NetworkService
remote.NetworkService

These are distinct because local clients should *not* be able to express intent around remote Mechanisms, and vice versa.

This has had the side effect that we have a branching of code paths in the NSMgr after selection of a NSE.  If the NSE is local, we do a bunch of local things.  If its remote we do a bunch of remote things.  This has been dealt with by abstracting to an internal API that makes fuzzy the distinction between local and remote.  While this is a time honored approach, it increases complexity and makes it harder for more casual developers to follow what is going on in the code and productively make changes.

Additionally, when we look at trying to implement the 'create pNSMgr', we can imagine a situation where that pNSMgr runs an NSE on the same Node as the requestor, and needs a way to communicate back to the nodes NSMgr to connect to the newly created NSE.  We have no semantics to support that currently.

This PR proposes to resolve that by making the call through the NSMgr *linear* (not branched.

The new proposed call chain is simple:

Same Node:
![Node Local](https://user-images.githubusercontent.com/1455208/63349820-d49e6c00-c321-11e9-9ef9-2e22cfffb2df.png)

Different Node:
![Remote Node](https://user-images.githubusercontent.com/1455208/63349835-dff19780-c321-11e9-90fb-09fbb3816b4d.png)

Create pNSMgr:
![Create pNSMgr](https://user-images.githubusercontent.com/1455208/63349854-eb44c300-c321-11e9-94ba-96712970533a.png)

It is important to note that these three cases look *exactly the same* inside the NSMgr.  There is no logic in distinguishing local vs remote cases... because all calls follow the same call flow... its only *selection* of NSE that will *cause* a difference due to the difference in NSMgr being address (node local NSMgr, remote NSMgr, or pNSMgr).

## LOCAL remote.MechanismType
In order to achieve this, we will need to add a LOCAL remote.MechanismType, with parameters:

* SourceNSMgrName
* SourceConnectionId
* DestinationConnectionId

The local.NetworkServiceServer should put the Connection object  in a store available to the remote.NetworkService in the same NSMgr.  Then the local.NetworkServiceServer in the NSMgr should always offer mechanism type LOCAL at top priority when calling remote.NetworkService.  

The remote.NetworkServiceServer in the NSMgr should consider the LOCAL MechanismType when it is for itself (as determined via NSMgrName).  It should then lookup the Connection in the shared Connection store with the local.NetworkServiceServer, and use that as the Source in the CrossConnect to the Dataplane API.

## Handling Monitoring and Healing
Monitoring and Healing should be simplified as there is no logical switch between purely local CrossConnects and CrossConnects that have a Remote component.

**Comment by haiodo** [comment]
@edwarnicke I think we could close this one?
