### ISSUE TITLE
CrossConnect Server sending empty statistics for metrics

### ISSUE THREAD

**Issue by ivanayov** [networkservicemesh/networkservicemesh#1512]
Related to exposing metrics for #1263

The cross connect monitor server should send statistics with the UPDATE event
[crossconnect_monitor_server.go#L38](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/monitor/crossconnect/crossconnect_monitor_server.go#L38), but statistics are actually empty in [metrics_collector.go#L80](https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/metrics_collector.go#L80) and so in the `cross connect_monitor` log:
```
metrics:<key:\"SRC-6\" value:<metrics:<key:\"rx_bytes\" value:\"0\" > metrics:<key:\"rx_error_packets\" value:\"0\" > metrics:<key:\"rx_packets\" value:\"0\" > metrics:<key:\"tx_bytes\" value:\"0\" > metrics:<key:\"tx_error_packets\" value:\"0\" > metrics:<key:\"tx_packets\" value:\"0\" >
```

When running `basic_monitor_crossconnect_metrics_test.go` results look ok:
```
SRC-1 metrics:<key:\"rx_bytes\" value:\"476\" > metrics:<key:\"rx_error_packets\" value:\"0\" > metrics:<key:\"rx_packets\" value:\"6\" > metrics:<key:\"tx_bytes\" value:\"476\" > metrics:<key:\"tx_error_packets\" value:\"0\" > metrics:<key:\"tx_packets\" value:\"6\" > "
```
but the test does not get metrics sent from the crossconnect monitor server.

**Comment by quangtamle** [comment]
Hi @ivanayov ,

I also have the same problem like yours. I tried to create some traffic by doing "make k8s-***-check" but still no changes happend in the metric logs. I wonder whether it's normal behavior or not.

One more thing, I tried to create and delete some crossconnects (in order to create CrossConnectEvent) in the example folder and somehow the metric values of some of the crossconnects are no longer empty (to be exact, it's 90 and always that number, I tried many times in several day but it's always 90). It's strange
![values](https://user-images.githubusercontent.com/43220759/63412825-c8391280-c3f8-11e9-859f-bb53a4e59e61.png)

**Comment by denis-tingajkin** [comment]
@ivanayov  I can look at this Issue, could you please attach logs and steps to reproduce?
@fkautz  Can you please assign this Issue on me?

**Comment by ivanayov** [comment]
@denis-tingajkin 
This is some data from the `crossconnect-monitor` log:
```
msg="====== monitorCrossConnects event: type:UPDATE cross_connects:<key:\"1\" value:<id:\"1\" payload:\"IP\" local_source:<id:\"1\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"nsm0\" > parameters:<key:\"netnsInode\" value:\"4026532588\" > parameters:<key:\"socketfile\" value:\"nsm0/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-4\" > > context:<ip_context:<src_ip_addr:\"10.20.1.9/30\" dst_ip_addr:\"10.20.1.10/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > > remote_destination:<id:\"5\" network_service:\"icmp-responder\" mechanism:<type:VXLAN parameters:<key:\"dst_ip\" value:\"172.28.128.193\" > parameters:<key:\"src_ip\" value:\"172.28.128.192\" > parameters:<key:\"vni\" value:\"2\" > > context:<ip_context:<src_ip_addr:\"10.20.1.9/30\" dst_ip_addr:\"10.20.1.10/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > source_network_service_manager_name:\"kube-master\" destination_network_service_manager_name:\"kube-worker1\" network_service_endpoint_name:\"icmp-responderjbplp\" > > > cross_connects:<key:\"2\" value:<id:\"2\" payload:\"IP\" local_source:<id:\"2\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"nsm0\" > parameters:<key:\"netnsInode\" value:\"4026532738\" > parameters:<key:\"socketfile\" value:\"nsm0/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-23\" > > context:<ip_context:<src_ip_addr:\"10.20.1.1/30\" dst_ip_addr:\"10.20.1.2/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > > local_destination:<id:\"3\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmb9RJkzJf0\" > parameters:<key:\"netnsInode\" value:\"4026532667\" > parameters:<key:\"socketfile\" value:\"nsmb9RJkzJf0/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-21\" > parameters:<key:\"workspaceNseName\" value:\"icmp-responderdq7wz\" > > context:<ip_context:<src_ip_addr:\"10.20.1.1/30\" dst_ip_addr:\"10.20.1.2/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > > > > cross_connects:<key:\"4\" value:<id:\"4\" payload:\"IP\" local_source:<id:\"4\" network_service:\"icmp-responder\" mechanism:<type:MEM_INTERFACE parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"if1\" > parameters:<key:\"netnsInode\" value:\"4026532905\" > parameters:<key:\"socketfile\" value:\"if1/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-14\" > > context:<ip_context:<src_ip_addr:\"10.30.1.5/30\" dst_ip_addr:\"10.30.1.6/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > > remote_destination:<id:\"9\" network_service:\"icmp-responder\" mechanism:<type:VXLAN parameters:<key:\"dst_ip\" value:\"172.28.128.193\" > parameters:<key:\"src_ip\" value:\"172.28.128.192\" > parameters:<key:\"vni\" value:\"4\" > > context:<ip_context:<src_ip_addr:\"10.30.1.5/30\" dst_ip_addr:\"10.30.1.6/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > source_network_service_manager_name:\"kube-master\" destination_network_service_manager_name:\"kube-worker1\" network_service_endpoint_name:\"icmp-responderz7jsn\" > > > 
```
Metrics for the same event (separating for visibility):
```
metrics:<key:\"SRC-4\" value:<metrics:<key:\"rx_bytes\" value:\"0\" > metrics:<key:\"rx_error_packets\" value:\"0\" > metrics:<key:\"rx_packets\" value:\"0\" > metrics:<key:\"tx_bytes\" value:\"0\" > metrics:<key:\"tx_error_packets\" value:\"0\" > metrics:<key:\"tx_packets\" value:\"0\" > > >
```
This is what I print in the `vppagent_dataplane` log where statistics are empty:
```
msg="================= Calling handleNotifications: notification: next_idx:3 notification:<vpp_notification:<interface:<type:UPDOWN state:<name:\"DST-1\" if_index:2 admin_status:UP oper_status:DOWN last_change:1566392858 statistics:<> > > > > 
```
Those empty statistics are received directly from the gRPC and it looks more like a problem in ligato than a bug from our side, except we've missed some specific configuration. I didn't find any though.

More logs from the `vppagent_dataplane` 
```
2019-08-21 13:07:39,699 DEBG 'vppagent-dataplane' stdout output:
time="2019-08-21T13:07:39Z" level=info msg="Try to send message type:UPDATE cross_connects:<key:\"1\" value:<id:\"1\" payload:\"IP\" remote_source:<id:\"1\" network_service:\"icmp-responder\" mechanism:<type:VXLAN parameters:<key:\"dst_ip\" value:\"10.44.0.2\" > parameters:<key:\"src_ip\" value:\"10.32.0.4\" > parameters:<key:\"vni\" value:\"2\" > > context:<ip_context:<src_ip_addr:\"172.16.1.1/30\" dst_ip_addr:\"172.16.1.2/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"app\" value:\"icmp\" > source_network_service_manager_name:\"kube-master\" destination_network_service_manager_name:\"kube-worker1\" network_service_endpoint_name:\"icmp-responderxlcpk\" > local_destination:<id:\"2\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmxjbNNN7dQ\" > parameters:<key:\"netnsInode\" value:\"4026532394\" > parameters:<key:\"socketfile\" value:\"nsmxjbNNN7dQ/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-15\" > parameters:<key:\"workspaceNseName\" value:\"icmp-responderxlcpk\" > > context:<ip_context:<src_ip_addr:\"172.16.1.1/30\" dst_ip_addr:\"172.16.1.2/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" > > > > > metrics:<key:\"SRC-1\" value:<metrics:<key:\"rx_bytes\" value:\"0\" > metrics:<key:\"rx_error_packets\" value:\"0\" > metrics:<key:\"rx_packets\" value:\"0\" > metrics:<key:\"tx_bytes\" value:\"0\" > metrics:<key:\"tx_error_packets\" value:\"0\" > metrics:<key:\"tx_packets\" value:\"0\" > > > "
```

`basic_monitor_crossconnect_metrics_test` is not using vpp and is successful.

**Comment by ivanayov** [comment]
Steps to reproduce:
1. Log event metrics in  [crossconnect_monitor.go#L58](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/crossconnect-monitor/crossconnect_monitor.go#L58)
2. Log state in [metrics_collector.go#L73](https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/metrics_collector.go#L73)
3. Deploy infra
4. Deploy imp
5. k8s-check
6. Check `crossconnect-monitor` and `nsm-vppagent-dataplane` logs

**Comment by denis-tingajkin** [comment]
By simple investigation found that vpp agent publishes notifications only on InterfaceNotification_UPDOWN or InterfaceState_DELETED. Will try to provide a native solution into vpp-agent repo and ask the question about the solution.

**Comment by denis-tingajkin** [comment]
created Issue in vpp-agent repo: https://github.com/ligato/vpp-agent/issues/1450

**Comment by denis-tingajkin** [comment]
https://github.com/ligato/vpp-agent/pull/1451#issuecomment-527046272

**Comment by BoutheinaDab** [comment]
@ivanayov and @denis-tingajkin , I have got similar similar issue with logs from the vppagent_dataplane, and from crossconnect-monitor.
However, for logs from k8s-nsmgr, I can get non empty metrics statistics for Update events:

> `time="2019-09-04T12:52:16Z" level=info msg="NSM-DataplaneMonitor(vppagent): Received event: &{{UPDATE map[]} map[mgmt:metrics:<key:\"rx_bytes\" value:\"5218648\" > metrics:<key:\"rx_error_packets\" value:\"0\" > metrics:<key:\"rx_packets\" value:\"11996\" > metrics:<key:\"tx_bytes\" value:\"0\" > metrics:<key:\"tx_error_packets\" value:\"0\" > metrics:<key:\"tx_packets\" value:\"0\" > ]}"
`
Have you any idea please how can I obtain these stats even from the controplane?

**Comment by edwarnicke** [comment]
I've added a comment to [ligato/vpp-agent#1451](https://github.com/ligato/vpp-agent/pull/1451#issuecomment-527046272).  We need real stats reported at an interval from vpp-agent.  I'll push to get them.

**Comment by edwarnicke** [comment]
@denis-tingajkin @ivanayov @BoutheinaDab Looks like vpp-agent will be supporting getting us interface stats at intervals: 

https://github.com/ligato/vpp-agent/pull/1451#issuecomment-527974087

**Comment by edwarnicke** [comment]
https://github.com/ligato/vpp-agent/pull/1495 appears to have committed a fix for this for us.

**Comment by BoutheinaDab** [comment]
> [ligato/vpp-agent#1495](https://github.com/ligato/vpp-agent/pull/1495) appears to have committed a fix for this for us.

Great! I will try it. Thank you

**Comment by denis-tingajkin** [comment]
still blocked by https://github.com/ligato/vpp-agent/pull/1451#issuecomment-544200835

**Comment by denis-tingajkin** [comment]
@ivanayov should be fixed with 1983, can you please check?

**Comment by ivanayov** [comment]
It's working as expected now and metrics are triggered to Prometheus as well.
