### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [networkservicemesh/networkservicemesh#1518]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [prometheus/prometheus](https://github.com/prometheus/prometheus), [coredns/coredns](https://github.com/coredns/coredns), [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by edwarnicke** [comment]
@yevgenypats We'd welcome a PR :)

**Comment by yevgenypats** [comment]
ccing @bookmoons who will take the lead on that:)

**Comment by edwarnicke** [comment]
@bookmoons welcome!  Would you mind if I added you as read to the repo and assigned this issue to you so we can track?

**Comment by bookmoons** [comment]
Thanks a lot guys. Yes please do set it all up. I'm working toward this in [`bookmoons/fuzz`](https://github.com/bookmoons/networkservicemesh/tree/bookmoons/fuzz).

**Comment by bookmoons** [comment]
The docs are really good. Love the sequence diagrams.

I've got my head around the major concepts. Will be digging through the code soon to find the right pieces to fuzz.

**Comment by bookmoons** [comment]
https://github.com/networkservicemesh/networkservicemesh/compare/2552d88473e2de53d705181f5d6384f4a8456c82...bookmoons:ce1d9640fcbc73e96f71e790bce3f56073c0d92f has something toward this. It fuzzes some of the little parsers scattered around.

* `dataplane/pkg/common/egress_interface` - parseProcFile.
* `dataplane/pkg/common/egress_interface` - parseGatewayIP.
* `pkg/tools` - ParseAnnotationValue.
* `pkg/tools` - ParseKVStringToMap.
* `utils/caddyfile` - Caddyfile parsing.

Do you have any ideas about a few higher value targets?

Connection negotiation seems like something that should be fuzzed. It's not obvious to me how to set up a fixture for that. Is there a test or something that gives a good example?

The code is well organized. Always a relief to read lucid code.

**Comment by bookmoons** [comment]
Each of the egress fuzzers found a crash. I'm attaching here. Both are index bound errors. The unsuffixed file is the crashing input. Gateway IP parsing also crashes on empty input.

These are both private functions so maybe there's validation elsewhere.

[crashers.ProcFile.zip](https://github.com/networkservicemesh/networkservicemesh/files/3612440/crashers.ProcFile.zip)
[crashers.GatewayIP.zip](https://github.com/networkservicemesh/networkservicemesh/files/3612441/crashers.GatewayIP.zip)

**Comment by edwarnicke** [comment]
@bookmoons Thank you so much for I've filed issues for both of these (should be good starter problems for folks to fix).  I presume someone can reproduce the issues using https://github.com/networkservicemesh/networkservicemesh/compare/2552d88473e2de53d705181f5d6384f4a8456c82...bookmoons:ce1d9640fcbc73e96f71e790bce3f56073c0d92f?

**Comment by edwarnicke** [comment]
Connection negotiation should definitely be a fuzzed.  @haiodo suggestions on how @bookmoons might set up a fixture for them (or pointers to where you guys have in the unit tests?)

**Comment by bookmoons** [comment]
Running the fuzzer should hit those issues again. Details are in the [go-fuzz readme](https://github.com/dvyukov/go-fuzz). Function names are:
* `FuzzParseProcFile`
* `FuzzParseGatewayIP`

You could also maybe write unit tests for them. Tried to add some for those 2 cases. Links are in the issues.

**Comment by bookmoons** [comment]
Hi guys. I'll have another look through this and see if I can dig out an example of that fixture.

**Comment by edwarnicke** [comment]
@bookmoons Excellent!  @pringlewood  is working some of the existing fuzzing bugs :)

**Comment by bookmoons** [comment]
Is there someone who can point me at the right logic here? There's connection logic in several different places. It's not clear to me where that negotiation is happening.

**Comment by edwarnicke** [comment]
I believe if its connections over a Unix file socket its here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/pkg/tools/socket.go#L114

And over TCP is here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/pkg/tools/socket.go#L132

**Comment by bookmoons** [comment]
Thanks a lot @edwarnicke. Missed that socket file, I was looking for things named connection.

**Comment by bookmoons** [comment]
I'm not really finding a channel to get the fuzz to the right place. What would you think about getting the fuzzers we have running? You might as well get some testing out of them since they're ready to use.

I'd be happy to write this one if someone could show me the right setup on the NSM side. I think you'd want to start a test service, do preliminary exchange to get to negotiation, then hit negotiation logic with a raw byte stream. Connection properties offered by the service could be varied deterministically based on fuzz. Seems like there must be a way to do it, but maybe nothing is ready made because it's not really normal usage. Maybe it's all underneath abstractions.

>New connections negotiate their connection properties. These properties include but are not limited to: The type of network interface, for example Linux Interface, MemIf, or vhost-user; The payload type, for example Ethernet, IP, MPLS, or L2TP.

>The network service, SDN, and client negotiate with each other the parameters of the tunnel.

**Comment by edwarnicke** [comment]
So it sounds like you are wanting to:

a)  Run a component that takes input from the network (usually GRPC in our case)
b)  Feed it fuzz
c)  See what falls out

Correct?   Would using helm to deploy the [nsm system](https://github.com/networkservicemesh/networkservicemesh/tree/master/deployments/helm/nsm) in Kubernetes work?  Or is that more complex than what you are looking for?

If so, the place to start fuzzing would likely be to deploy the fuzzer in a container with a Pod spec similar to [vpp-icmp-responder](https://github.com/networkservicemesh/networkservicemesh/blob/master/deployments/helm/vpp-icmp-responder/templates/vppagent-nsc.tpl) in form, but replacing the container image with your fuzzer component.

The socket your fuzzing container wants to open will be specified by the [NSM_SERVER_SOCKET](https://github.com/networkservicemesh/networkservicemesh/blob/master/sdk/common/constants.go#L5) env variable (injected by the K8s DevicePlugin).

Does that help?

**Comment by bookmoons** [comment]
Yeah that's seems about right. This seems promising, I'll have a look. But I wonder if it's heavy for a fuzzer. The binary will reconstruct the fixture each iteration, so I think you'd end up starting Kubernetes fresh and deploying every iteration. It might make it pretty slow. Is there a way to set that up with the underlying pieces stubbed out?

**Comment by edwarnicke** [comment]
@bookmoons Should be doable.  We have some unit tests that do something quite similar to what you are describing.  Give me a bit to find examples :)
