### ISSUE TITLE
no nsm-init:latest on dockerhub

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#1526]
the nsm-init image on docker hub has no tag latest: 

https://hub.docker.com/r/networkservicemesh/nsm-init/tags

This tag is used by default by the admission webhook:

https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/admission-webhook/const.go#L19

We cannot used the admission webhook without building and pushing the nsm-init image manually.

**Comment by haiodo** [comment]
@edwarnicke As I remember you wanted to check something here?

**Comment by nickolaev** [comment]
There is no nsm-init in 0.1.0:
https://github.com/networkservicemesh/networkservicemesh/blob/release-0.1/k8s/cmd/admission-webhook/impl.go#L50

**Comment by nickolaev** [comment]
`make helm-install-nsm` sets the proper tags:
https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/helm.mk#L35

We might want to change some defaults here and there though.
