### ISSUE TITLE
CI unstable on master Example-helm-vpn

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1532]
## Expected Behavior

CI is expected to pass reliably on master.

## Current Behavior

CI is failing intermittently on master

## Failure Information (for bugs)

https://circleci.com/gh/networkservicemesh/networkservicemesh/92559
https://circleci.com/gh/networkservicemesh/networkservicemesh/92558

**Comment by denis-tingajkin** [comment]
Test `TestDNSMonitoringNsc` will be fixed by this PR: https://github.com/networkservicemesh/networkservicemesh/pull/1521
For now  `TestDNSMonitoringNsc`  disabled on master

**Comment by artem-belov** [comment]
TestInterdomainNSMHealRemoteDieNSMD fixed with pr #1538

**Comment by haiodo** [comment]
Reproduced with:
https://circleci.com/gh/networkservicemesh/networkservicemesh/98623?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment]
duplicate of https://github.com/networkservicemesh/networkservicemesh/issues/1623

**Comment by haiodo** [comment]
Closing since it is duplicate to #1623
