### ISSUE TITLE
TestInterdomainNSCDies is unstable on CI

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1561]
## Failure Logs

1) https://circleci.com/gh/networkservicemesh/networkservicemesh/94372
2) https://circleci.com/gh/networkservicemesh/networkservicemesh/95117
3) https://circleci.com/gh/networkservicemesh/networkservicemesh/94212
4) https://circleci.com/gh/networkservicemesh/networkservicemesh/95606

**Comment by haiodo** [comment]
@artem-belov could you please take a look: it still could happen: https://circleci.com/gh/networkservicemesh/networkservicemesh/116237?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
