### ISSUE TITLE
EthernetContext

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1563]
## Overview

As noted in #1225, we can have situations where autohealing results in temporary ping failures because the ethernet address for the IP address changes, and thus existing arp table entries are wrong.

What this reveals is a lack of proper ```EthernetContext``` in ```ConnectionContext``` to convey optionally the dst/src ethernet addresses.

The basics are fairly simple.  Add to [ConnectionContext](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/connectioncontext/connectioncontext.proto#L77) a new submessage 'EthernetContext':

```proto
message ConnectionContext {
    IPContext ip_context = 1; /* IP related context */
    DNSContext dns_context = 2; /* DNS related context */
    EthernetContext = 3; /* Ethernet related context */
}
```

where EthernetContext is defined as:

```proto
message EthernetContext {
   string src_mac_address = 1; /* Mac address of source side of connection */
   string dst_mac_address = 2; /* Mac address of destination side of connection */
}
```

# Implementation Changes

## Forwarders
The [vppagent-forwarder](https://github.com/networkservicemesh/networkservicemesh/tree/master/dataplane/vppagent) and [kernel-forwarder](https://github.com/networkservicemesh/networkservicemesh/tree/master/dataplane/kernel-forwarder) will need to be updated such that if and only if there is an EthernetContext with a properly set src_mac_address is set, and the mechanism is 'kernel interface' we set the mac address.  Likewise for NSEs with mechanism kernel interface and dst_mac_address set.

## NSE Composite Endpoint

Once #1524 has been merged (soon), write a Composite Endpoint analogous to the IPAMEndpoint that adds an EthernetContext with a [locally administered](http://www.noah.org/wiki/MAC_address#locally_administered_address) dst_mac_address for the Endpoint.  Modify the [vppagent.MemifConnect](https://github.com/networkservicemesh/networkservicemesh/pull/1524/files#diff-c69e69e1dbbcae3efe6b8d16e38e8bd2) to apply the dst_mac_address if provided.

Modify the [vppagent.ClientMemifConnect](https://github.com/networkservicemesh/networkservicemesh/pull/1524/files#diff-6e5547a57fb01ef859eb3f928545c54c) to apply the src_mac_address if provided.

## References
#1225

**Comment by denis-tingajkin** [comment]
In progress

**Comment by denis-tingajkin** [comment]
blocked by https://github.com/ligato/vpp-agent/issues/1509

**Comment by denis-tingajkin** [comment]
Faced with a new problem. Reported to vpp-agent https://github.com/ligato/vpp-agent/issues/1525

**Comment by denis-tingajkin** [comment]
PR provided but we can't merge it. We need wait for https://github.com/ligato/vpp-agent/issues/1528
