### ISSUE TITLE
Spec: Switch MechanismType from enum to string

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1564]
## Overview

Network Service Mesh on K8s delegates from the Network Service Manager (NSMgr) to the  NSM Forwarder (formerly NSM Dataplane) performing the cross connect between the mechanisms from each side of a vWire.  Examples:
* (kernel interface, memif)
* (kernel interface, vxlan)
* (vxlan, memif)
* (SRv6, kernel interface)
* (SRIOV VF, vlan)
* (HW NIC, vxlan)
The NSM Forwarder is the only portion of the NSM system in K8s that has privilege.

NSM was always intended to support arbitrary mix and match of MechanismTypes.

Currently, we use an enumeration of [local.MechanismType](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/connection.proto#L32) and [remote.MechanismType](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto#L31).  This enum also represents a requirement when one adds a Mechanism type to alter the enum, thus acting as a bottleneck in the system.

Example:
If I wish to add a remote.Mechanism type IPSEC, I would need to add an entry to the enum in the proto file, and wait for it to be released, and then broadly adopted.

# Solution
Change [local.MechanismType](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/connection.proto#L32) and [remote.MechanismType](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto#L31) to be strings.  Provide constants in [remote constants.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/constants.go) and [local constants.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/constants.go) for MechanismTypes for which we currently have support (not prospective MechanismTypes).

Examples:
```go
const (
    KERNEL_INTERFACE = "KERNEL_INTERFACE"
    MEMIF = "MEMIF"
)
```

Fix controlplane, dataplane, and [examples](https://github.com/networkservicemesh/examples) to use the new MechanismType.

**Comment by edwarnicke** [comment]
@rdimitrov Could you have a look at this and let me know what you think?

**Comment by rdimitrov** [comment]
Looks good to me 👍 It makes sense to avoid the troubles of updating the corresponding proto files. Nevertheless, we'll still keep track of the "verified/adopted" mechanism types in their corresponding "constants.go" file, right?

**Comment by edwarnicke** [comment]
@rdimitrov Yes... but that's a much 'softer' limit than the enum :)

Think of it as emergent behavior.  You and I both decide that we want to provide 'IPSEC'.  You pick the string 'IpSec', I pick 'IPSEC'... neither of us is blocked... but at some point, we want to put into the constant files *one* of those strings so we get proper interop.

**Comment by rdimitrov** [comment]
Indeed. Great then! 👍

**Comment by edwarnicke** [comment]
Suggest we wait a bit on this pending #1657

**Comment by denis-tingajkin** [comment]
@edwarnicke ok, let's wait
