### ISSUE TITLE
Make SDK to have minimal dependencies for clients.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1577]
## Overview

We need to move SDK and all stuff for client/endpoint vendors into a separate repository.

Right now it is really hard to depend on NSM main repository, since it has a lot of dependencies not really required to writing clients/endpoints.

**Comment by edwarnicke** [comment]
@nickolaev @fkautz Thoughts on this?  I know @fkautz hit some of these issues to... is this something we want to do sooner rather than later?

**Comment by edwarnicke** [comment]
@haiodo How would this relate to APIs?

**Comment by edwarnicke** [comment]
We might also go the route of multi-module repos: https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories

**Comment by haiodo** [comment]
@edwarnicke I've also thinking about multi module repository.
