### ISSUE TITLE
Connection fails in Kernel-forwarder after a long test

### ISSUE THREAD

**Issue by rdimitrov** [networkservicemesh/networkservicemesh#1582]
## Expected Behavior

No unexepected errors.

## Current Behavior

In case of doing a continious and longer test(>3 hours), sometimes the connection seems to fail with messages like there's a duplicate request for creating the VETH or the VXLAN device (the device already exists but there's a request to create it).

## Steps to Reproduce

- There're no specific steps yet to reproducing the issue, but this is something that I used.
- Let it run for as long as you can (sometimes it happens in the first 20-30mins, sometimes after 4 hours)
- Happens when metrics monitoring is enabled - #1553 
- I suspect enabling the metrics monitoring is the root cause (not sure yet).

1. `make vagrant-start`
2. `FORWARDING_PLANE=kerne make k8s-deploy`
3. `while true; do make k8s-check; sleep 2; done`
4. Let it run for as long as you can (between 30 mins and 4 hours)

## Context

* Kubernetes Version:
* etc.

## Failure Logs

```
time="2019-09-09T04:27:20Z" level=error msg="kernel-forwarder: fail to receive from liveness grpc channel with error: rpc error: code = Unavailable desc = transport is closing, grpc code: Unavailable"
time="2019-09-09T04:27:21Z" level=error msg="common: failed to inject \"nsm0\" in namespace - file exists"
time="2019-09-09T04:27:21Z" level=error msg="local: failed to setup interface - source - \"nsm0\": file exists"
time="2019-09-09T04:27:21Z" level=error msg="local: failed to create connection - file exists"
time="2019-09-09T04:27:21Z" level=error msg="common: failed to inject \"nsmrSrXkA6wS\" in namespace - file exists"
time="2019-09-09T04:27:21Z" level=error msg="remote: failed to setup interface - destination - \"nsmrSrXkA6wS\": file exists"
time="2019-09-09T04:27:21Z" level=error msg="remote: failed to create connection - file exists"
time="2019-09-09T04:27:21Z" level=error msg="local: failed to create VETH pair - file exists"
time="2019-09-09T04:27:21Z" level=error msg="local: failed to create connection - file exists"
time="2019-09-09T04:27:22Z" level=error msg="remote: failed to create VXLAN interface - file exists"
```

**Comment by haiodo** [comment]
@rdimitrov any update for this?

**Comment by rdimitrov** [comment]
@haiodo I'm not able to reproduce it, so I'm okay closing it 👍
