### ISSUE TITLE
NSMD-k8s and plugins should not crash.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1590]
## Expected Behavior

NSMD-k8s and plugins should not crash.

## Current Behavior

I have a crash of nsmd-k8s, after running nsmgr for  along period (~1h)
after crashing and restarting, nsmd-k8s tells: level=fatal msg="Failed to start K8s Plugin rpc error: code = Unknown desc = already have a plugin with the same name"

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by matrohon** [comment]
here is the failure reported by nsmd-k8s: 

```
panic: close of closed channel

goroutine 113 [running]:
github.com/networkservicemesh/networkservicemesh/k8s/pkg/prefixcollector.watchSubnet.func1(0xc0003f71a0, 0x15ac5a0, 0xc000077b80, 0xc0002645a0, 0xc000189390, 0xc000189380, 0xc0004b6b70, 0xc00000c7c8)
	/root/networkservicemesh/k8s/pkg/prefixcollector/collector_server.go:181 +0x64a
created by github.com/networkservicemesh/networkservicemesh/k8s/pkg/prefixcollector.watchSubnet
	/root/networkservicemesh/k8s/pkg/prefixcollector/collector_server.go:173 +0xf6
```

it then automatically restarts by fails with the following error:

```
time="2019-09-10T13:09:58Z" level=info msg="Receive resource: name kube-master, subnet 10.42.0.0/24"
2019/09/10 13:09:58 Reporting span 683338a03285cfb2:683338a03285cfb2:0:1
time="2019-09-10T13:09:58Z" level=fatal msg="Failed to start K8s Plugin rpc error: code = Unknown desc = already have a plugin with the same name"
```

**Comment by matrohon** [comment]
To me, there are two issues:
- the panic
- the incapacity of registering a plugin that has failed and restarted

**Comment by matrohon** [comment]
I rebased and let nsmgr run several hours, and this kind of panic is happening:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503056]

goroutine 90 [running]:
net.networkNumberAndMask(0x0, 0xc000248e08, 0xc000248eb8, 0xc000023f50, 0xc0000bde88, 0x1, 0x1)
	/usr/local/go/src/net/ip.go:477 +0x26
net.(*IPNet).String(0x0, 0xc000023ef8, 0x2)
	/usr/local/go/src/net/ip.go:527 +0x40
github.com/networkservicemesh/networkservicemesh/k8s/pkg/prefixcollector.monitorReservedSubnets(0xc000562840, 0xc0004d8480, 0xc000108000, 0x20e9678, 0x0, 0x0)
	/root/networkservicemesh/k8s/pkg/prefixcollector/collector.go:116 +0x268
created by github.com/networkservicemesh/networkservicemesh/k8s/pkg/prefixcollector.monitorSubnets.func1
	/root/networkservicemesh/k8s/pkg/prefixcollector/collector.go:88 +0xd3
```

but nsmd-k8s is restarting properly.

**Comment by alex-yust** [comment]
@matrohon, thank you for the new report, we made a fix for the crash, please give it a try when you have time.

> I rebased and let nsmgr run several hours, and this kind of panic is happening:
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503056]
> 
> goroutine 90 [running]:
> net.networkNumberAndMask(0x0, 0xc000248e08, 0xc000248eb8, 0xc000023f50, 0xc0000bde88, 0x1, 0x1)
