### ISSUE TITLE
Interdomain test fails

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1603]
## Failure Information (for bugs)
https://circleci.com/gh/networkservicemesh/networkservicemesh/98178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/106803

**Comment by artem-belov** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/108973
