### ISSUE TITLE
Fuzzing: panic in parseGatewayIP

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1615]
## Current Behavior

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common.parseGatewayIP(0xfb8210, 0x1, 0x1, 0x1, 0xfb8210)
	/home/user/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/egress_interface.go:96 +0x1c6
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common.FuzzParseGatewayIP(0x794aed72f000, 0x1, 0x1, 0x3)
	/home/user/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/egress_interface_fuzz.go:25 +0xb1
go-fuzz-dep.Main(0xc0000ddf78, 0x2, 0x2)
	/tmp/go-fuzz-build528173389/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build528173389/gopath/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/go.fuzz.main/main.go:17 +0x5d

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/tmp/go-fuzz-build528173389/goroot/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/share/go/src/os/signal/signal_unix.go:23 +0x52
created by os/signal.init.0
	/usr/share/go/src/os/signal/signal_unix.go:29 +0x41
exit status 2

## References

#1518 
[crashers.GatewayIP.zip](https://github.com/networkservicemesh/networkservicemesh/files/3612441/crashers.GatewayIP.zip)

**Comment by bookmoons** [comment]
[`parse-gateway-crash`](https://github.com/bookmoons/networkservicemesh/tree/parse-gateway-crash) adds a unit test for this case.
