### ISSUE TITLE
Example-helm-vpn failing in CI on master

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1623]
## Expected Behavior

Example-helm-vpn should always pass on CI in master

## Current Behavior

Example-helm-vpn is failing on master:

https://circleci.com/gh/networkservicemesh/networkservicemesh/100256
https://circleci.com/gh/networkservicemesh/networkservicemesh/99789

Please note: this has been reported in multiple forms before in 
#1478 
#1532 
#1562 

This issue has been going on for over a month, we need to fix it.

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/100918

**Comment by edwarnicke** [comment]
@lobkovilya More recent failuer:
https://circleci.com/gh/networkservicemesh/networkservicemesh/103331?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
