### ISSUE TITLE
nsm-monitor and nsm-coredns images missing in vagrant deployment

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#1645]
## Current Behavior

Following the quick-start guide, and applying the vpn scenario, with "make k8s-vpn-deploy", the nsc can't be started because nsm-monitor:latest and nsm-coredns:latest are not present. The makefiles don't seem uptodate.

**Comment by rdimitrov** [comment]
Indeed, the following issues are also related https://github.com/networkservicemesh/networkservicemesh/issues/1591, https://github.com/networkservicemesh/networkservicemesh/issues/1551 and it should be fixed by merging https://github.com/networkservicemesh/networkservicemesh/pull/1560

**Comment by haiodo** [comment]
Work is finished with #1560
