### ISSUE TITLE
NSM Enhancement Proposal: Support CNCF CNF project

### ISSUE THREAD

**Issue by lixuna** [networkservicemesh/networkservicemesh#165]
Task: Write up/KEP of how NSM could help support CNCF CNF project
---
Including:
- [x]  Overview of CNF project => see https://github.com/ligato/networkservicemesh/issues/165#issuecomment-406629824

- [x] Where does K8s not provide required features (for Kubecon test cases)? => see https://github.com/ligato/networkservicemesh/issues/165#issuecomment-406632160

- [ ] Where is the integration of NSM with CNF?

  - [ ] CNCF CNF project folks will provide NSM team with access to example tests cases and use case information
  - [ ] NSM folks will provide steps and Q/A use NSM to provide needed functionality
  - [ ] CNCF CNF team with integrate NSM following given instructions into provisioning code and test

---

To inform: 
- [ ]  New NSM features that would need planned to support CNF project

**Comment by taylor** [comment]
**Goals:**
- Performance comparison of virtualized (VNF) and containerized network functions (CNF)
- Real world use case of container network functions


**VNF/CNF comparison metrics:**
- Performance: Packets per second
  - Including packet per second numbers at different densities.
  - Considerations for performance
     - VNFs operate on CPUs this has a direct correlation to the clock frequency, which also means that this will need to be considered when looking at the output
     - When testing NFs, the performance depends on the use case of the NF
     - Stateless vs stateful traffic
- Density: CPU, memory, etc
   - CPU - how many cores are needed for VM vs Containers
- Efficiency

**Real world use case: vCPE Residential Broadband vCPE**

**Comment by taylor** [comment]
**What do we need in Kubernetes to implement the  vCPE use case?**

Some items needed for the implementation include:

- Multiple network interface support
- Multiple types of network interfaces: vhost-user, sr-iov
- Transporting L2 frames across the pod
- Fine grained control over resource utilization with-in a node

**Comment by taylor** [comment]
Hardware requirements seen with current VPP/DPDK code base:

- Intel CPU
- SR-IOV, PCI Passthrough support

**Comment by lixuna** [comment]
Next steps:
---

- [ ]  CNCF CNF project folks will provide NSM team with access to example tests cases and use case information
- [ ] NSM folks will provide steps and Q/A use NSM to provide needed functionality
- [ ] CNCF CNF team with integrate NSM following given instructions into provisioning code and test

**Comment by taylor** [comment]
### New NSM features needed to support CNF project for Kubecon Seattle

- memif connecting one container to another container
- memif devices available in container
- Connecting container to VPP on host and to another container over memif

**Comment by taylor** [comment]
NSM project to support Kubecon demos: https://github.com/ligato/networkservicemesh/projects/2
