### ISSUE TITLE
Inconsistent behavior when multiple DNS servers provided to fanout

### ISSUE THREAD

**Issue by john-a-joyce** [networkservicemesh/networkservicemesh#1659]
## Expected Behavior

Expecting the coredns/fanout can deliver a consistent DNS response when multiple servers are configured.  

## Current Behavior

Querying for the same host will yield inconsistent results.  Sometimes they return a successful response.   Sometimes a failure and sometimes it seems partially successful.   

## Steps to Reproduce

1. Create services in two separate DNS repositories.  In my case 1 was the local kube-dns and the other was kube-dns in a KIND cluster. 
2.  Configure the fanout with multiple DNS servers.   In my case it was configured like this:
''`kubectl logs helloworld-v1-99cc49865-k9qfx -c nsm-coredns
Starting nsm-coredns
Version: 75502fff
. {
        log
        fanout 10.96.0.10 10.87.49.210:30853
}
'''
3.  Kubectl exec into an pod with the nsm-coredns container active
4.  Use nslookup to check for entries.  "busybox" is in kube-dns "busyboy" is in KIND.

Some Results:
  
root@helloworld-v1-99cc49865-k9qfx:/# nslookup busyboy  
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find busyboy: NXDOMAIN

root@helloworld-v1-99cc49865-k9qfx:/# nslookup busyboy
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   busyboy.default.svc.cluster.local
Address: 10.97.146.183

root@helloworld-v1-99cc49865-k9qfx:/# nslookup busybox
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find busybox: NXDOMAIN

root@helloworld-v1-99cc49865-k9qfx:/# nslookup busybox
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   busybox.default.svc.cluster.local
Address: 10.105.73.86

## Context

As noted the most important thing is have two independent DNS servers configured and provide to the nsm-coredns container.   
  
Kubernetes Version:  1.13
NSM version is from master but has some vl3 related changes that have not been committed.  

## Failure Logs

I can provide more complete logs from the nsm-coredns container if that is useful.

**Comment by denis-tingajkin** [comment]
@john-a-joyce, thanks for the report. Interesting why sometimes you have a negative result... 

Some thoughts about negative result reason: 
1) Try to use the final version. I found from your logs, that you used not final `nsm-coredns` version (75502ff). I guess the current behavior can differ because after 75502ff I did some fixes in nsm-coredns.
2) Try to configure your pod. I see you use custom DNS config for pod with `nsm-coredns`. If it is correct please try to use DNSConfig with DNSPolicy = None and make sure that your pod has only one search server on localhost.

@john-a-joyce, if you have a chance, please retest with the last version of nsm-coredns and configure your pod with specific DNSConfig. Also, attach logs from nsm-coredns after reproducing the issue.

**Comment by john-a-joyce** [comment]
I used the latest version from Master and here are some updated logs.   I don't know why the version string didn't print.   Is there a cli command within container to get it.   Here is the image details:

kubectl describe pod helloworld-v1-5bc5c999d6-k2pp9 | grep coredns
  nsm-coredns:
    Image:         networkservicemesh/nsm-coredns:master
    Image ID:      docker-pullable://networkservicemesh/nsm-coredns@sha256:597f32023bcd5529fe80a73464c2a856aab96fc6a434b028589a102e58752ca4

--------------  nslookup output ------------------------------
kubectl exec -it helloworld-v1-5bc5c999d6-k2pp9 -c kiali bash
root@helloworld-v1-5bc5c999d6-k2pp9:/# nslookup busybox
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   busybox.default.svc.cluster.local
Address: 10.105.73.86

root@helloworld-v1-5bc5c999d6-k2pp9:/# nslookup busybox
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find busybox: NXDOMAIN

root@helloworld-v1-5bc5c999d6-k2pp9:/# nslookup busyboy
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find busyboy: NXDOMAIN

root@helloworld-v1-5bc5c999d6-k2pp9:/# nslookup busyboy
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   busyboy.default.svc.cluster.local
Address: 10.97.146.183

root@helloworld-v1-5bc5c999d6-k2pp9:/# exit
exit

------------------------   log output ------------------------------------

root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl logs helloworld-v1-5bc5c999d6-k2pp9 -c nsm-coredns
Starting nsm-coredns
Version: 
. {
        log
        fanout 10.96.0.10 10.87.49.210:30853
}

Starting dns context update server...
Update server started
.:53
2019-09-24T14:01:30.174Z [INFO] CoreDNS-1.5.2
2019-09-24T14:01:30.175Z [INFO] linux/amd64, go1.13, 
CoreDNS-1.5.2
linux/amd64, go1.13, 
2019-09-24T14:07:10.381Z [INFO] 127.0.0.1:46648 - 44587 "A IN busybox.default.svc.cluster.local. udp 51 false 512" NOERROR qr,aa,rd,ra 100 0.001781226s
2019-09-24T14:07:10.383Z [INFO] 127.0.0.1:45758 - 15610 "AAAA IN busybox.default.svc.cluster.local. udp 51 false 512" NOERROR qr,aa,rd,ra 144 0.000650493s
2019-09-24T14:07:16.034Z [INFO] 127.0.0.1:55513 - 64781 "A IN busybox.default.svc.cluster.local. udp 51 false 512" NXDOMAIN qr,rd 144 0.000921652s
2019-09-24T14:07:16.035Z [INFO] 127.0.0.1:37159 - 55654 "A IN busybox.svc.cluster.local. udp 43 false 512" NXDOMAIN qr,aa,rd 136 0.000611823s
2019-09-24T14:07:16.036Z [INFO] 127.0.0.1:51795 - 36519 "A IN busybox.cluster.local. udp 39 false 512" NXDOMAIN qr,aa,rd 132 0.000524002s
2019-09-24T14:07:16.238Z [INFO] 127.0.0.1:54592 - 23050 "A IN busybox. udp 25 false 512" NXDOMAIN qr,rd,ra 100 0.201245023s
2019-09-24T14:07:36.971Z [INFO] 127.0.0.1:56797 - 65409 "A IN busyboy.default.svc.cluster.local. udp 51 false 512" NXDOMAIN qr,aa,rd,ra 144 0.00143675s
2019-09-24T14:07:36.972Z [INFO] 127.0.0.1:47365 - 25461 "A IN busyboy.svc.cluster.local. udp 43 false 512" NXDOMAIN qr,aa,rd,ra 136 0.000498089s
2019-09-24T14:07:36.973Z [INFO] 127.0.0.1:39652 - 19192 "A IN busyboy.cluster.local. udp 39 false 512" NXDOMAIN qr,aa,rd 132 0.000618977s
2019-09-24T14:07:37.017Z [INFO] 127.0.0.1:45123 - 33684 "A IN busyboy. udp 25 false 512" NXDOMAIN qr,rd,ra 100 0.043816282s
2019-09-24T14:07:42.923Z [INFO] 127.0.0.1:35579 - 62243 "A IN busyboy.default.svc.cluster.local. udp 51 false 512" NOERROR qr,rd 100 0.001213998s
2019-09-24T14:07:42.924Z [INFO] 127.0.0.1:45771 - 23464 "AAAA IN busyboy.default.svc.cluster.local. udp 51 false 512" NOERROR qr,aa,rd 144 0.000570605s

------------------   resolv.conf output from container  ------------
kubectl exec -it helloworld-v1-5bc5c999d6-k2pp9 -c kiali bash
root@helloworld-v1-5bc5c999d6-k2pp9:/# cat /etc/resolv.conf
nameserver 127.0.0.1
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

**Comment by john-a-joyce** [comment]
dnsConfig output from pod. 

  dnsConfig:
    nameservers:
    - 127.0.0.1
    options:
    - name: ndots
      value: "5"
    searches:
    - default.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None

**Comment by john-a-joyce** [comment]
After testing by cherry-picking the original issue seems fixed but I see a slightly different issue.  If I provide the wrong port number in the fanout for the dns server requests that should be successfully are not even if the other server can resolve.   Here are some logs.  You will see below I edited the deployment and switched the ports to the 2nd server (it was to the UDP ports of that server).   The helloworld request I would expect to begin failing,   but the google.com request can be resolve by either server. 

root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl exec -it helloworld-v1-5695f9cb97-6lpmj -c kiali bash
root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup google.com                    
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.7.206
Name:   google.com
Address: 2607:f8b0:4005:80b::200e

root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup helloworld.default.svc.cluster.local
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   helloworld.default.svc.cluster.local
Address: 10.105.254.2

root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup helloworld                                                 
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   helloworld.default.svc.cluster.local
Address: 10.105.254.2

root@helloworld-v1-5695f9cb97-6lpmj:/# 
root@helloworld-v1-5695f9cb97-6lpmj:/# exit
exit

----- Editing deployment here to provide the UDP port ---- 
root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl edit deployment helloworld-v1
deployment.extensions/helloworld-v1 edited
root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl exec -it helloworld-v1-69c5f9598c-l7wjg -c kiali bash
root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup helloworld.default.svc.cluster.local
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find helloworld.default.svc.cluster.local: NXDOMAIN

root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup helloworld
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find helloworld.default.svc.cluster.local: SERVFAIL

root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup google.com
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find google.com: SERVFAIL

root@helloworld-v1-69c5f9598c-l7wjg:/# exit
exit
command terminated with exit code 1
root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl logs helloworld-v1-69c5f9598c-l7wjg -c nsm-coredns
Starting nsm-coredns
Version: f7c6954
. {
        log
        fanout 10.96.0.10 10.87.49.210:30653
}

Starting dns context update server...
time="2019-10-02T22:48:47Z" level=info msg="GRPC.NewServer with open tracing enabled"
Update server started
.:53
2019-10-02T22:48:47.766Z [INFO] CoreDNS-1.5.2
2019-10-02T22:48:47.766Z [INFO] linux/amd64, go1.13.1, 
CoreDNS-1.5.2
linux/amd64, go1.13.1, 
2019-10-02T22:49:42.963Z [INFO] 127.0.0.1:46866 - 50690 "A IN helloworld.default.svc.cluster.local.default.svc.cluster.local. udp 80 false 512" NXDOMAIN qr,aa,rd,ra 173 0.001998718s
2019-10-02T22:49:42.965Z [INFO] 127.0.0.1:58832 - 41612 "A IN helloworld.default.svc.cluster.local.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd,ra 165 0.000870982s
2019-10-02T22:49:42.966Z [INFO] 127.0.0.1:59912 - 26351 "A IN helloworld.default.svc.cluster.local.cluster.local. udp 68 false 512" NXDOMAIN qr,aa,rd,ra 161 0.000952574s
2019-10-02T22:49:42.967Z [INFO] 127.0.0.1:54433 - 52439 "A IN helloworld.default.svc.cluster.local. udp 54 false 512" NXDOMAIN qr,aa,rd,ra 147 0.000881845s
2019-10-02T22:50:15.568Z [INFO] 127.0.0.1:57016 - 5126 "A IN helloworld.default.svc.cluster.local. udp 54 false 512" NOERROR - 0 0.001534065s
2019-10-02T22:51:00.505Z [INFO] 127.0.0.1:36426 - 43132 "A IN google.com.default.svc.cluster.local. udp 54 false 512" NXDOMAIN qr,aa,rd,ra 147 0.001736814s
2019-10-02T22:51:00.506Z [INFO] 127.0.0.1:35158 - 11334 "A IN google.com.svc.cluster.local. udp 46 false 512" NXDOMAIN qr,aa,rd,ra 139 0.001125281s
2019-10-02T22:51:00.508Z [INFO] 127.0.0.1:46152 - 22939 "A IN google.com.cluster.local. udp 42 false 512" NXDOMAIN qr,aa,rd,ra 135 0.001026348s
2019-10-02T22:51:08.512Z [INFO] 127.0.0.1:36742 - 45097 "A IN google.com. udp 28 false 512" NOERROR - 0 8.004035913s
2019-10-02T22:51:13.513Z [INFO] 127.0.0.1:36742 - 45097 "A IN google.com. udp 28 false 512" NOERROR - 0 8.004689638s

**Comment by denis-tingajkin** [comment]
> After testing by cherry-picking the original issue seems fixed but I see a slightly different issue. If I provide the wrong port number in the fanout for the dns server requests that should be successfully are not even if the other server can resolve. Here are some logs. You will see below I edited the deployment and switched the ports to the 2nd server (it was to the UDP ports of that server). The helloworld request I would expect to begin failing, but the google.com request can be resolve by either server.
> 
> root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl exec -it helloworld-v1-5695f9cb97-6lpmj -c kiali bash
> root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup google.com
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> Non-authoritative answer:
> Name: google.com
> Address: 172.217.7.206
> Name: google.com
> Address: 2607:f8b0:4005:80b::200e
> 
> root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup helloworld.default.svc.cluster.local
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> Name: helloworld.default.svc.cluster.local
> Address: 10.105.254.2
> 
> root@helloworld-v1-5695f9cb97-6lpmj:/# nslookup helloworld
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> Non-authoritative answer:
> Name: helloworld.default.svc.cluster.local
> Address: 10.105.254.2
> 
> root@helloworld-v1-5695f9cb97-6lpmj:/#
> root@helloworld-v1-5695f9cb97-6lpmj:/# exit
> exit
> 
> ----- Editing deployment here to provide the UDP port ----
> root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl edit deployment helloworld-v1 deployment.extensions/helloworld-v1 edited root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl exec -it helloworld-v1-69c5f9598c-l7wjg -c kiali bash
> root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup helloworld.default.svc.cluster.local
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> ** server can't find helloworld.default.svc.cluster.local: NXDOMAIN
> 
> root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup helloworld
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> ** server can't find helloworld.default.svc.cluster.local: SERVFAIL
> 
> root@helloworld-v1-69c5f9598c-l7wjg:/# nslookup google.com
> Server: 127.0.0.1
> Address: 127.0.0.1#53
> 
> ** server can't find google.com: SERVFAIL
> 
> root@helloworld-v1-69c5f9598c-l7wjg:/# exit
> exit
> command terminated with exit code 1
> root@bxb-ds-82:~/go/src/github.com/networkservicemesh/examples# kubectl logs helloworld-v1-69c5f9598c-l7wjg -c nsm-coredns
> Starting nsm-coredns
> Version: f7c6954
> . {
> log
> fanout 10.96.0.10 10.87.49.210:30653
> }
> 
> Starting dns context update server...
> time="2019-10-02T22:48:47Z" level=info msg="GRPC.NewServer with open tracing enabled"
> Update server started
> .:53
> 2019-10-02T22:48:47.766Z [INFO] CoreDNS-1.5.2
> 2019-10-02T22:48:47.766Z [INFO] linux/amd64, go1.13.1,
> CoreDNS-1.5.2
> linux/amd64, go1.13.1,
> 2019-10-02T22:49:42.963Z [INFO] 127.0.0.1:46866 - 50690 "A IN helloworld.default.svc.cluster.local.default.svc.cluster.local. udp 80 false 512" NXDOMAIN qr,aa,rd,ra 173 0.001998718s
> 2019-10-02T22:49:42.965Z [INFO] 127.0.0.1:58832 - 41612 "A IN helloworld.default.svc.cluster.local.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd,ra 165 0.000870982s
> 2019-10-02T22:49:42.966Z [INFO] 127.0.0.1:59912 - 26351 "A IN helloworld.default.svc.cluster.local.cluster.local. udp 68 false 512" NXDOMAIN qr,aa,rd,ra 161 0.000952574s
> 2019-10-02T22:49:42.967Z [INFO] 127.0.0.1:54433 - 52439 "A IN helloworld.default.svc.cluster.local. udp 54 false 512" NXDOMAIN qr,aa,rd,ra 147 0.000881845s
> 2019-10-02T22:50:15.568Z [INFO] 127.0.0.1:57016 - 5126 "A IN helloworld.default.svc.cluster.local. udp 54 false 512" NOERROR - 0 0.001534065s
> 2019-10-02T22:51:00.505Z [INFO] 127.0.0.1:36426 - 43132 "A IN google.com.default.svc.cluster.local. udp 54 false 512" NXDOMAIN qr,aa,rd,ra 147 0.001736814s
> 2019-10-02T22:51:00.506Z [INFO] 127.0.0.1:35158 - 11334 "A IN google.com.svc.cluster.local. udp 46 false 512" NXDOMAIN qr,aa,rd,ra 139 0.001125281s
> 2019-10-02T22:51:00.508Z [INFO] 127.0.0.1:46152 - 22939 "A IN google.com.cluster.local. udp 42 false 512" NXDOMAIN qr,aa,rd,ra 135 0.001026348s
> 2019-10-02T22:51:08.512Z [INFO] 127.0.0.1:36742 - 45097 "A IN google.com. udp 28 false 512" NOERROR - 0 8.004035913s
> 2019-10-02T22:51:13.513Z [INFO] 127.0.0.1:36742 - 45097 "A IN google.com. udp 28 false 512" NOERROR - 0 8.004689638s

@john-a-joyce Many thanks for testing. It seems to me as another problem. Can we create separate Issue for this problem?

**Comment by john-a-joyce** [comment]
@denis-tingajkin - I can create a different issue, but isn't that problematic since 1690 hasn't merged yet?

**Comment by denis-tingajkin** [comment]
@john-a-joyce if a problem what you describe is reproduced in the master branch then we can solve this in separate PR.
