### ISSUE TITLE
TestSimpleMetrics is failed

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/networkservicemesh#1673]
## Expected Behavior

The test is expected to pass

## Current Behavior

The test fails occasionaly
According to @denis-tingajkin this is not a duplicate of #1029 

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

## Failure Logs

https://circleci.com/gh/networkservicemesh/networkservicemesh/104734#tests/containers/0
[TestSimpleMetrics.zip](https://github.com/networkservicemesh/networkservicemesh/files/3660923/TestSimpleMetrics.zip)

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/105161?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by alex-yust** [comment]
@lobkovilya please look if this TestSimpleMetrics test failure is similar to one you experience currently

**Comment by denis-tingajkin** [comment]
@alex-yust  I have looked at logs from dataplane, yes it is the same problem
```
2019-09-27 02:42:52,840 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:52Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:53,841 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:53Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:54,842 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:54Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:55,843 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:55Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:56,845 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:56Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:57,845 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:57Z" level=info msg="Metrics collector: request 0"

2019-09-27 02:42:58,846 DEBG 'vppagent-dataplane' stdout output:
time="2019-09-27T02:42:58Z" level=info msg="Metrics collector: request 0"
```
By some reason request always has index 0.

**Comment by haiodo** [comment]
Seems fixed.

**Comment by haiodo** [comment]
Still could fail: @lobkovilya  please take a look: https://circleci.com/gh/networkservicemesh/networkservicemesh/113749?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
