### ISSUE TITLE
VPPAgent dataplane errors during testing

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1718]
## Expected Behavior

Vpp agent should not disconnect

## Current Behavior

time="2019-10-04T11:00:46Z" level=error msg="rpc error: code = FailedPrecondition desc = KeyErrors: [config/vpp/v2/interfaces/DST-d9 (CREATE): not connected to VPP, ignoring the request, config/vpp/v2/interfaces/SRC-d9 (CREATE): not connected to VPP, ignoring the request]

and so on.

## Steps to Reproduce

Run following testcase

```go
// +build bench

package nsmd_integration_tests

import (
	"fmt"
	"sync"
	"testing"

	. "github.com/onsi/gomega"
	v1 "k8s.io/api/core/v1"

	"github.com/networkservicemesh/networkservicemesh/test/kubetest"
	"github.com/networkservicemesh/networkservicemesh/test/kubetest/pods"
)

func TestHugeConnectionCount(t *testing.T) {
	g := NewWithT(t)
	nodesCount := 2

	k8s, err := kubetest.NewK8s(g, true)
	defer k8s.Cleanup()
	//defer kubetest.MakeLogsSnapshot(k8s, t)
	g.Expect(err).To(BeNil())

	config := []*pods.NSMgrPodConfig{}
	for i := 0; i < nodesCount; i++ {
		cfg := &pods.NSMgrPodConfig{
			Variables: pods.DefaultNSMD(),
		}
		cfg.Namespace = k8s.GetK8sNamespace()
		cfg.DataplaneVariables = kubetest.DefaultDataplaneVariables(k8s.GetForwardingPlane())
		config = append(config, cfg)
	}
	nodes_setup, err := kubetest.SetupNodesConfig(k8s, nodesCount, defaultTimeout, config, k8s.GetK8sNamespace())
	g.Expect(err).To(BeNil())

	// Run ICMP on latest node
	_ = kubetest.DeployICMP(k8s, nodes_setup[nodesCount-1].Node, "icmp-responder-nse-1", defaultTimeout)

	var wg sync.WaitGroup
	count := 1000
	cycle := 5
	for j := 0; j < cycle; j++ {
		wg.Add(1)
		go func(j int) {
			defer wg.Done()
			for i := 0; i < count; i++ {
				var nscPodNode *v1.Pod
				podName := fmt.Sprintf("nsc-%d-%d", j, i)
				//logrus.Infof("podName=%v", podName)
				nscPodNode = kubetest.DeployNSC(k8s, nodes_setup[i%len(nodes_setup)].Node, podName, defaultTimeout)

				kubetest.CheckNSC(k8s, nscPodNode)
				k8s.DeletePods(nscPodNode)
			}
		}(j)
	}
	wg.Wait()
}

```
## Context

* Kubernetes Version:
* etc.

**Comment by haiodo** [comment]
@artem-belov could you as VPP expect take a look. Thanks.

**Comment by haiodo** [comment]
dataplane logs:
[worker.log.zip](https://github.com/networkservicemesh/networkservicemesh/files/3691770/worker.log.zip)

jaeger tracing:
[5684484e3c2f9366.json.zip](https://github.com/networkservicemesh/networkservicemesh/files/3691771/5684484e3c2f9366.json.zip)

**Comment by denis-tingajkin** [comment]
Can we reproduce the issue using existing bench tests?
For example: 
1) Need to change https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/const.go#L12
2) Run test https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/bench_connection_test.go#L22
