### ISSUE TITLE
Cleanup CI-specific docker images from DockerHub registry

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/networkservicemesh#1728]
## Overview

Project's CI creates unique image tag for every build, which means images built during CI are never  (theoretically) de-tagged and cleaned up from DockerHub registry. Those images take pretty amount of space and create clutter in registry.

It seems right to cleanup the images by default.

Although there is no docker command to remove an image from a remote registry, it is possible
via Docker Registry HTTP API V2 https://devopsheaven.com/docker/dockerhub/2018/04/09/delete-docker-image-tag-dockerhub.html

**Comment by edwarnicke** [comment]
Good idea :)

**Comment by alex-yust** [comment]
done
