### ISSUE TITLE
Handle excludePrefixes via ConfigMap not GRPC

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1735]
## Overview

Currently we are populating ExcludePrefixes via a GRPC protocol.  Since this is a configuration matter, its better handled via a [ConfigMap](https://medium.com/@xcoulon/kubernetes-configmap-hot-reload-in-action-with-viper-d413128a1c9a).

The goal is to transition the ExcludePrefixes plugin to being a separate server that updates a ConfigMap of ExcludePrefix information.  That ConfigMap can then be consumed by nsmd as a  yaml file.  Being consumed as a file will cause it to be updated whenever the ConfigMap is updated in any consuming Pod.

So the cycle becomes:

1. ExcludePrefixServer detects Prefixes to be Excluded
2. ExcludePrefixSever updates ConfigMap
3. nsmd ConfigMap file gets updated
4. nsmd detects ConfigMap file is updated
5. nsmd loads ConfigMap file and updates its internal ExcludePrefixes

**Comment by haiodo** [comment]
@denis-tingajkin I think we should do same for DNS records if applicable :-)

**Comment by edwarnicke** [comment]
@haiodo Say more :)  I don't quite follow :)

**Comment by edwarnicke** [comment]
Suggested yaml file format:

```yaml
excludePrefixes:
  - 1.1.1.1/24
  - 2.2.2.2/30
  ...
```

You can adapt [prefixcollector](https://github.com/networkservicemesh/networkservicemesh/tree/master/k8s/pkg/prefixcollector) to gather the excludedPrefixes and update the ConfigMap.

In the process you should delete [controlplane/api/plugins](https://github.com/networkservicemesh/networkservicemesh/tree/master/controlplane/api/plugins)

I would suggest using [Viper](https://github.com/spf13/viper) to adapt [nsmd](https://github.com/networkservicemesh/networkservicemesh/tree/master/controlplane/cmd/nsmd) to read the Config file placed by the ConfigMap.

**Comment by denis-tingajkin** [comment]
@edwarnicke Am I understand correctly that for step 4(`nsmd detects ConfigMap file is updated`) we need to monitor the configmap file on nsmd side via `file watcher` ?

**Comment by denis-tingajkin** [comment]
@edwarnicke got it. `viper` provides API for monitoring config file. Looks clear to me
