### ISSUE TITLE
TestSimpleMetrics failed with vpp-agent v2.3.0

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1763]
## Expected Behavior

Test should pass on all clusters

## Current Behavior

Test failed on waiting for metrics update 

## Failure Information (for bugs)

vpp-agent version update #1753
https://circleci.com/gh/networkservicemesh/networkservicemesh/111817

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by denis-tingajkin** [comment]
Blocked by https://github.com/ligato/vpp-agent/issues/1537
