### ISSUE TITLE
Example-helm-vpn fails on CI

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1774]
## Failure Information (for bugs)
[vpn-example.zip](https://github.com/networkservicemesh/networkservicemesh/files/3740908/vpn-example.3.zip)

https://circleci.com/gh/networkservicemesh/networkservicemesh/112410?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by denis-tingajkin** [comment]
found in logs of firewall
```
time="2019-10-17 17:38:10.62745" level=error msg="Failed to switch to Linux network namespace (<nil>): operation not permitted" loc="nsplugin/ns_plugin.go(186)" logger=linux-nsplugin ns="NS(12: 3, 4026532568)" ns-fd=12 orig-ns="NS(11: 3, 4026532568)" orig-ns-fd=11
time="2019-10-17 17:38:10.62774" level=warning msg="Failed to switch namespace:operation not permitted" loc="descriptor/interface.go(807)" logger=linux-ifplugin.if-descriptor namespace="<nil>"
time="2019-10-17 17:38:10.62845" level=error msg="Failed to switch to Linux network namespace (<nil>): operation not permitted" loc="nsplugin/ns_plugin.go(186)" logger=linux-nsplugin ns="NS(12: 3, 4026532568)" ns-fd=12 orig-ns="NS(11: 3, 4026532568)" orig-ns-fd=11
```
Is it expected error?

**Comment by lobkovilya** [comment]
@denis-tingajkin I don't know, but you can check logs of successful test

**Comment by nickolaev** [comment]
Is this still a thing?

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/117053?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by alex-yust** [comment]
> Is this still a thing?

@nickolaev yes, this still might be a thing.

There is #1988 which is intended to help tracing the supposed original arp-related cause of ping issues 
We're waiting for failed test logs.

**Comment by nickolaev** [comment]
Considering it is fixed already.

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/121340

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/121610
