### ISSUE TITLE
AWS: NetworkPlugin cni failed to set up pod... network: add cmd: failed to assign an IP address to container

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1775]
## Failure Information (for bugs)

https://circleci.com/gh/networkservicemesh/networkservicemesh/112410?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by haiodo** [comment]
I think we need to check this situation in test and return some status for CloudTest tool to try on another instance of same cluster to re-test this particular test again.

**Comment by haiodo** [comment]
I will try to add a re-try attempt to re-deploy pod with name name if this situation will happen, and if this will not help when a cluster-restart/choose a different instance will potentially help I suppose.

**Comment by haiodo** [comment]
We had this happen again on master: https://circleci.com/gh/networkservicemesh/networkservicemesh/112410?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by haiodo** [comment]
Should be fixed with retest
