### ISSUE TITLE
Cross connect fails to log events with spire enabled

### ISSUE THREAD

**Issue by ivanayov** [networkservicemesh/networkservicemesh#1780]
Cross connect monitor logs have the following error and there are no printed events after `k8s-check`:

```
FetchX509SVID failed with rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/spire/sockets/agent.sock: connect: no such file or directory\"; retrying in 1s
```

When `spire` is disabled, `nsm` deployment fails with time out:
```
Error: release nsm failed: timed out waiting for the condition
make: *** [helm-install-nsm] Error 1
```

**Comment by edwarnicke** [comment]
@lobkovilya Could you have a look?

**Comment by ivanayov** [comment]
@lobkovilya @edwarnicke I think this is resolved now on latest master + there's an update in the documentation about disabling spire.
Didn't test with spire enabled though.

**Comment by lobkovilya** [comment]
I'll check what's wrong with `cross-connect monitor` with enabled `spire`.

**Comment by haiodo** [comment]
@ivanayov Could you please check.
