### ISSUE TITLE
Error when running make docker-build

### ISSUE THREAD

**Issue by manuelbuil** [networkservicemesh/networkservicemesh#1840]
## Expected Behavior

As stated in the [README](https://github.com/networkservicemesh/networkservicemesh/blob/2923db39e12d8da1d11629a18a9d6f566e216130/scripts/vagrant/README.md), I would expect images to be built by executing `make docker-build`

## Current Behavior

It fails with errors because it cannot find the package github.com/spiffe/spire/proto/spire/api/workload

## Failure Information (for bugs)

The error is: 

> ../../github.com/networkservicemesh/networkservicemesh/pkg/security/spire.go:27:2: cannot find package "github.com/spiffe/spire/proto/spire/api/workload"

When trying to access that github project, I get a 404. The following url exists https://github.com/spiffe/spire/tree/master/proto/spire/api but there is no workload directory.

## Steps to Reproduce

This is what I do:

1. `make docker-build`

## Context

GitCommit: "d9b330b7f32fed19fbfd90725816ffa394d19ee2"
go version go1.10.4 linux/amd64

**Comment by edwarnicke** [comment]
@manuelbuil Could you try with go 1.13 ?

**Comment by manuelbuil** [comment]
@edwarnicke yep, that fixes problem :). Should I add that information in https://github.com/networkservicemesh/networkservicemesh/tree/master/scripts/vagrant#prerequisites? BTW, in that same document, after executing `make docker-save`, it executes `cd forwarders/vpp` but that directory does not exist or?

**Comment by edwarnicke** [comment]
@manuelbuil Please do :)  We'd welcome a PR to improve documentation :)

You should be able to also delete the whole
```
cd forwarders/vpp
make docker-build
make docker-save
``` 
and have things still work :)

**Comment by manuelbuil** [comment]
https://github.com/networkservicemesh/networkservicemesh/pull/1843
