### ISSUE TITLE
etcdserver: request timed out on pod deploying [Azure]

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1848]
## Logs
https://114245-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/azure-1/016-TestDeleteDirtyNSEWithClient-run.log

## Build
https://circleci.com/gh/networkservicemesh/networkservicemesh/114245

**Comment by artem-belov** [comment]
I suppose this issues related only to Azure cloud.

**Comment by denis-tingajkin** [comment]
@artem-belov fixed

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/114386

**Comment by haiodo** [comment]
I think we need to restart cloud in this case. Question here is could we detect this situation not from test.

**Comment by haiodo** [comment]
Should be fixed with retest
