### ISSUE TITLE
TestInterdomainVPNNSERemote sometimes fails on CI

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1849]
## Failure Logs
https://114296-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/aws-6_azure-4/001-TestInterdomainVPNNSERemote-run.log

## Build

https://circleci.com/gh/networkservicemesh/networkservicemesh/114296?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by haiodo** [comment]
Should be fixed with retest
