### ISSUE TITLE
Packet cluster fails on CI

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1851]
## Expected Behavior

Packet cluster choose another facility if default is busy

## Current Behavior

Packet cluster starts with error 
> The facility sjc1 has no provisionable t1.small.x86 servers matching your criteria 

## Failure Information (for bugs)

https://circleci.com/gh/networkservicemesh/networkservicemesh/114351

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by haiodo** [comment]
Closing as fixed on CloudTest
