### ISSUE TITLE
Enhance Meshery adapter for NSM with full collection of CNF example apps

### ISSUE THREAD

**Issue by leecalcote** [networkservicemesh/networkservicemesh#1869]
## Overview

Meshery is a multi-service mesh management plane that, among other things, provides lifecycle management of a variety of service meshes, including NSM.

Currently, the [Meshery adapter for NSM](https://github.com/layer5io/meshery-nsm) includes four of the NSM CNF as published in [helm charts](https://github.com/networkservicemesh/helm-charts) and one sample application created in the Meshery project.

In order to highlight the full set of NSM capabilities (via example CNFs), ideally, all NSM example apps will be included in the Meshery adapter for NSM. 

**Desired Behavior:**
The approach to doing so (listed below) is dynamic in that anytime a new example app is added in the [networkservicemesh/examples](https://github.com/networkservicemesh/examples) repo (using the same folder structure), it will show up in Meshery's UI for users to choose from the CNF "catalog", so to speak.

Deprovisioning of example apps (CNFs) should require no update in the adapter (the adapter should be able to deprovision all apps as-is).

**Desired Implementation:**
Incorporate the following logic within `nsm.go` and `nsm-cnfs.go`:

- [ ] create `nsm-cnfs.go` (a new file).
  - [ ] clone the networkservicemesh/examples repo.
  - [ ] iterate through the list of example app folders.
  - [ ] append the adapter's [SupportOperations array](https://github.com/layer5io/meshery-nsm/blob/master/nsm/nsm.go#L592) of supported apps.

- [ ] within `nsm.go`,
  - [ ] update logic in [applyOperation](https://github.com/layer5io/meshery-nsm/blob/master/nsm/nsm.go#L317) to include for provisioning of CNFs via [applyConfigChange](https://github.com/layer5io/meshery-nsm/blob/master/nsm/nsm.go#L42)

// @girishranganathan

**Comment by edwarnicke** [comment]
@leecalcote Would it help to have helm charts for the examples/ ?  We have them currently for the ones in the networkservicemesh repo at https://helm.nsm.dev/master 
Then we could simply take your approach with walking the helm charts rather than checking out the repo :)

**Comment by leecalcote** [comment]
@edwarnicke great suggestion. 😀 Yes, helm charts really would improve the approach.

**Comment by leecalcote** [comment]
@Harshini-M and @ivanayov, would one of you like to investigate this enhancement?

**Comment by ivanayov** [comment]
Hi @leecalcote,
I reviewed your proposal and can take that as one of the next priorities.

**Comment by girishranganathan** [comment]
@ivanayov, thx a lot for volunteering here. 
Please feel free to reach out to me or @Harshini-M for any help/clarifications in moving this forward.

**Comment by girishranganathan** [comment]
@ivanayov you should have the necessary access to work on the code in this repo.
Also, please feel free to join our slack here: http://slack.layer5.io/.
If you are interested, I am available for a chat mid day during the week. Feel free to ping me on slack or GitHub and we can set up a time to catch up.

**Comment by leecalcote** [comment]
@ivanayov yes, please! 👍 There's a weekly community call on Fridays at 8am Pacific where we can chat (or another time). Please do make some noise in the Slack channel. Let's get you the support you need.

**Comment by ivanayov** [comment]
Thanks @leecalcote @girishranganathan ! I'll ping you on slack
