### ISSUE TITLE
Double close() requests with vpp backplane

### ISSUE THREAD

**Issue by johan-lj** [networkservicemesh/networkservicemesh#1876]
## Expected Behavior

Single close request for each removed alpine-nsc client

## Current Behavior

Double close requests for each removed alpine-nsc client

## Failure Information (for bugs)

If the NSCs are scaled in double close requests are registered where the first succeeds and the second fails (since the close() is already finished)

## Steps to Reproduce

helm install nsm (with vpp backplane)
helm install icmp-responder
kubectl scale deployment alpine-nsc --replicas=1 -n default
kubectl logs icmp-responder-nse-<hash> | grep -i -C 5 "connection prefixes network"

## Context

* Kubernetes Version:
* etc.

## Failure Logs
[log.txt](https://github.com/networkservicemesh/networkservicemesh/files/3846370/log.txt)

**Comment by denis-tingajkin** [comment]
@johan-lj  Hello,
I tried to reproduce the problem. My steps are:
```
1. make helm-install-nsm
2. make helm-install-icmp-responder
3. kubectl scale deployment alpine-nsc --replicas=1 -n nsm-system
```
Run for each NSE
```
4. kubectl logs icmp-responder-nse- | grep -i -C 5 "connection prefixes network"
```
Actual: No errors.

My questions are:
1) Did I reproduce the problem correctly?
2) Can you attach full logs. (You need simply reproduce the problem on your side and run 
`STORE_POD_LOGS_IN_FILES=true sh scripts/logs_snapshot.sh`

**Comment by johan-lj** [comment]
The procedure looks fine to me. I'll reproduce with full logs, maybe it has been fixed recently.
Could you try it with only a single NSE/icmp-responder?

**Comment by johan-lj** [comment]
Reproduced with the latest master today, confirmed it's not there anymore :)
Will close the ticket

Br,
Johan
