### ISSUE TITLE
Extra request() call for icmp-responder + kernel backplane

### ISSUE THREAD

**Issue by johan-lj** [networkservicemesh/networkservicemesh#1878]
## Expected Behavior

No extra request, NSC IPs start att .1

## Current Behavior

An extra request() is issued and the first IPAM assigned address is stepped to .5

## Failure Information (for bugs)

There are 3 NSC pods
the following interfaces are added in the icmp-responder
nsm1LnbggDiv Link encap:Ethernet  HWaddr 7A:1F:B0:7B:A6:80  
          inet addr:172.16.1.14  Bcast:172.16.1.15  Mask:255.255.255.252
nsmXmRr66Giv Link encap:Ethernet  HWaddr 52:B1:2D:C4:D4:8D  
          inet addr:172.16.1.10  Bcast:172.16.1.11  Mask:255.255.255.252
nsmwvRr6gGiv Link encap:Ethernet  HWaddr 36:0A:C5:E5:B9:76  
          inet addr:172.16.1.6  Bcast:172.16.1.7  Mask:255.255.255.252

Seems there was a 4th interface briefly as well?
Ie. request={\"connection\":{\"id\":\"1\",\"network_service\":\"icmp-responder\",\"mechanism\":{\"type\":1,\"parameters\":{\"dst_ip\":\"192.168.1.2\",\"src_ip\":\"192.16
8.1.4\",\"vni\":\"3\"}},\"context\":{\"ip_context\":{\"src_ip_addr\":\"172.16.1.1/30\",\"dst_ip_addr\":\"172.16.1.2/30\",\"src_ip_required\":true,

## Steps to Reproduce

Deploy the icmp-responder (kernel backplane)
Check the logs

## Context

* Kubernetes Version:
* etc.

## Failure Logs

Attached
[icmp-responder.txt](https://github.com/networkservicemesh/networkservicemesh/files/3846689/icmp-responder.txt)
[kernel-forwarder.txt](https://github.com/networkservicemesh/networkservicemesh/files/3846690/kernel-forwarder.txt)
[nsmd.txt](https://github.com/networkservicemesh/networkservicemesh/files/3846691/nsmd.txt)

**Comment by edwarnicke** [comment]
@rdimitrov I think this one is for you :)

**Comment by rdimitrov** [comment]
@edwarnicke Thanks 👍 
@johan-lj Hm, I agree there's an additional request sent to the forwarding plane.

What happened is that there were two Request()'s being done - one with `id=1` and one with `id=2`. Both of them are for creating a remote connection but unfortunately configured to use the same VNI index(vni=3). 
So, naturally one of them was successful and the other one failed because the desired VXLAN index was already used.

As far as I understand you had at least 3 nodes - 
- `vm-002` hosted the endpoint
- `vm-003` and `vm-004` hosted the two clients that initiated the overlapping requests

More precisely, that's the request with id=1 - 
```
time="2019-11-14T12:52:56Z" level=info msg="Request() called with id:\"1\" payload:\"IP\" remote_source:<id:\"1\" network_service:\"icmp-responder\" mechanism:<type:VXLAN parameters:<key:\"dst_ip\" value:\"192.168.1.2\" > parameters:<key:\"src_ip\" value:\"192.168.1.4\" > parameters:<key:\"vni\" value:\"3\" > > context:<ip_context:<src_ip_addr:\"172.16.1.1/30\" dst_ip_addr:\"172.16.1.2/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"192.168.2.0/24\" > excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" > > labels:<key:\"app\" value:\"icmp\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"alpine-nsc-86b66765bc-dx9mk\" > source_network_service_manager_name:\"vm-004\" destination_network_service_manager_name:\"vm-002\" network_service_endpoint_name:\"icmp-responder2zmfn\" > local_destination:<id:\"3\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmOvhrg6Gjt\" > parameters:<key:\"netnsInode\" value:\"4026532244\" > parameters:<key:\"socketfile\" value:\"nsmOvhrg6Gjt/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-4\" > parameters:<key:\"workspaceNseName\" value:\"icmp-responder2zmfn\" > > context:<ip_context:<src_ip_addr:\"172.16.1.1/30\" dst_ip_addr:\"172.16.1.2/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"192.168.2.0/24\" > excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" > > labels:<key:\"app\" value:\"icmp\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"icmp-responder-nse-58848df66c-7s84g\" > > "
```
and that's the one with id=2 - 
```
time="2019-11-14T12:52:56Z" level=info msg="Request() called with id:\"2\" payload:\"IP\" remote_source:<id:\"2\" network_service:\"icmp-responder\" mechanism:<type:VXLAN parameters:<key:\"dst_ip\" value:\"192.168.1.2\" > parameters:<key:\"src_ip\" value:\"192.168.1.3\" > parameters:<key:\"vni\" value:\"3\" > > context:<ip_context:<src_ip_addr:\"172.16.1.5/30\" dst_ip_addr:\"172.16.1.6/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"192.168.2.0/24\" > excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" > > labels:<key:\"app\" value:\"icmp\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"alpine-nsc-86b66765bc-fgfsf\" > source_network_service_manager_name:\"vm-003\" destination_network_service_manager_name:\"vm-002\" network_service_endpoint_name:\"icmp-responder2zmfn\" > local_destination:<id:\"4\" network_service:\"icmp-responder\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmwvRr6gGiv\" > parameters:<key:\"netnsInode\" value:\"4026532244\" > parameters:<key:\"socketfile\" value:\"nsmwvRr6gGiv/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-4\" > parameters:<key:\"workspaceNseName\" value:\"icmp-responder2zmfn\" > > context:<ip_context:<src_ip_addr:\"172.16.1.5/30\" dst_ip_addr:\"172.16.1.6/30\" src_ip_required:true dst_ip_required:true dst_routes:<prefix:\"192.168.2.0/24\" > excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" excluded_prefixes:\"11.0.0.0/22\" excluded_prefixes:\"12.0.0.0/18\" > > labels:<key:\"app\" value:\"icmp\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"icmp-responder-nse-58848df66c-7s84g\" > > "
```

I've tried the latest master with the `icmp-responder` (default setup - 4 clients, 2 endpoints) within a clean Vagrant environment with 2 nodes and I was not able to reproduce it. So I'm wondering if you did something else that might have triggered such conditions?

**Comment by johan-lj** [comment]
Hi,

ok, the other ticket I reported wasn't reproducible either with the very latest master, I'll update and try again.

Thanks for the help.

Br,
Johan

**Comment by johan-lj** [comment]
With the master from today it was fine :)
So will close this ticket

Br,
Johan
