### ISSUE TITLE
Helm make targets not compatible with Helm 3

### ISSUE THREAD

**Issue by rktidwell** [networkservicemesh/networkservicemesh#1950]
## Expected Behavior

Helm make targets should succeed when running with helm 3 (as soon as it is officially released).

## Current Behavior

My distro (openSUSE Tumbleweed) is providing helm 3 packages. When running the NSM examples that require invoking helm make targets, they fail due to significant changes to the helm CLI.

## Steps to Reproduce

1. Install helm 3
2. Begin following the steps set out in https://github.com/networkservicemesh/examples/blob/master/README.md#run-the-examples .
3. On the second step you will invoke `'SPIRE_ENABLED=false INSECURE=true make helm-init helm-install-nsm'` . This fails with the following output:

```
make[1]: Entering directory '/home/ryan/workspace/go/src/networkservicemesh'
helm init --wait && ./scripts/helm-patch-tiller.sh
Error: unknown flag: --wait
make[1]: *** [.mk/helm.mk:23: helm-init] Error 1
make[1]: Leaving directory '/home/ryan/workspace/go/src/networkservicemesh'
make: *** [Makefile:53: helm-init] Error 2
```

4. Because `'helm init'` has been removed in v3 and won't be needed, I thought I would just work around this by invoking the  `'helm-install-nsm'` target. That fails too with the following output:

```
make[1]: Entering directory '/home/ryan/workspace/go/src/networkservicemesh'
# We specifically set admission-webhook variables here as it is a subchart
# there might be a way to set these as global and refer to them with .Values.global.org
# but that seems more intrusive than this hack. Consider changing to global if the charts
# get even more complicated
helm install --name=nsm \
--atomic --timeout 300 \
--set org="networkservicemesh",tag="master" \
--set forwardingPlane="vpp" \
--set insecure="true" \
--set global.JaegerTracing="true" \
--set spire.enabled="false",spire.org="networkservicemesh",spire.tag="master" \
--set admission-webhook.org="networkservicemesh",admission-webhook.tag="master" \
--set prefix-service.org="networkservicemesh",prefix-service.tag="master" \
--namespace="nsm-system" \
deployments/helm/nsm
Error: unknown flag: --name
make[1]: *** [.mk/helm.mk:28: helm-install-nsm] Error 1
make[1]: Leaving directory '/home/ryan/workspace/go/src/networkservicemesh'
make: *** [Makefile:53: helm-install-nsm] Error 2
```

After consulting the helm help that the `--name` flag has been removed, and the `--atomic` and `--set `flags may have been removed also. Anything that interfaces with helm will eventually need to be compatible with both helm 2 and 3.

## Context

* Kubernetes Version: v1.16
* NSM master branch
* Any system with helm 3 installed

This is a minor issue in my opinion. This will eventually become a bit of a hassle once helm 3 gets out into the wild. This mostly is a blocker for people trying to experiment with the examples, but anything like CI that relies on helm could be affected. Helm v3 appears to still be in beta, so not too many people are going to hit this right now. Reverting back to helm 2 fixed the issue for me and I was able to experiment with the examples.

## Failure Logs

```
> make helm-init helm-install-nsm
make[1]: Entering directory '/home/ryan/workspace/go/src/networkservicemesh'
helm init --wait && ./scripts/helm-patch-tiller.sh
Error: unknown flag: --wait
make[1]: *** [.mk/helm.mk:23: helm-init] Error 1
make[1]: Leaving directory '/home/ryan/workspace/go/src/networkservicemesh'
make: *** [Makefile:53: helm-init] Error 2
```

```
> make helm-install-nsm
make[1]: Entering directory '/home/ryan/workspace/go/src/networkservicemesh'
# We specifically set admission-webhook variables here as it is a subchart
# there might be a way to set these as global and refer to them with .Values.global.org
# but that seems more intrusive than this hack. Consider changing to global if the charts
# get even more complicated
helm install --name=nsm \
--atomic --timeout 300 \
--set org="networkservicemesh",tag="master" \
--set forwardingPlane="vpp" \
--set insecure="true" \
--set global.JaegerTracing="true" \
--set spire.enabled="false",spire.org="networkservicemesh",spire.tag="master" \
--set admission-webhook.org="networkservicemesh",admission-webhook.tag="master" \
--set prefix-service.org="networkservicemesh",prefix-service.tag="master" \
--namespace="nsm-system" \
deployments/helm/nsm
Error: unknown flag: --name
make[1]: *** [.mk/helm.mk:28: helm-install-nsm] Error 1
make[1]: Leaving directory '/home/ryan/workspace/go/src/networkservicemesh'
make: *** [Makefile:53: helm-install-nsm] Error 2
```

**Comment by nickolaev** [comment]
@rktidwell thanks for sharing your experience here. Indeed, helm2 and helm3 command lines seem to be incompatible and there won't be a simple way forward to support them both.That said, Helm3 was officially released before KubeCon NA: https://helm.sh/blog/helm-3-released/ and Helm2 is in a "maintain it for another year" mode now. We are considering Helm3 and will move to it soon.
PRs are welcome as always :)

**Comment by rktidwell** [comment]
I'm working on a PR to get myself over the hump, will post when I have it.
