### ISSUE TITLE
[Feature Request] connectivity among pods of different clusters

### ISSUE THREAD

**Issue by vishnuitta** [networkservicemesh/networkservicemesh#1972]
## Overview
Following the steps at this NSM documentation link https://networkservicemesh.io/docs/examples/vpn/ provides the pod to pod communication in the cluster.

Requirement is to have connectivity across pods in different cloud providers.

It would be great to know if this feature request is already part of NSM roadmap or to any documentation link if feature is available.

**Comment by nickolaev** [comment]
This feature exists, we call it "Interdomain" and there are [some docs around](https://github.com/networkservicemesh/networkservicemesh/blob/master/docs/spec/interdomain.md).
We actually had a presentation at NSMCon about it https://youtu.be/sb-vfDg_gb8
So I'll call to @tiswanso about helping with putting together a proper example that will showcase this work.

**Comment by vishnuitta** [comment]
thanks @nickolaev .. Going through above links
