### ISSUE TITLE
CloudTest: Test doesn't get rescheduled when cluster fails

### ISSUE THREAD

**Issue by a-bastrykina** [networkservicemesh/networkservicemesh#1981]
## Expected Behavior

Tests should be rescheduled when cluster fails

## Current Behavior

Some tests are is not rescheduled when cluster fails

## Failure Logs

[CI logs](https://circleci.com/gh/networkservicemesh/networkservicemesh/117658)

**Comment by nickolaev** [comment]
Fixed, closing.
