### ISSUE TITLE
interdomain: network_service_managers URL using private/pod IP rather than node IP

### ISSUE THREAD

**Issue by tiswanso** [networkservicemesh/networkservicemesh#1991]
## Expected Behavior

In interdomain scenarios, the network_service_managers identifier is of the format `<nodename>@<ip addr>".  The intent is for this to be usable for the proxy-nsmd to reach the specific nsmd in the other cluster to forward requests to it.  Tvalue of the IP address should be converted by the proxy NSR to be the external node IP for the node of the target nsmd.

## Current Behavior

In interdomain scenarios, the network_service_managers identifier is of the format `<nodename>@<ip addr>" but the specific value of the IP address is the pod IP of the nsmgr on that node.  The pod IP is useless on remote clusters and should be converted by the proxy NSR (proxy-nsmd-k8s) to be the external node IP of the target nsmd.

I see some places where the proxy-nsmd-k8s is trying to get the remote clusterInfo for the node so perhaps that didn't work properly for this EKS cluster.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

## Failure Logs

From a local proxy-nsmd request--see the `network_service_managers` value (192.168.139.111:5001).
```
time="2019-12-13T17:54:17Z" level=info msg="ProxyNSMD: Received request from client to connect to NetworkService: connection:<id:\"-\" network_service:\"vl3-service@52.15.79.192\" context:<ip_context:<src_ip_required:true dst_ip_required:true src_routes:<prefix:\"172.31.0.0/24\" > > > labels:<key:\"\" value:\"\" > labels:<key:\"vl3Nse/nseSource/endpointName\" value:\"vl3-servicez7t5t\" > network_service_managers:\"gke-nsm-main1-default-pool-c9468831-8b1b\" network_service_managers:\"ip-192-168-151-42.us-east-2.compute.internal@192.168.139.111:5001\" network_service_endpoint_name:\"vl3-service4rz8l\" > mechanism_preferences:<type:\"VXLAN\" parameters:<key:\"src_ip\" value:\"10.128.0.12\" > > "
time="2019-12-13T17:54:17Z" level=info msg="Waiting for liveness probe: tcp:192.168.139.111:5001"
time="2019-12-13T17:54:32Z" level=info msg="Waiting for liveness probe: tcp:192.168.139.111:5001"
time="2019-12-13T17:54:32Z" level=info msg="Waiting for liveness probe: tcp:192.168.139.111:5001"
time="2019-12-13T17:54:32Z" level=error msg="ProxyNSMD: Failed connect to Network Service Client (ip-192-168-151-42.us-east-2.compute.internal@192.168.139.111:5001): timeout waiting for: tcp:192.168.139.111:5001"
time="2019-12-13T17:54:32Z" level=info msg=">><<-- response=null span=15f6ab504957fa69:7421dbd4068a672c:
```

**Comment by artem-belov** [comment]
Hello @tiswanso 
Could you please attach logs of nsmgr and proxy-nsmgr containers and results of next commands:
`kubectl get pods -o wide`
`kubectl get nodes -o wide`

It would help to understand and resolve an issue
Thank you

**Comment by tiswanso** [comment]
@artem-belov  -- I'm going to create some other issues instead of this one.  The issue I posted here is really due to the interdomain install not being correct because of errors/inconsistencies in the nsmgr and proxy-nsmgr helm charts.  

This symptom is seen when I expose the nsmd-k8s's in each cluster and point the proxy-nsmd-k8s at it the remote cluster's nsmd-k8s directly.  In that scenario, the remote NSR is responding directly to the local proxy-nsmd-k8s' FindNetworkServiceRequest.  In that path it doesn't convert the `network_service_manager` to the remote node's externalIP.

**Comment by tiswanso** [comment]
Closing this as it was due to a misconfig in the interdomain setup.  See #1994 for the real issues  related to deploying interdomain NSM.  I was attempting to work around/through them and hit this scenario.
