### ISSUE TITLE
NSMD doesn't recover connection in case of interdomain

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2007]
## Steps to reproduce

1) Rebase on https://github.com/networkservicemesh/networkservicemesh/pull/1861
2) Run tests:
2.1) TestInterdomainNSEHealLocalToRemote
2.2) TestInterdomainNSMHealRemoteDieNSMD_NSE // will faill. NSMD doesn't recover a connection.

## Expected Behavior

NSMD should recover a connection

## Current Behavior

NSMD doesn't recover a connection

## Logs
https://118168-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/aws-2_azure-2/002-TestInterdomainNSMHealRemoteDieNSMD_NSE-run.log

NSMD logs
[nsmgr-ip-192-168-130-59.us-east-2.compute.internal-nsmd.log](https://github.com/networkservicemesh/networkservicemesh/files/3973874/nsmgr-ip-192-168-130-59.us-east-2.compute.internal-nsmd.log)

**Comment by nickolaev** [comment]
Issue fixed with #2030. Closing.
