### ISSUE TITLE
Reconsider some testing bash sctipts in golang

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#2013]
## Overview

@nickolaev suggested to move some existing testing bash scripts in golang, such as `helm-test-charts.sh` and cloud creating tools

Lets use this "Issue" for duscussion

**Comment by artem-belov** [comment]
@edwarnicke @haiodo @lobkovilya @Denis @alex-yust @a-bastrykina

**Comment by lobkovilya** [comment]
Personally I don't like the idea to eliminate shell tests.
If we had some UI, we would have automatic ui tests. Deploying of helm charts in some way our UI, because that what users contact with. Users contact with helm charts usually using bash. That's why I believe it's really important to us to have tests that reproduce user's steps as accurately as possible.

**Comment by nickolaev** [comment]
Before #1247 our testing was a mess of shell scripts and unmaintainable CircleCI yaml:
https://github.com/networkservicemesh/networkservicemesh/pull/1247/files#diff-1d37e48f9ceff6d8030570cd36286a61

Fortunately this was removed with the excellent cloud-test framework that @haiodo introduced.
Now we are slowly returning to these testing practices. Yes, the people that use NSM will default to the helmcharts, that is where we have a nice guide
https://networkservicemesh.io/docs/setup/run/


```shell
helm repo add nsm https://helm.nsm.dev/ # Add the latest release nsm helm repo
helm install nsm/nsm # Install the nsm infrastructure in your Kubernetes Cluster
```

But I really fail to see how a shell script like this one helps any user to understand that:
https://github.com/networkservicemesh/networkservicemesh/blob/master/scripts/helm-test-charts.sh

```shell
#!/usr/bin/env bash

error(){ echo "error: $*" >&2; exit 1; }

[ -n "$*" ] && CHARTS="$*"
[ -n "$CHARTS" ] || error "chart name(s) expected as positional arguments or CHARTS variable"
[ -n "$NSM_NAMESPACE" ] || error "NSM_NAMESPACE must be set"

: "${CHECK_CMD:=make k8s-check}"

reverse() {
  { for e in "$@"; do echo "$e"; done } | tac | tr '\n' ' '
}

echo "Testing HELM chart deployment, chart(s): ${CHARTS}, namespace: ${NSM_NAMESPACE}"

for ch in $CHARTS; do
  dp="deployments/helm/$ch"
  [ -d "$dp" ] || error "Deployment $dp not found"
done

DEPLOYED_CHARTS=''

cleanup() {
  [ "$SKIP_CLEANUP" == '1' ] && echo "Skipping cleanup by flag" && return
  charts=$(reverse $DEPLOYED_CHARTS)
  echo "Deleting chart(s): $charts"
  for ch in $charts; do
    make "helm-delete-${ch}"
  done
  [ "$DELETE_NAMESPACES" == '1' ] && make k8s-delete-nsm-namespaces
  make k8s-deconfig k8s-config
  kubectl delete pods --force --grace-period 0 -n "${NSM_NAMESPACE}" --all
}

onfail() {
  errmsg="Helm chart deployment '$CHARTS' failed"
  echo "$errmsg"
  echo "Cleanup failed chart testing..."

  trap - ERR
  set +o errexit

  kubectl get pods -n "${NSM_NAMESPACE}"
  make k8s-logs-snapshot
  DELETE_NAMESPACES=1 cleanup

  echo "$errmsg"
  exit 1
}

trap onfail ERR
set -o errexit

make k8s-deconfig
# deploy charts
for ch in $CHARTS; do
  make "helm-install-$ch"
  DEPLOYED_CHARTS="$DEPLOYED_CHARTS $ch"
done
# run checks
if [ -n "$CHECK_CMD" ]; then
  echo "Executing checks: $CHECK_CMD"
  $CHECK_CMD
  echo "All checks are OK"
fi

trap - ERR
set +o errexit

make k8s-logs-snapshot-only-master
cleanup

echo "Helm chart(s) deployment '$CHARTS' succeeded"
```

Now compare the two-line guide and that huge pile of shell trickery. I continue to think that a simple ggolang implementation will be much better than any shell script. I absolutely support the "use the right tool for the job" principle, but here we are digging a rabbit hole. We already have 75 shell script files and 488 go files. That is 15%! It is a lot and we should not continue in this direction.

**Comment by lobkovilya** [comment]
Yes, you are right, script `helm-test-charts.sh` were introduced in [#1923](https://github.com/networkservicemesh/networkservicemesh/pull/1923/files) and it had to eliminate redundancy that we had before. 

But probably we have to keep shell tests as simple as possible, so they could be treated by user as concrete steps. Following that steps user could easily reproduce the whole use-case.

So what do you think about moving back to tests like:
``` 
make helm-install-nsm
make helm-install-vpn
make k8s-check
```
Yes they will be excessive, but much more readable than go-test or what we have now. Also they could be easily correspond with documentation that you mentioned.

**Comment by denis-tingajkin** [comment]
I like the idea to simplify examples. It is a super good point. We should keep our examples as easy as we can for new users. 
I also think that we can use bash scripts but it should be extremely simple. For example, as @lobkovilya  proposes. 
Something like 
```
make helm-install-nsm
make helm-install-icmp-responder
make helm-install-nsc
make nsc-ping-all
```

**Comment by nickolaev** [comment]
Yes, I am supportive of having simple scripts. Still, we need to be cautious into building a whole "framework" around them again. And it is not only the helm tests, but we also have scripts for a lot of "automation", and that may be fine. Yet let's keep a general concept that the shell scripts are only good if they (a) are simple and (b) automate some real steps to follow.
