### ISSUE TITLE
CloudTest: clusters not always deleted when exiting due force push to PR branch

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/networkservicemesh#2053]
## Expected Behavior

Clusters deleted when CloudTest exits due force push to PR branch

## Current Behavior

Clusters are not deleted

## Failure Information (for bugs)

This happens when force push occurs at the moment when clusters are in the process of being created.
https://circleci.com/gh/networkservicemesh/networkservicemesh/119668

## Context

* Kubernetes Version:
* etc.

**Comment by haiodo** [comment]
For this I think @artem-belov already added to to cleanup clusters working for >=4hours.
