### ISSUE TITLE
Example-helm-icmp test is not optimal?

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/networkservicemesh#2056]
Example-helm-icmp test uses deployments/helm/icmp-responder Helm chart
Currently it is a deployment of 4 clients and 2 endpoints, where endpoints are forced to be deployed on different nodes using Kubernetes anti-affinity feature.
Theoretically, there is still possible a situation when client-endpoint connections would be all either local or remote.

It seems a setup with just one endpoint and 2 clients (in different nodes using anti-affinity feature) would prevent the situation and provides 100% remote/local cases coverage on every run using fewer components.

The logic above also can be applied to vpp-icmp-responder chart

**Comment by nickolaev** [comment]
2 clients and 1 endpoint here makes sense. If we want to test scalability we might implement this with the integration testing (go).

**Comment by alex-yust** [comment]
fixed
