### ISSUE TITLE
Failing tests on Packet

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#2065]
## Failure Information (for bugs)
All tests are failed on one cluster, according to `prepare` cluster had only one node. 

## Failure Logs
https://circleci.com/gh/networkservicemesh/networkservicemesh/120021?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by denis-tingajkin** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/119878

**Comment by denis-tingajkin** [comment]
https://github.com/networkservicemesh/networkservicemesh/pull/2073

**Comment by lobkovilya** [comment]
@denis-tingajkin last link has some other root cause

**Comment by denis-tingajkin** [comment]
@lobkovilya oops! Link fixed.
