### ISSUE TITLE
Helm charts install command should not require --dep-up option

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/networkservicemesh#2093]
Currently, nsm chart depend on config chart which contain CRDs used to implement k8s-config make target used for testing.

Also, docs/guide-helm.md and Helm CI tests should be rewritten to use bare Helm commands instead of 'make' targets.

**Comment by nickolaev** [comment]
I think it is more or less a matter to call `make k8s-config` before the `make helm-install-nsm` and remove the `file://../config` from `requirements.yaml`.

**Comment by alex-yust** [comment]
done
