### ISSUE TITLE
Add an example of how to setup NSM working with Wireguard via helm

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2126]
## Overview

We've added support for wireguard remote mechanism for kernel forwarder https://github.com/networkservicemesh/networkservicemesh/pull/2085
And people interesting how to set wireguard up with NSM.
At this moment, we have not any examples for wireguard cases via helm on CI (we have only integration go tests but they can be not clear for users)
We need to add an example of usage wireguard via helm.

**Comment by denis-tingajkin** [comment]
@terror96 added example please take a look https://github.com/networkservicemesh/networkservicemesh/pull/2128

**Comment by denis-tingajkin** [comment]
@terror96 can we close this issue? Do you still have any questions related to wireguard helm example?

**Comment by terror96** [comment]
Yes, you can close the ticket. Thank you for the example.
