### ISSUE TITLE
Wireguard VPP Plugin

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2137]
## Overview

Current limitations in VPP prevent it from integrating with wireguard. To get around these problems, we are proposing a wireguard plugin that can speak the wireguard protocol and emit wireguard encapsulated datagrams.

## Link to the Google Docs document

https://docs.google.com/document/d/1ICYb2kV48l-T1qounqkUBetUAmme0znD9gl405HJ2VQ/edit#heading=h.rvc98q8enqpk

**Comment by glazychev-art** [comment]
Ran ipsec between two VPP instances. 
Trying to select ipsec template without encryption/decryption.

**Comment by glazychev-art** [comment]
Made a plugin with simple encrypt/decrypt nodes. Trying to run it using IPIP tunnel.

**Comment by glazychev-art** [comment]
Working at wireguard implementation.
In particular at crypto module and data structures (for peers, keys storing).
Wg seems to be closely related to the Linux kernel, so there are some difficulties with porting. I use wireguard-linix-compat repository.

**Comment by glazychev-art** [comment]
Made a crypto module. Continue work at keys and handshake packet making.

**Comment by glazychev-art** [comment]
Made a simple handshake procedure (run it manually).
Now i can also send keepalive packets (zero length message). Additionally, i sent some encrypted bytes - it works fine, the server side can correctly decrypt it. 
Now i'm working at ping sending.

**Comment by glazychev-art** [comment]
Ran ping via wg-plugin.
It's possible to connect two VPP instances. It seems to work correctly, i can ping each other.
Now i'm working on timers for auto key freshing and re-handshaking.

**Comment by glazychev-art** [comment]
Made timers for auto key freshing and connection supporting.
Tested it on thousands ping packets. No packages were lost.
Now i'm cleaning my code and preparing draft pr.

**Comment by glazychev-art** [comment]
Draft PR
https://github.com/FDio/vpp/pull/26

**Comment by glazychev-art** [comment]
Made custom vpp-agent image with plugin:
https://hub.docker.com/repository/docker/artgl/vpp-agent/
https://github.com/glazychev-art/vpp-agent/tree/wg

Now i'm reworking noise-protocol based on openbsd implementation

**Comment by glazychev-art** [comment]
Pushed commit to vpp repo for code review
https://gerrit.fd.io/r/c/vpp/+/28503

**Comment by denis-tingajkin** [comment]
Wireguard plugin is contributed into vpp and vpp-agent
https://gerrit.fd.io/r/c/vpp/+/28503
https://github.com/ligato/vpp-agent/pull/1731

The next steps are:
1. https://github.com/networkservicemesh/networkservicemesh/issues/2105
2. https://github.com/networkservicemesh/networkservicemesh/issues/2105
