### ISSUE TITLE
Advanced OPA Policies

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#2138]
## Overview

A placeholder for OPA works.

Advanced OPA Policies
* * [x] -  Create OPA examples
* * [ ] -  Single cluster SFC example
* * [ ] -  Multi-cluster SFC example
* * [ ] -  Multi-org (Interdomain), Multi-cluster SFC example
* * [ ] -  eNSM SFC example
Implement examples as demos
* * [ ] -  All examples listed above created except for eNSM
Modifications to NSM to support the above use cases

**Comment by gupta-alok** [comment]
The SFC (Service Function Chaining) property in NSM which can be policy enforced, isn't it uses network policy similar to istio?

By enforcing network policies through OPA (Open Policy Agent), does it mean NSM's choice of policy enforcement engine will be OPA?

**Comment by haiodo** [comment]
Hi @gupta-alok, yes plan to use OPA. We had already some experiments with it.
This issue is place holder to work into this direction is planned, we are fully sure how it will become.

**Comment by edwarnicke** [comment]
@gupta-alok Two kinds of policy :)  What we do right now in the Network Service definition is the policy about chaining that you reference.  All it does is reason on labels to determine what set of candidate NSEs for a request from a client are.  I don't anticipate that changing.  It's nice and clean and simple :)

What we are talking about here is the 'admissions' policy.  Basically determining whether or not an NSE is willing to provide a Network Service to a given Client, or a Client is willing to accept a service *from* a given NSE.  Make sense?
