### ISSUE TITLE
SR-IOV support

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#2139]
## Overview
* Current SR-IOV plugin is reliant on a device plugin which makes many poor assumptions about the environment. A new SR-IOV plugin is necessary to rectify these problems and unlock SR-IOV.
* [ ] - NSM XConnectNS Forwarder that:
* Exposes an SRIOV K8s Device Plugin appropriate to NSM
* * [ ] - Including rebinding to default driver on allocate
* * [ ] - Correctly handles privileged bits of programming SR-IOV VF to:
* * [ ] - Program any privileged bits necessary for ‘VLAN’ remote mechanism
* Supports local Mechanisms:
* * [ ] - Kernel interface - by binding VF to kernel interface driver
* * [ ] - VFIO

**Comment by lvfxx** [comment]
Trying to launch [existing SR-IOV plugin](https://github.com/networkservicemesh/networkservicemesh/tree/release-0.2/controllers/sriov-controller) to get better understanding how it works and what we need to change in a new plugin. There is a note in readme.md:
`nsm-sriov-config-manager is a standalone binary which should be but not mandatory executed before sriov-controller.`
I wonder where is this nsm-sriov-config-manager? Perhaps i don't need it at all for my testing purposes and can use generated configmap example from readme..
