### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by sbezverk** [networkservicemesh/networkservicemesh#2143]
## Expected Behavior

Following documentation  to install nsm and expect to have fully functional nsm 
Here is the link:
https://github.com/networkservicemesh/networkservicemesh/blob/master/docs/guide-helm.md

## Current Behavior
Installation is failing with error.

## Failure Information (for bugs)

sbezverk@bruce-dev1:~/nsm$ helm install deployments/helm/nsm
Error: must either provide a name or specify --generate-name

## Steps to Reproduce

1. `git clone https://github.com/networkservicemesh/networkservicemesh nsm`
2. `git checkout v0.2.0`
3.  `helm install deployments/helm/nsm`

## Context

* Kubernetes Version: v1.17.4
* etc.

## Failure Logs

helm install deployments/helm/nsm
Error: must either provide a name or specify --generate-name

**Comment by liuming-dev** [comment]
You have missing the release name argument, try `helm install -h` to see the usage.

![image](https://user-images.githubusercontent.com/11614773/79709510-e4c57b80-82f4-11ea-9b8f-f7dffef69da0.png)

**Comment by haiodo** [comment]
Hi @sbezverk,
Did you use helm v3? v2.0 support helm v2 only.

Support for helm v3, still in PR: https://github.com/networkservicemesh/networkservicemesh/pull/2075

**Comment by houstar** [comment]
@haiodo ,  Could we merge PR#2075 ASAP? I'm struggled with installation issue while using helm3

**Comment by edwarnicke** [comment]
@houstar Merged #2075 

Does that solve your issue here?
