### ISSUE TITLE
External clients can not use port of proxy nsmgr via nsm annotation

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2154]
## Expected Behavior

The external client could pass all required parameters via NSM annotation.

## Current Behavior

The external client could not pass the proxy port in the interdomain case via NSM annotation.

## Failure Logs

```
Error from server: error when creating "examples/examples/icmp/k8s/simple-client.yaml": admission webhook "admission-webhook.networkservicemesh.io" denied the request: parse icmp-responder@172.17.0.7:5001?app=simple-client: first path segment in URL cannot contain colon
```

## Steps to Reproduce

1. setup two clusters with nsmgr and pnsmgr
2. deploy examples/examples/icmp/k8s/simple-endpoint.yaml on cluster1
3. Replace nsm label in examples/examples/icmp/k8s/simple-client.yaml to `icmp-responder@{IP}:{PORT}`
4. deploy nsc from step 3 on cluster2

Actual: see at Failure logs
Expected: no errors?

**Comment by denis-tingajkin** [comment]
@edwarnicke Do we need to fix this issue?

**Comment by edwarnicke** [comment]
You specify networkservices via annotation, not network service endpoints.  networkservice's don't have a 'port'.

**Comment by denis-tingajkin** [comment]
@edwarnicke  yes it is correct but in case of interdomain currently, we allow to use this pattern via env variable `CLIENT_NETWORK_SERVICE`

**Comment by edwarnicke** [comment]
I don't think we should be doing that at all... a network service doesn't contain a port.

**Comment by denis-tingajkin** [comment]
Actually, it is not a problem. Network service should not contain a port.
