### ISSUE TITLE
Annotations to connect to multiple NSEs connects to the same

### ISSUE THREAD

**Issue by uablrek** [networkservicemesh/networkservicemesh#2156]
## Expected Behavior

When using annotations to connect to multiple NSEs;
```
metadata:
  name: simple-client-2
  namespace: default
  annotations:
    ns.networkservicemesh.io: bridge-domain?app=bridge,bridge-domain-ipv6?app=bridge-ipv6
```
there should be two interfaces, "nsm0" and "nsm1", connected to the two different specified endpoints.

## Current Behavior

The two interfaces are created but they are connected to the same endpoint;

```
nsm0      Link encap:Ethernet  HWaddr 76:9F:82:83:46:E2  
          inet6 addr: fe80::749f:82ff:fe83:46e2/64 Scope:Link
          inet6 addr: 1200::6/120 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:61 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5782 (5.6 KiB)  TX bytes:962 (962.0 B)

nsm1      Link encap:Ethernet  HWaddr 3A:1B:D0:1A:1E:D8  
          inet6 addr: 1200::9/120 Scope:Global
          inet6 addr: fe80::381b:d0ff:fe1a:1ed8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:746 (746.0 B)  TX bytes:892 (892.0 B)
```
In this example the interfaces should get addresses from different families.

## Steps to Reproduce

The [examples/bridge-domain](https://github.com/networkservicemesh/examples/tree/master/examples/bridge-domain) was used;

1. Start a cluster with NSM
2. Run the bridge-domain example
3. Run the bridge-domain-ipv6 example
4. Start yet another simple-client with both endpoint annotated
5. Login to simple-client-2 and do `ifconfig`

The manifest for the "extra" simple-client; [simple-client-2.yaml](https://github.com/networkservicemesh/networkservicemesh/files/4644746/simple-client-2.yaml.txt)

## Context

* Kubernetes Version: v1.18.2
* NSM built from commit 9a17692e4a5
* NSM/examples from commit 2a59960b7ade4a349bb7019280a10169b3f375a1

**Comment by edwarnicke** [comment]
Let's talk through what you are looking to do here :)

The contract for that annotation in NSM is that if you ask for multiple *Network Services* we will connect you to those Network Services.  We don't (currently, but happy to talk about) make any guarantees a priori about which NSEs we connect you to for those network services.

It sounds like you have two distinct network services 'bridge-domain' and 'bridge-domain-ipv6' that you are asking for... and you have them both provided by the same NSE (totally fine, often even a good idea :) ).

I presume from what you are saying that you have multiple NSEs providing those services, and your *preference* would be some form of stickiness so that when a Pod connect to one, you keep connecting to the same one (even though its providing a different Network Service).

I can totally see why that behavior is *sometimes* desireable (and sometimes not).  So the question is: how can we get you what you need in a way that preserves the flexibility of the system :)

Did I get that all right? :)

**Comment by edwarnicke** [comment]
One other question... do you happen to know why bridge-domain and bridge-domain-ipv6 are distinct (other than perhaps IPAM issues?).  Normally when I think of a bridge domain I think of it as something that is looking at L2 frames, and so would be agnostic between IPv4 and IPv6 :)

**Comment by uablrek** [comment]
Second question first; as I recall the IPAM did not allow more than one address at the time of writing. But it may also be to simply separate ipv6.

**Comment by uablrek** [comment]
First question; I thought these were different services. How can I tell they are the same?
```
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "bridge-domain-ipv6"
```
`ENDPOINT_NETWORK_SERVICE` are different.

**Comment by edwarnicke** [comment]
> Second question first; as I recall the IPAM did not allow more than one address at the time of writing. But it may also be to simply separate ipv6.

Yeah... if that's still true, we should definitely fix that root underlying issue :)

**Comment by edwarnicke** [comment]
> First question; I thought these were different services. How can I tell they are the same?
> 
> ```
>           env:
>             - name: ENDPOINT_NETWORK_SERVICE
>               value: "bridge-domain-ipv6"
> ```
> 
> `ENDPOINT_NETWORK_SERVICE` are different.

I don't quite follow this comment.  Could you say more?

**Comment by uablrek** [comment]
Um, I think I misread. You *are* saying that there are 2 services, sorry.

But implemented by the same NSE? There are 2 different PODs. Here is a list of pods in my system;
```
> kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
default       bridge-domain-67dd974897-677l9           1/1     Running   0          43s
default       bridge-domain-ipv6-79679bc995-2knxh      1/1     Running   0          25s
default       nsm-admission-webhook-5f49675b9c-c8vtk   1/1     Running   0          84s
default       nsm-vpp-forwarder-7v4kh                  1/1     Running   0          84s
default       nsm-vpp-forwarder-87hns                  1/1     Running   0          84s
default       nsm-vpp-forwarder-qm9g4                  1/1     Running   0          84s
default       nsm-vpp-forwarder-sgzkc                  1/1     Running   0          84s
default       nsmgr-56tw4                              3/3     Running   0          84s
default       nsmgr-5mlqp                              3/3     Running   0          84s
default       nsmgr-966rw                              3/3     Running   0          84s
default       nsmgr-q6jgb                              3/3     Running   0          84s
default       prefix-service-6dc94f94f6-wdv5v          1/1     Running   0          84s
default       simple-client-2-855c8db46b-9swtd         3/3     Running   0          8s
default       simple-client-2-855c8db46b-kb8vm         3/3     Running   0          8s
default       simple-client-2-855c8db46b-z52fr         3/3     Running   0          8s
default       simple-client-8fb4d7bf9-bprpk            3/3     Running   0          38s
default       simple-client-8fb4d7bf9-kmgbn            3/3     Running   0          38s
default       simple-client-8fb4d7bf9-rqj5l            3/3     Running   0          38s
default       simple-client-ipv6-6bccb686f7-bh54v      3/3     Running   0          20s
default       simple-client-ipv6-6bccb686f7-h6szw      3/3     Running   0          20s
default       simple-client-ipv6-6bccb686f7-tmlg5      3/3     Running   0          20s
kube-system   metrics-server-694f99474-85snl           1/1     Running   0          89s
spire         spire-agent-b4952                        1/1     Running   0          84s
spire         spire-agent-ddz87                        1/1     Running   0          83s
spire         spire-agent-t96fl                        1/1     Running   0          82s
spire         spire-agent-wlvtw                        1/1     Running   0          83s
spire         spire-server-0                           2/2     Running   0          83s
```

**Comment by edwarnicke** [comment]
Ah... OK... so you have distinct NSEs for each of 'bridge-domain' and 'bridge-domain-ipv6'  :)

Which means that I misunderstood the issue.  I apparently read to fast:
>The two interfaces are created but they are connected to the same endpoint;

 So nsm0 and nsm1 are both connected to 'bridge-domain' (or 'bridge-domain-ipv6') ?

**Comment by uablrek** [comment]
Yes, to bridge-domain-ipv6. I have not entirely ruled out that they are connected to different nse's but the fault is that they use IPAM form the same nse (which is definitely ipv6).

**Comment by edwarnicke** [comment]
Yeah... that sounds like a bug.

Let's see who we can get to look at it :)
