### ISSUE TITLE
Network Service CRD responds with old values (not updated) when NSMgr tries to find a match

### ISSUE THREAD

**Issue by vparames86** [networkservicemesh/networkservicemesh#2165]
## Expected Behavior
When the Network Service CRD for a network service is updated via API, the NSMgr should fetch the new values for the Network Service.

## Current Behavior
When NetworkService CRD gets updated for a network service, The response to NMSgr from network service returns old values, when it tries to find a match for NSC -> NSE and errors out with 
"**error=NSM:(7.1.5) <nil>. Last NSE Error: failed to find NSE for NetworkService vppvethquagga02**". 

## Steps to Reproduce

1. Create a Network Service describing the matches (source selector, destination selector etc).
2. Update the Network Service with new set of matches.
3. NSMgr is not able to find a match for the new match added, since it is still getting the old values in the response and not able to find the new match.

## Context

* Kubernetes Version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.2", GitCommit:"a7b4459cd1cf89420e2370ae5d067fc5ad6629ba", GitTreeState:"clean", BuildDate:"2020-01-21T10:43:51Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

## Failure Logs

**CRD:**
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  creationTimestamp: "2020-06-09T01:50:36Z"
  generation: 3
  name: vppvethquagga02
  namespace: default
  resourceVersion: "24822084"
  selfLink: /apis/networkservicemesh.io/v1alpha1/namespaces/default/networkservices/vppvethquagga02
  uid: fbdee5d3-ee25-4236-964b-195c28aa6cb9
spec:
  matches:
  - match: null
    route:
    - destination: null
      destinationSelector:
        device: vppvethquagga04
    sourceSelector:
      link: net-190
  - match: null
    route:
    - destination: null
      destinationSelector:
        device: vppvethquagga05
    sourceSelector:
      **link: net-191** -> New match added
  - match: null
    route:
    - destination: null
      destinationSelector:
        device: vppvethquagga04
    sourceSelector:
      link: net-192
  payload: IP

**LOGS:** (Highlighted logs where the response still shows the old one
time="2020-06-09T17:29:50Z" level=info msg=">><<------ request={\"connection\":{\"network_service\":\"vppvethquagga02\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true}},\"labels\":{\"link\":\"net-191\",\"namespace\":\"default\",\"peerif\":\"eth2\",\"podName\":\"vppvethquagga04-6cdbddbb98-gknwz\"}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\"}}]} span={}"
time="2020-06-09T17:29:50Z" level=info msg="Received request from client to connect to NetworkService: connection:<network_service:\"vppvethquagga02\" context:<ip_context:<src_ip_required:true dst_ip_required:true > > labels:<key:\"link\" value:\"net-191\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"peerif\" value:\"eth2\" > labels:<key:\"podName\" value:\"vppvethquagga04-6cdbddbb98-gknwz\" > > mechanism_preferences:<cls:\"LOCAL\" type:\"KERNEL_INTERFACE\" parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"eth2\" > parameters:<key:\"netnsInode\" value:\"4026532896\" > parameters:<key:\"socketfile\" value:\"eth2/memif.sock\" > > "
time="2020-06-09T17:29:50Z" level=info msg="==--------> Local.*connectionService.Request() span:{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<-------- request={\"connection\":{\"network_service\":\"vppvethquagga02\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true}},\"labels\":{\"link\":\"net-191\",\"namespace\":\"default\",\"peerif\":\"eth2\",\"podName\":\"vppvethquagga04-6cdbddbb98-gknwz\"}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\",\"workspace\":\"nsm-66\"}}]} span={}"
time="2020-06-09T17:29:50Z" level=info msg="Received request from client to connect to NetworkService: connection:<network_service:\"vppvethquagga02\" context:<ip_context:<src_ip_required:true dst_ip_required:true > > labels:<key:\"link\" value:\"net-191\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"peerif\" value:\"eth2\" > labels:<key:\"podName\" value:\"vppvethquagga04-6cdbddbb98-gknwz\" > > mechanism_preferences:<cls:\"LOCAL\" type:\"KERNEL_INTERFACE\" parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"eth2\" > parameters:<key:\"netnsInode\" value:\"4026532896\" > parameters:<key:\"socketfile\" value:\"eth2/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-66\" > > " span="{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------- connection-id= span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------- workspace=nsm-66 span={}"
time="2020-06-09T17:29:50Z" level=info msg="resourceAdded started: &{6e9 <nil> <nil> <nil> <nil>  1 0 <nil> 0xc0025a6d20}"
time="2020-06-09T17:29:50Z" level=info msg="resourceAdded finished: &{6e9 <nil> <nil> <nil> <nil>  1 0 <nil> 0xc0025a6d20}"
time="2020-06-09T17:29:50Z" level=info msg="==----------> Local.*forwarderService.Request() span:{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------- request={\"connection\":{\"id\":\"6e9\",\"network_service\":\"vppvethquagga02\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true}},\"labels\":{\"link\":\"net-191\",\"namespace\":\"default\",\"peerif\":\"eth2\",\"podName\":\"vppvethquagga04-6cdbddbb98-gknwz\"}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\",\"workspace\":\"nsm-66\"}}]} span={}"
time="2020-06-09T17:29:50Z" level=info msg="==------------> wait-forwarder() span:{}"
time="2020-06-09T17:29:50Z" level=info msg="Waiting for forwarder available..." operation=wait-forwarder span="{}"
time="2020-06-09T17:29:50Z" level=info msg="==----------> ClientConnectionAdded() span:{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------- clientConnection={\"ConnectionID\":\"6e9\",\"Request\":null,\"Xcon\":null,\"RemoteNsm\":null,\"Endpoint\":null,\"ForwarderRegisteredName\":\"\",\"ConnectionState\":1,\"ForwarderState\":0,\"Span\":null,\"Monitor\":{\"Server\":{}}} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<------------ dataplane={\"RegisteredName\":\"vppagent\",\"SocketLocation\":\"/var/lib/networkservicemesh/nsm-vppagent.forwarder.sock\",\"LocalMechanisms\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}],\"RemoteMechanisms\":[{\"type\":\"VXLAN\",\"parameters\":{\"src_ip\":\"10.240.0.4\"}}],\"MechanismsConfigured\":true} span={}"
time="2020-06-09T17:29:50Z" level=info msg="==------------> Local.*endpointSelectorService.Request() span:{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<------------ request={\"connection\":{\"id\":\"6e9\",\"network_service\":\"vppvethquagga02\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\",\"workspace\":\"nsm-66\"}},\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true}},\"labels\":{\"link\":\"net-191\",\"namespace\":\"default\",\"peerif\":\"eth2\",\"podName\":\"vppvethquagga04-6cdbddbb98-gknwz\"}},\"mechanism_preferences\":[{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\",\"workspace\":\"nsm-66\"}}]} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<-------------- requestNSEOnUpdate=false span={}"
time="2020-06-09T17:29:50Z" level=info msg="==--------------> select-nse-1() span:{}"
time="2020-06-09T17:29:50Z" level=info msg="==----------------> GetEndpoint() span:{}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- request={\"id\":\"6e9\",\"network_service\":\"vppvethquagga02\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"Primary interface\",\"name\":\"eth2\",\"netnsInode\":\"4026532896\",\"socketfile\":\"eth2/memif.sock\",\"workspace\":\"nsm-66\"}},\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true}},\"labels\":{\"link\":\"net-191\",\"namespace\":\"default\",\"peerif\":\"eth2\",\"podName\":\"vppvethquagga04-6cdbddbb98-gknwz\"}} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- ignores={} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- targetEndpoint=\"\" span={}"
time="2020-06-09T17:29:50Z" level=info msg="Requesting NetworkServiceDiscoveryClient..."
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- nseRequest={\"network_service_name\":\"vppvethquagga02\"} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- /registry.NetworkServiceDiscovery/FindNetworkService()=\"\" span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- request={\"network_service_name\":\"vppvethquagga02\"} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- response={\"payload\":\"IP\",\"network_service\":{\"name\":\"vppvethquagga02\",\"payload\":\"IP\",\"matches\":[{\"source_selector\":{\"link\":\"net-190\"},\"routes\":[{\"destination_selector\":{\"device\":\"vppvethquagga04\"}}]}]},\"network_service_managers\":{\"k8s-agentpool-24376997-vmss000000\":{\"name\":\"k8s-agentpool-24376997-vmss000000\",\"url\":\"10.240.0.26:5001\",\"state\":\"RUNNING\"},\"k8s-agentpool-24376997-vmss00001c\":{\"name\":\"k8s-agentpool-24376997-vmss00001c\",\"url\":\"10.240.0.174:5001\",\"state\":\"RUNNING\"}},\"network_service_endpoints\":[{\"name\":\"vppvethquagga02dwpmg\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga03\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga02ks8th\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss000000\",\"labels\":{\"device\":\"vppvethquagga04\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga02x4wct\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga05\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga028cr7w\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga06\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"}]} span={}"
time="2020-06-09T17:29:50Z" level=info msg=">><<---------------- **nseResponse={\"payload\":\"IP\",\"network_service\":{\"name\":\"vppvethquagga02\",\"payload\":\"IP\",\"matches\":[{\"source_selector\":{\"link\":\"net-190\"},\"routes\":[{\"destination_selector\":{\"device\":\"vppvethquagga04\"}}]}]},\"network_service_managers\":{\"k8s-agentpool-24376997-vmss000000\":{\"name\":\"k8s-agentpool-24376997-vmss000000\",\"url\":\"10.240.0.26:5001\",\"state\":\"RUNNING\"},\"k8s-agentpool-24376997-vmss00001c\":{\"name\":\"k8s-agentpool-24376997-vmss00001c\",\"url\":\"10.240.0.174:5001\",\"state\":\"RUNNING\"}},\"network_service_endpoints\":[{\"name\":\"vppvethquagga02dwpmg\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga03\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga02ks8th\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss000000\",\"labels\":{\"device\":\"vppvethquagga04\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga02x4wct\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga05\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"},{\"name\":\"vppvethquagga028cr7w\",\"payload\":\"IP\",\"network_service_name\":\"vppvethquagga02\",\"network_service_manager_name\":\"k8s-agentpool-24376997-vmss00001c\",\"labels\":{\"device\":\"vppvethquagga06\",\"networkservicename\":\"vppvethquagga02\"},\"state\":\"RUNNING\"}]} span={}"**
time="2020-06-09T17:29:50Z" level=info msg="Selecting endpoint for vppvethquagga02 with 1 matches."
time="2020-06-09T17:29:50Z" level=info msg="Matching endpoint for labels map[link:net-191 namespace:default peerif:eth2 podName:vppvethquagga04-6cdbddbb98-gknwz]"
time="2020-06-09T17:29:50Z" level=error msg=">><<---------------- error=failed to find NSE for NetworkService vppvethquagga02. Checked: 0 of total NSEs: 4\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*nseManager).GetEndpoint\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/nsm/nse_manager.go:71\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*endpointSelectorService).selectEndpoint\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/endpoint_selector_service.go:133\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*endpointSelectorService).prepareRequest\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/endpoint_selector_service.go:255\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*endpointSelectorService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/endpoint_selector_service.go:75\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*forwarderService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/forwarder_service.go:124\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*connectionService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/connection_service.go:89\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/local.(*workspaceProviderService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/local/workspace_service.go:46\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*monitorService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/monitor_service.go:43\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*requestValidator).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/request_service.go:37\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*nextEndpoint).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:90\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.ProcessNext\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/next.go:61\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*requestValidator).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/request_service.go:37\ngithub.com/networkservicemesh/networkservicemesh/controlplane/pkg/common.(*CompositeNetworkService).Request\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/pkg/common/composite.go:45\ngithub.com/networkservicemesh/networkservicemesh/controlplane/api/networkservice._NetworkService_Request_Handler.func1\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/api/networkservice/networkservice.pb.go:179\ngithub.com/networkservicemesh/networkservicemesh/pkg/tools.CloneArgsServerInterceptor.func1.1\n\t/home/venkat/virtualnetlab/networkservicemesh/pkg/tools/interceptor.go:60\ngithub.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1\n\t/home/venkat/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57\ngithub.com/networkservicemesh/networkservicemesh/pkg/tools.CloneArgsServerInterceptor.func1\n\t/home/venkat/virtualnetlab/networkservicemesh/pkg/tools/interceptor.go:64\ngithub.com/networkservicemesh/networkservicemesh/controlplane/api/networkservice._NetworkService_Request_Handler\n\t/home/venkat/virtualnetlab/networkservicemesh/controlplane/api/networkservice/networkservice.pb.go:181\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/home/venkat/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/home/venkat/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/home/venkat/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722\nruntime.goexit\n\t/usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 span={}"

**Comment by edwarnicke** [comment]
@vparames86 Interested in trying your hand at a fix? :)

https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/nsmd-k8s/main.go

**Comment by vparames86** [comment]
@edwarnicke - Already checking the code. Would be interested in trying :). Since I am new might need some assistance in fixing the issue. I see a cache layer where the NSE registrations are cached. Do I need to find a way to update this cache when the network service CRD gets updated?

**Comment by edwarnicke** [comment]
@vparames86 Delighted to assist!

We do cache... basically, what ends up happening is that we keep a cache locally.  That cache should be updated from the CRDs.  If you chase down through the server, you will find where we are listening for CRD updates.

**Comment by vparames86** [comment]
I went through the code but couldn't find where we are listening for CRD updates. Could you please point me to the file.

**Comment by denis-tingajkin** [comment]
@vparames86 I think you need to start from here https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/pkg/registryserver/resourcecache/resource_cache.go#L144
