### ISSUE TITLE
Interdomain NSM: client and endpoint on the same cluster node fails

### ISSUE THREAD

**Issue by terror96** [networkservicemesh/networkservicemesh#2169]
## Expected Behavior

Client and endpoint can reside on the same cluster node in the case of interdomain NSM.

## Current Behavior

Client fails to init.

## Failure Information (for bugs)

nsm-vpp-forwarder-lspbp: level=error msg="VPPApiError: Source and destination are the same (-82)" loc="descriptor/interface_crud.go(95)" logger=vpp-ifplugin.if-descriptor

nsmd: level=error msg="NSM:(9.1.1) Forwarder request failed: rpc error: code = FailedPrecondition desc = KeyErrors: [config/vpp/v2/interfaces/SRC-b (CREATE): VPPApiError: Source and destination are the same (-82)] retry: 4" operation=ProgramAttempt-4

## Steps to Reproduce

Create two k8s clusters (cluster 1 and cluster 2) with one worker node in each, and deploy nsmrs in cluster 1. Deploy nsm and proxy-nsmgr to both clusters. Launch both endpoint and client in cluster 1, and make sure that they are spawned on the same worker node.

Please note. We are using OpenStack VMs, not kind etc.

## Failure Logs

The above messages are extracted from 'nsm-vpp-forwarder-lspbp' and 'nsmd' in cluster 1.

**Comment by denis-tingajkin** [comment]
@terror96 Am I understand correctly that the client wants "networkservice@client.domain"?

**Comment by denis-tingajkin** [comment]
It is a good catch :) 

@edwarnicke Should we fix this issue for monorpo?

**Comment by edwarnicke** [comment]
@denis-tingajkin Please do :)

@terror96 Thanks for reporting the issue :)

**Comment by terror96** [comment]
> @terror96 Am I understand correctly that the client wants "${networkservice name}@${client domain}"?

The client is configured to request endpoint at ${networkservice name}@${NSMRS}.

**Comment by denis-tingajkin** [comment]
@terror96 The problem should be fixed with #2170, can you please check? :)

**Comment by terror96** [comment]
> @terror96 The problem should be fixed with #2170, can you please check? :)

Sure :) Yes, I can confirm that it now works also in our OS setup. Good job, thanks.

**Comment by denis-tingajkin** [comment]
Fixed by #2170

**Comment by tiswanso** [comment]
Unless I'm misunderstanding, this fix seems to make it so any requests to the interdomain NSM will not see any endpoints outside of the local cluster.  I would've expected the fix to enhance the endpoint selection criteria to prefer local endpoints.

**Comment by edwarnicke** [comment]
> Unless I'm misunderstanding, this fix seems to make it so any requests to the proxy NSR will not see any endpoints outside of the local cluster. I would've expected the fix to enhance the endpoint selection criteria to prefer local endpoints.

Hmm... I would expect topological concerns to be handled in the NetworkService 'Matches', not by default choice in NSM itself...  NSM should *enable* topology, but not enforce it.

**Comment by tiswanso** [comment]
> > Unless I'm misunderstanding, this fix seems to make it so any requests to the proxy NSR will not see any endpoints outside of the local cluster. I would've expected the fix to enhance the endpoint selection criteria to prefer local endpoints.
> 
> Hmm... I would expect topological concerns to be handled in the NetworkService 'Matches', not by default choice in NSM itself... NSM should _enable_ topology, but not enforce it.

I think we're saying the same thing, right?  The proxy-nsmgr deciding to only return local endpoints is my concern.

**Comment by edwarnicke** [comment]
@tiswanso Yeah.. it should *also* return local endpoints, definitely... but not exclusively.
