### ISSUE TITLE
Azure cloud instances fail with error 'Operation failed with status: 'Bad Request'

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2172]
## Failure Information (for bugs)
https://app.circleci.com/pipelines/github/networkservicemesh/networkservicemesh/9060/workflows/2fa11b49-38f7-4542-8e6c-203fe999f52d/jobs/122183/tests
## Steps to Reproduce

Trigger CI

**Comment by denis-tingajkin** [comment]
@edwarnicke Can this problem be related to the subscription problem?

**Comment by denis-tingajkin** [comment]
@haiodo I haven't access to AKS, so if you'll have a time please take a look at this issue.

**Comment by haiodo** [comment]
I think we already resolved this by fixing kubernetes Version, @denis-tingajkin  Please close if so.

**Comment by denis-tingajkin** [comment]
@haiodo yes, sure
