### ISSUE TITLE
Guaranteed QoS  class NSE can't register the service

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/networkservicemesh#2183]
## Expected Behavior

The NSE pod has Guranteed QoS class for resources like below.

```
          resources:
            limits:
              networkservicemesh.io/socket: 1
              cpu: 4
              memory: 1Gi
```

When deploying it with helm chart, NSE pod should come up and its service should be registered with NSMgr appropriately.

## Current Behavior

NSE pod comes up properly, but its service is not registered with NSM. 
But this works perfectly fine for 'Burstable' QoS class NSE pods.

## Failure Information (for bugs)

This seems to be an issue with spire, as per NSE pod logs (after adding few debug messages in the endpoint initialization code path), it hangs on [NewSpireProvider](https://github.com/networkservicemesh/networkservicemesh/blob/master/pkg/security/spire.go#L47). Not sure why it waits indefinitely there.

## Steps to Reproduce

1. Change [icmp-responder-nse.tpl](https://github.com/networkservicemesh/networkservicemesh/blob/master/deployments/helm/endpoint/templates/icmp-responder-nse.tpl#L40) to have Guranteed QoS class for resources like above.
2. `make helm-install-endpoint`
3. Now look for icmp-responder `NetworkService `in the default namespace.

## Context

* Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pperiyasamy** [comment]
seeing the below logs continuously from spire agent pod while bringing up the Guaranteed QoS class NSE pod.

```
2020/09/08 12:39:09 Kube pod entry found, but without container id: /kubepods.slice/kubepods-pod82937187_6b6a_44f0_923d_edaf069ff465.slice/docker-cafea808ac048ddaa135c15337d540c4d9922c5aaa2ff4211a622169def7c1a8.scope
2020/09/08 12:39:09 Kube pod entry found, but without container id: /kubepods.slice/kubepods-pod82937187_6b6a_44f0_923d_edaf069ff465.slice/docker-cafea808ac048ddaa135c15337d540c4d9922c5aaa2ff4211a622169def7c1a8.scope
```

which seems to be related to this spiffe [issue ](https://github.com/spiffe/spire/issues/1535)

**Comment by pperiyasamy** [comment]
The NSC pods are also set to `Burstable `QoS class when `Guaranteed `QoS class is requested for resources. This happens if service request is initiated with its init container.  This seems to be related to [this k8s issue](https://github.com/kubernetes/kubernetes/issues/93282). 

Should we workaround this issue in [admission webhook](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/admission-webhook/mutate.go) to have resource requirements for init container as same as client container ?

**Comment by xzfc** [comment]
We updated spire to 0.11.0, which should fix the issue. Could you please confirm?

---

> Should we workaround this issue in admission webhook to have resource requirements for init container as same as client container?

Yes, I discussed it with the team. I'll add it in a few days.

**Comment by denis-tingajkin** [comment]
@xzfc Since this issue is closed I think we should create another to tracking the status of adding limits into our containers.

**Comment by xzfc** [comment]
#2187
