### ISSUE TITLE
Bridge-domain client cannot connect

### ISSUE THREAD

**Issue by U24543426** [networkservicemesh/networkservicemesh#2204]
## Expected Behavior

Attempting to run examples/examples/bridge-domain/
At a minimum, expecting both the client and the endpoint pods to reach the ready state

The powerful conceptual model of NSM can allow implementation of many useful scenarios even on a single node cluster. Unfortunately, it seems like simple configurations with one or more nodes with bare-metal k8s is being missed in integration tests because of constraining the basic scope on Kind, Vagrant type abstractions. One of the recent Issues about "too many open files" related to nsmgr gRPC communication is another example of these simple scenarios where we cannot run two node bare-metal k8s. The problem we are reporting here also manifests itself via gRPC--even though the root cause may be different, but at least the gRPC error reports are not helping much in understanding what is going wrong.

## Current Behavior

The client cannot get past the initContainer stage
   ```
 % NAMESPACE  NAME                                                READY   STATUS   RESTARTS  AGE   IP             
 % nsm-system   simple-client-6b874485b5-jbnkv  0/3         Init:1/2     6                  17m   10.32.0.10    
```

icmp-responder test example works in this simple environment, but cannot get anything else to work
icmp-client completes init stage, gets an ip, and can ping the endpoint (since this is single host, the second icmp-client is not used)

## Failure Information (for bugs)

Two key indicators in the logs are the following:
from the msgr pod logs:

```
time= 2020-10-06T13:13:29Z  level=info msg= >><<-------------- request={ id : 994 , payload : IP , source :{ id : 994 , network_service : bridge-domain , mechanism :{ cls : LOCAL , type : KERNEL_INTERFACE , parameters :{ description : Primary interface , name : nsm0 , netnsInode : 4026533123 , socketfile : nsm0/memif.sock , workspace : nsm-8 }}, context :{ ip_context :{ src_ip_addr : 172.16.1.1/24 , dst_ip_addr : 172.16.1.0/24 , src_ip_required :true, dst_ip_required :true, excluded_prefixes :[ 10.96.0.0/13 ]}}, labels :{ app : bridge , namespace : nsm-system , podName : simple-client-6b874485b5-d94gx }}, destination :{ id : 995 , network_service : bridge-domain , mechanism :{ cls : LOCAL , type : MEMIF , parameters :{ description : NSM Endpoint , name : nsmmUv9cIVyE , netnsInode : 4026533046 , socketfile : nsmmUv9cIVyE/memif.sock , workspace : nsm-106 , workspaceNseName : bridge-domainnht77 }}, context :{ ip_context :{ src_ip_addr : 172.16.1.1/24 , dst_ip_addr : 172.16.1.0/24 , src_ip_required :true, dst_ip_required :true, excluded_prefixes :[ 10.96.0.0/13 ]}}, labels :{ app : bridge , namespace : nsm-system , podName : bridge-domain-5ddd6f6764-qc5t7 }, path :{ path_segments :[{ name : kubebe }]}}} span=<nil> 
time= 2020-10-06T13:13:29Z  level=error msg= NSM:(9.1.1) Forwarder request failed: rpc error: code = Unknown desc = remote: **invalid connection type retry: 1**  operation=ProgramAttempt-1
```

from the client pod logs:

```
time= 2020-10-06T13:24:51Z  level=info msg= Requesting connection:<network_service: bridge-domain  context:<ip_context:<src_ip_required:true dst_ip_required:true > > labels:<key: app  value: bridge  > labels:<key: namespace  value: nsm-system  > labels:<key: podName  value: simple-client-6b874485b5-d94gx  > > mechanism_preferences:<cls: LOCAL  type: KERNEL_INTERFACE  parameters:<key: description  value: Primary interface  > parameters:<key: name  value: nsm0  > parameters:<key: netnsInode  value: 4026533123  > parameters:<key: socketfile  value: nsm0/memif.sock  > >   operation= nsmClient.Connect.attempt:0 
time= 2020-10-06T13:24:55Z  level=error msg= nsm client: **Failed to connect rpc error:** code = Unknown desc = remote: invalid connection type. Retry attempts: 10 Delaying: 5s  operation= nsmClient.Connect.attempt:0 
```

## Steps to Reproduce

1. Ubuntu 18.04
2. behind corporate proxy 
3. install docker 19.03.13, k8s 1.19.2
4. sudo kubeadm reset
5. sudo kubeadm init
6. kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
7. kubectl taint nodes --all node-role.kubernetes.io/master-
(apply nvidia-device-plugin ...)
8. git clone https://github.com/networkservicemesh/networkservicemesh.git
9. make k8s-build
10. 
export NSM_NAMESPACE="nsm-system"
export CLUSTER_RULES_PREFIX=null
export SPIRE_ENABLED=false
export INSECURE=true
export FORWARDING_PLANE=kernel
export KUBECONFIG=$HOME/.kube/config
make --debug helm-install-nsm 
11. git clone https://github.com/networkservicemesh/examples.git
12. make k8s-build
13. kubectl create -f examples/examples/bridge-domain/k8s/bridge-service.yaml 
14. kubectl create -f examples/examples/bridge-domain/k8s/bridge.yaml.  # replace namespace to nsm-system
15. kubectl create -f examples/examples/bridge-domain/k8s/simple-client.yaml  # replace namespace to nsm-system

## Context

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Docker:
Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

## Failure Logs

NSMGR pod, all containers, sequence of events: create service, create nse, create nsc:
Actual host machine address replaced with (host-ip-address)
[Nsmgr-bridge-nsc.log](https://github.com/networkservicemesh/networkservicemesh/files/5334369/Nsmgr-bridge-nsc.log)

simple-client pod, all contaienrs:
[Bridge-nsc.log](https://github.com/networkservicemesh/networkservicemesh/files/5334320/Bridge-nsc.log)

bridge-nse pod:
[Bridge-nse.log](https://github.com/networkservicemesh/networkservicemesh/files/5334342/Bridge-nse.log)

**Comment by U24543426** [comment]
As in the attached NSMgr log snippets, in the working ICMP-RESPONDER case, the forwarder request is going out as 

  ` type : KERNEL_INTERFACE` 

and in the failing BRIDGE-DOMAIN example, the forwarder request is showing up as 

   `type : MEMIF `

[Forwarder-request-failure-with-bridge.log](https://github.com/networkservicemesh/networkservicemesh/files/5348651/Forwarder-request-failure-with-bridge.log)

[Forwarder-request-success-with-icmp-responder.log](https://github.com/networkservicemesh/networkservicemesh/files/5348653/Forwarder-request-success-with-icmp-responder.log)

**Comment by U24543426** [comment]
In the working case (icmp-responder) source conn KERNEL_INTERFACE, destination conn KERNEL_INTERFACE
In the failure case (bridge example) source conn KERNEL_INTERFACE, destination conn MEMIF

**Comment by U24543426** [comment]
The bridge-domain example works when the forwarder plane is vpp (instead of kernel)
However, the ping latency is about 25x higher with vpp vs kernel forwarder
kernel: icmp-client to icmp-enpoint ~0.08 ms
vpp: simple-client to simple-client (via bridge) ~4.0 ms
(bridge does not ping, take twice the icmp measure)

It is unfortunate that we cannot figure out why the simple client would not come up with the kernel forwarder

**Comment by edwarnicke** [comment]
@U24543426 I believe the reason is that the bridge domain NSE is only offering the 'memif' mechanism, but the kernel forwarder does not support that mechanism.

As to the latency, part of what you are seeing there is that, to reduce CPU consumption, since many folks are running in a kind env on their laptop, in the 'examples' we've intentionally tweeked the [poll-sleep-usec](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/vpp/startup.conf#L8) in vpp to an unreasonably high number.  VPP has since developed a more sophisticated approach to adaptive polling that we are planning to adopt.

If you would like to try without the suppressing poll-sleep-usec you could delete that line:

1. In the [forwarder](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/vpp/startup.conf#L8)2. 
2. In the [bridge-domain](https://github.com/networkservicemesh/examples/blob/master/examples/bridge-domain/bridge/etc/vpp/vpp.conf#L8)

And give it a go.

**Comment by edwarnicke** [comment]
Additionally: thank you for your extremely well written and detailed issue report.  I kept finding myself having a question, scrolling up, and finding the answer :)

**Comment by U24543426** [comment]
Thanks Ed, this was quite helpful.
Bilgehan

**Comment by U24543426** [comment]
You guys are going a great job by the way, thank you!
