### ISSUE TITLE
Supporting Minikube, on Windows 10 (against Virtualbox)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [networkservicemesh/networkservicemesh#2207]
In addition to supporting Windows 10: I am experiencing various issues, which disallows me to use Windows 10 ports of kubectl/minikube/docker, for running containers inside a guest VM.

I guess that Virtualbox, VMWare Player could be of help.

Nevertheless it is not clear how to build a Linux oriented k8s operator, from within Windows 10 (I am using MinGW bash).
I was able to build an operator - but it is not clear how would it run, since a Windows executable is generated.
Something wrong is happening.

**Comment by edwarnicke** [comment]
@advancedwebdeveloper I'm a little confused how this is related to Network Service Mesh, could you say a bit more?
