### ISSUE TITLE
Getting started with NSM

### ISSUE THREAD

**Issue by abhiranjeet** [networkservicemesh/networkservicemesh#2209]
I have created a kubernetes cluster using 2 VMs (1 Master & 1 Worker) and installed NSM on my cluster 
(referred this link : https://github.com/networkservicemesh/networkservicemesh/blob/master/docs/guide-quickstart.md). 

However, I want to know how can I include NSM components in a helm chart for a microservice I plan to deploy on my cluster. Also it would be awesome if you could refer me to a demonstration of 5 examples mentioned in this link : https://networkservicemesh.io/docs/concepts/what-is-nsm

Thanks !

**Comment by edwarnicke** [comment]
@abhiranjeet Is this the one you are looking for: https://github.com/networkservicemesh/examples/tree/master/examples/bridge-domain ?
