### ISSUE TITLE
Spec: VxLAN Port mapping

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/networkservicemesh#2217]
Currently, the VPP VxLAN protocol has the ability to use only the default udp-port. It is proposed to make it possible to use other ports as well.
The document below describes the problem and possible solutions:
[Link](https://docs.google.com/document/d/1BSYdKpzZrH_rgxg6woFGWG50XjVU2q_GEGMulNziGXk)

New ideas are welcome

**Comment by denis-tingajkin** [comment]
@edwarnicke, @fkautz Could you take a look?

**Comment by glazychev-art** [comment]
There is a patch for vpp repository:
https://gerrit.fd.io/r/c/vpp/+/30204

**Comment by glazychev-art** [comment]
https://gerrit.fd.io/r/c/vpp/+/30204 was merged

The patch for vxlan-gpe:
https://gerrit.fd.io/r/c/vpp/+/31170

**Comment by glazychev-art** [comment]
Closed due to https://gerrit.fd.io/r/c/vpp/+/30204 was merged.

The separate task for VxLAN-GPE was created:
https://github.com/networkservicemesh/sdk-vpp/issues/150
