### ISSUE TITLE
Configure VPP buffers-per-numa

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/networkservicemesh#2218]
## Overview

Context: https://github.com/networkservicemesh/networkservicemesh/issues/2208#issuecomment-725846209

VPP pre-allocates a certain amount of memory buffers at startup (which is controlled by `buffers-per-numa` option), and these buffers are consumed during interface creation. When the free buffers on vppagent-forwarder run out, connectivity between newly created interfaces is lost. The default amount of buffers is low (see below).

## Statistics

Buffer usage on vpp-agent-forwarder per each NS `Connection`:

| Mechanism                   | Buffers used |
| --------------------------- | -----------: |
| `KERNEL` (tap)             |  256 |
| `KERNEL` (veth)            |    0 |
| `MEMIF` (NSE)              | 1024 |
| `MEMIF` (NSC)              |    0 |
| `MEMIF` direct (same node) |    0 |

E.g. each kernel-to-memif connection on a single node takes 1280=256+1024 buffers on vpp-agent-forwarder. Given that the default buffer number is 8192, we are limited to 6 working kernel-to-memif connections or 16 kernel-to-kernel connections.

Memory usage, bytes per buffer:
* 2304 = 256 + 2048, based on `sh buffers` and [this message](https://lists.fd.io/g/vpp-dev/message/17325).
* 3.5k-4k, based on system/process memory consumption on my machine.

## Proposal

1. **Tune the default configuration.**
   Increase the default value of `buffers-per-numa`.
   Suggestion: `buffers-per-numa 65536`. It takes 256 MB of memory, and let us have 128 kernel-to-kernel connections or 51 kernel-to-memif connections per single node.
2. **User-defined configuration.**
   Provide an environment variable to configure `buffers-per-numa` value without rebuilding `vppagent-forwarder` container.
   * Suggestion 1: provide an option for this particular value.
      Example `VPP_BUFFERS_PER_NUMA=128000`.
      Drawback, assuming we'll introduce more configuration options like this one: additional complexity to the user. The user now have to refer both to the `vpp.conf` documenation and our sdk-vppagent documentation.
   * Suggestion 2: take arbitrary `vpp.conf` fragment and append it to our configuration.
      Example: `ADDITIONAL_VPP_CONFIGURATION="buffers { buffers-per-numa 128000 }"`.
      Advantage: this option lets the user tune an arbitrary `vpp.conf` option, not just `buffers-per-numa`.
2. **Handle errors.**
   New connection request `vppagent-forwareder` should return an error if there are no free buffers.
   The current version of vpp-agent doesn't report an error in this case. See https://github.com/ligato/vpp-agent/issues/1758#issuecomment-730869779.

**Comment by xzfc** [comment]
cc @edwarnicke

**Comment by xzfc** [comment]
Proposals 1 and 2 implementation in multirepo: https://github.com/networkservicemesh/sdk-vppagent/pull/434.

**Comment by edwarnicke** [comment]
I spent a little time conversing with some colleagues about this.

By default, a buffer is 256 bytes + data size (default 2048 bytes) + one cache line (64 bytes) == 2368 bytes

Buffers cannot span page boundaries, so for 4096 byte pages (ie, non-huge pages case) you lose a lot of potential space (1728 bytes).

For this reason, we probably want to configure:

https://github.com/edwarnicke/vpphelper/blob/main/vpp.conf.go#L29-L35

Which is now the default in [vpphelper](https://github.com/edwarnicke/vpphelper) used in [cmd-forwarder-vpp](https://github.com/networkservicemesh/cmd-forwarder-vpp).

WRT setting the config in the cmd... you can just write your conf to /etc/vpp/helper/vpp.conf in the container and it won't get over written by vpphelper.
