### ISSUE TITLE
Support for dualstack interfaces (IPv4 + IPv6 combined)

### ISSUE THREAD

**Issue by johlj** [networkservicemesh/networkservicemesh#2225]
## Overview

Add support for having both (ie. simultaneous) IPv4 and IPv6 addresses on NSM interfaces

The above is the basic requirement,
placeholder for further discussion

**Comment by denis-tingajkin** [comment]
@edwarnicke  Is https://github.com/networkservicemesh/api/pull/47 solves this issue?

**Comment by johlj** [comment]
With the latest updates this looks good :)

Br,
Johan
