### ISSUE TITLE
Insufficient networkservicemesh.io/socket

### ISSUE THREAD

**Issue by younus2019** [networkservicemesh/networkservicemesh#2226]
### Expected Behavior
A succesfull installation of simple NSC and NSE through Helm

### Current Behavior
The icmp-responder-nse pods are pending state due to FailedScheduling - 0/6 nodes are available: 6 Insufficient networkservicemesh.io/socket.

**Steps to Reproduce**
helm install nsm deployments/helm/nsm
helm install endpoint deployments/helm/endpoint
helm install client deployments/helm/client
**Context**
oc version: 
	Client Version: 4.6.4
        Server Version: 4.6.4
        Kubernetes Version: v1.19.0+9f84db3
Helm version: v3.2.1

**Failure Logs**

$ oc get pods -n nsm
NAME                                    READY   STATUS    RESTARTS   AGE
icmp-responder-nsc-955d44889-8tlmh      1/1     Running   0          32s
icmp-responder-nsc-955d44889-mb662      1/1     Running   0          33s
icmp-responder-nsc-955d44889-pdmx6      1/1     Running   0          32s
icmp-responder-nsc-955d44889-zkdrb      1/1     Running   0          32s
icmp-responder-nse-9bfd5666b-dfv4z      0/1     Pending   0          33s
icmp-responder-nse-9bfd5666b-xbk8k      0/1     Pending   0          33s
nsm-admission-webhook-76f79669f-z77v9   1/1     Running   0          5m28s
nsm-operator-7749c56b98-s44tj           1/1     Running   0          15m
nsm-vpp-forwarder-b5b8w                 1/1     Running   0          5m26s
nsm-vpp-forwarder-bl56n                 1/1     Running   0          5m26s
nsm-vpp-forwarder-trst6                 1/1     Running   0          5m26s
nsmgr-g2kw7                             3/3     Running   0          5m26s
nsmgr-hjm8b                             3/3     Running   0          5m26s
nsmgr-vkhbn                             3/3     Running   0          5m26s

$ oc describe pod icmp-responder-nse-9bfd5666b-dfv4z
Name:           icmp-responder-nse-9bfd5666b-dfv4z
Namespace:      nsm
Priority:       0
Node:           <none>
Labels:         networkservicemesh.io/app=icmp-responder
                networkservicemesh.io/impl=icmp-responder
                pod-template-hash=9bfd5666b
Annotations:    openshift.io/scc: restricted
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/icmp-responder-nse-9bfd5666b
Containers:
  icmp-responder-nse:
    Image:      docker.io/networkservicemesh/test-common:v0.2.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/icmp-responder-nse
    Limits:
      networkservicemesh.io/socket:  1
    Requests:
      networkservicemesh.io/socket:  1
    Environment:
      ADVERTISE_NSE_NAME:    icmp-responder
      ADVERTISE_NSE_LABELS:  app=icmp-responder
      TRACER_ENABLED:        true
      IP_ADDRESS:            172.16.1.0/24
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from nse-acc-token-njx8r (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  nse-acc-token-njx8r:
  Type:        Secret (a volume populated by a Secret)
    SecretName:  nse-acc-token-njx8r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  79s   default-scheduler  0/6 nodes are available: 6 Insufficient networkservicemesh.io/socket.
  Warning  FailedScheduling  79s   default-scheduler  0/6 nodes are available: 6 Insufficient networkservicemesh.io/socket.

$ oc get nodes
NAME                                  STATUS   ROLES    AGE    VERSION
nsm-os-cluster-56kbq-master-0         Ready    master   119m   v1.19.0+9f84db3
nsm-os-cluster-56kbq-master-1         Ready    master   119m   v1.19.0+9f84db3
nsm-os-cluster-56kbq-master-2         Ready    master   119m   v1.19.0+9f84db3
nsm-os-cluster-56kbq-worker-b-wkcmr   Ready    worker   109m   v1.19.0+9f84db3
nsm-os-cluster-56kbq-worker-c-v5dm9   Ready    worker   109m   v1.19.0+9f84db3
nsm-os-cluster-56kbq-worker-d-xfkj2   Ready    worker   109m   v1.19.0+9f84db3

Can someone please provide me the reference on how to deploy/install icmp-responder-nse on OpenShift?
thanks in advance,

**Comment by ebucchianeri** [comment]
I have the same problem trying to execute "universal-cnf" example with kind. Any suggestion?
Thank you

```
> kc get po
NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
default              ucnf-client-7f6498f5b5-5xj2n                0/1     Pending   0          12m
default              ucnf-client-7f6498f5b5-6wrlr                0/1     Pending   0          12m
default              ucnf-client-7f6498f5b5-7bkjz                0/1     Pending   0          12m
default              ucnf-client-7f6498f5b5-8f6p5                0/1     Pending   0          12m
default              ucnf-endpoint-5c58bb6577-wml9r              0/1     Pending   0          12m
default              ucnf-endpoint-5c58bb6577-xdmxh              0/1     Pending   0          12m
```


```
> kc describe po ucnf-endpoint-5c58bb6577-wml9r
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  48s (x10 over 12m)  default-scheduler  0/3 nodes are available: 3 Insufficient networkservicemesh.io/socket.
```
