### ISSUE TITLE
NSM breaks under Kubernetes 1.20 

### ISSUE THREAD

**Issue by U24543426** [networkservicemesh/networkservicemesh#2227]
## Expected Behavior

Custom Resource Definition API version upgrade to v1.

## Current Behavior
NSC/NSE connections don't come up.

Kubernetes 1.20 prints a warning about v1beta1 being deprecated in version 1.22+ and asks to switch the definitions to v1. Although it looks like a warning, some things already don't seem to work in 1.20.

## Failure Information (for bugs)
You can see in the nsmdr/nsmd log that nsmgr cannot find the registered service when NSC requests come in.
It can be seen in the nsmgr/(nsmdp?) log that the service registrations are being dropped after successful registration earlier on.

Unfortunately we don't have logs or more information to provide because once we realized that the problems were being caused by k8s version, we quickly switched back to 1.19 and we don't have the failing setup any longer.
## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by edwarnicke** [comment]
Thanks for the report!  We will have a look.

**Comment by denis-tingajkin** [comment]
I feel to fix this we need to re-generate NSM k8s api client to latest version, but  looks like in this case we'll drop older k8s versions.

**Comment by denis-tingaikin** [comment]
@edwarnicke I guess we can try to use the 'fallback' strategy and have two versions of the client. Thoughts?

**Comment by edwarnicke** [comment]
@U24543426 Quick gut check... how urgent is your need to move to 1.20.  Are we blocking you yet?  How long do we have to sort this out before we are?
