### ISSUE TITLE
Nsm-vpp-forwarder issue -Readiness probe failed

### ISSUE THREAD

**Issue by Ieneya** [networkservicemesh/networkservicemesh#2237]
Expected Behavior
A succesfull installation of nsm through Helm

Current Behavior
The nsmgr and nsm-vpp-forwarder pods are not running properly due to Readiness probe failed: HTTP probe failed with statuscode: 503.

I have attached the logs of Nsm-vpp-forwarder  and NSMgr. Kindly see to it.
[vpplog.txt](https://github.com/networkservicemesh/networkservicemesh/files/6146625/vpplog.txt)
[nsmgrlog.txt](https://github.com/networkservicemesh/networkservicemesh/files/6146627/nsmgrlog.txt)

**Comment by edwarnicke** [comment]
```
latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/spire/sockets/agent.sock: connect: no such file or directory\"; retrying in 1.5s"
time="2021-03-16T05:03:02Z" level=info msg="FetchX509SVID failed with rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/spire/sockets/agent.sock: connect: no such file or directory\"; retrying in 2.25s"
```

Are you running spire?  It looks like its trying to find a spire server and not finding it...

**Comment by Ieneya** [comment]
yes , when getting list of pods , i can see in spire namespace , spire agent and spire server are running...

I installed NSM by executing the below commands
```
helm repo add nsm https://helm.nsm.dev/ # Add the latest release nsm helm repo
helm install nsm/nsm # Install the nsm infrastructure in your Kubernetes Cluster
```
To be added , in VMware vSphere also I am getting the same issue .

**Comment by edwarnicke** [comment]
And this is on OpenShift, correct?

**Comment by Ieneya** [comment]
Now, Anthos Clusters on AWS in GCP environment is in use . The guide which I followed is per the below attached link
[https://cloud.google.com/anthos/clusters/docs/aws/how-to](url)

Context:
anthos-gke version : aws-1.6.2-gke.0
terraform version : v0.12.28
gitVersion: v1.20.4

To be noted , in standalone GCP environment and in standalone AWS environment , NSM is working fine.

**Comment by edwarnicke** [comment]
@Ieneya Here's a spire solution on OpenShift:

https://github.com/spiffe/spire/pull/2181

I wonder if something similar would help with the Anthos Cluster on AWS in GCP environment.
