### ISSUE TITLE
CrossConnect update infinite loop in nsmd per connection

### ISSUE THREAD

**Issue by tiswanso** [networkservicemesh/networkservicemesh#2241]
## Expected Behavior

The connection should complete and not cause an infinite crossconnect update notification loop.

## Current Behavior

This is on a fork with a few changes on the mono-repo latest HEAD as of March 26, 2021:
I can see in jaeger and in nsmd logs each connection is showing the completion of the ProgramForwarder results in CrossConnect-send-update and the end result is a CrossConnect update loop that goes on forever.  

## Failure Information (for bugs)

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/3629949/112662779-76efd100-8e2e-11eb-9a58-9b984993414b.png">

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/3629949/112663082-cdf5a600-8e2e-11eb-9de2-fa8a27d11fe5.png">

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/3629949/112663287-05fce900-8e2f-11eb-8c10-61f0d1df0c0f.png">

## Steps to Reproduce

1. Install NSM on k8s (e.g. KinD or EKS)
2. Bringup an NSE
3. Bring up a NSC for that NSE to cause a connection
4. Check Jaeger for NetworkServiceRequest spans

## Context

* Kubernetes Version:
* etc.

**Comment by tiswanso** [comment]
Likely due to this, we're seeing update channel sizes maxed after about 10 connections, which correspond with:
DefaultSize here: https://github.com/networkservicemesh/networkservicemesh/blob/6fb890e00e22e098e82ca81e78636b4f60d8ff4c/sdk/monitor/monitor_server.go#L13-L54
This channel aswell: https://github.com/networkservicemesh/networkservicemesh/blob/13585604d21d4229c59f41f8099591d9829e10cb/forwarder/pkg/common/monitor_netnsinode_server.go#L53

Gathering more detailed info but this seems to lead to deadlock/no-service between the forwarder & nsmd.

**Comment by edwarnicke** [comment]
@haiodo This looks like it may be heal related ... could you also have a look?

**Comment by haiodo** [comment]
Hi @tiswanso , 
If you have a logs from nsmgr and could export jaeger traces and attach to issue, it would be nice.

**Comment by tiswanso** [comment]
> Hi @tiswanso ,
> If you have a logs from nsmgr and could export jaeger traces and attach to issue, it would be nice.

Ok...I will add logs from a smaller repro.  I'm seeing this on every client connection so it should be very easy to reproduce in any env.  It would be good info to know if it's not!

**Comment by tiswanso** [comment]
Uploaded nsmgr and nsm-vpp-forwarder logs and exported json trace of an NS request that is in the infinite loop
https://drive.google.com/drive/folders/1wG824KNneRkNzOixchQJDcqe6v9l82NU?usp=sharing

**Comment by haiodo** [comment]
It is related to MetricsCollector sending update every 2seconds. 
It configured per vpp router METRICS_COLLECTOR_REQUEST_PERIOD.
But there is no metrics attached to cross connect event, so it looks useless. Still checking why it is so.

**Comment by edwarnicke** [comment]
@haiodo Any updates?

**Comment by tiswanso** [comment]
I am now testing with the nsm-vpp-forwarder env var:
```
METRICS_COLLECTOR_ENABLED: false
```

Will update more as we get further but the initial symptom of the Jaeger trace showing the infinite update loop in nsmd on client connections seems cleared up.

**Comment by narcolepticsnowman** [comment]
We end up seeing those messages run much more frequently than every two seconds. 
It appears related to these two lines:
https://wwwin-github.cisco.com/cisco-app-networking/networkservicemesh/blob/vl3_latest/sdk/monitor/monitor_server.go#L126
and
https://github.com/networkservicemesh/networkservicemesh/blob/756a5e48592b29174765657cf3a4cb79c3491240/controlplane/pkg/nsmd/nsmd_crossconnect_client.go#L396

each side is immediately sending a new event to each other side.

**Comment by narcolepticsnowman** [comment]
Ah, it's not sending to both sides, the monitor_server is reading the events into a map here:

https://github.com/networkservicemesh/networkservicemesh/blob/756a5e48592b29174765657cf3a4cb79c3491240/forwarder/pkg/common/monitor_netnsinode_server.go#L162

So.... probably not that...

**Comment by edwarnicke** [comment]
@denis-tingaikin Any further updates on this?
