### ISSUE TITLE
CI tests fail on Azure

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/networkservicemesh#2243]
## Expected Behavior

Integration tests should be passed

## Current Behavior

Integration tests fail due to an error at the Azure startup

## Failure Information (for bugs)
```
Cluster start failed azure-1
Error: failed to run make azure-start ExitCode: 2
start: make azure-start
...
done
Waiting for deploy to complete...
done
Creating Inbound traffic rule
ERROR: argument --name/-n: expected one argument
```

## Steps to Reproduce

1. Create a PR
2. Look at CI tests

**Comment by edwarnicke** [comment]
I've updated the expired Azure token.
