### ISSUE TITLE
Tutorial NSM + Multus

### ISSUE THREAD

**Issue by g-rabah** [networkservicemesh/networkservicemesh#2247]
hi evryone, 

i am new to NSM. The learning curve is very steep and no end to end resources can be found

For my use case :  one master and two worker nodes i want to use Multus and NSM with ligato to build multiple overlays between different types of pods using VxLAN. 

can someone provide me with a good tutorial(s) ? or study guide. 

Thanks in advances

**Comment by denis-tingaikin** [comment]
Also be free to join to our NSM meetings tomorrow https://github.com/networkservicemesh/networkservicemesh#get-involved

**Comment by edwarnicke** [comment]
@g-rabah Question... what are you trying to accomplish using Multus?  You should be able to do what you are suggesting with just NSM (though your complaints about documentation there are completely valid... I just want to get a sense of what you are trying to get at so we can get you the best answer... and not sure why you would need Multus is you have NSM :) )
