### ISSUE TITLE
make aws-start error

### ISSUE THREAD

**Issue by younus2019** [networkservicemesh/networkservicemesh#2249]
**I am working on Public Cloud Setup.** 
While running **"make aws-start"** command to start AWS cluster and setup firewall rules.
**I am getting Below error:**

[cloudshell-user@ip-10-0-124-119 networkservicemesh]$ make aws-start
~/multi_check/networkservicemesh/scripts/aws ~/multi_check/networkservicemesh
2021/05/06 04:32:49 Creating EKS service role "nsm-role"...
2021/05/06 04:32:50 Role "nsm-role"(arn:aws:iam::112327498748:role/nsm-role) successfully created!
2021/05/06 04:32:50 Creating Amazon EKS Cluster VPC "nsm-srv"...
2021/05/06 04:34:12 Cluster VPC "nsm-srv" successfully created!
2021/05/06 04:34:12 Creating Amazon EKS Cluster "nsm"...
2021/05/06 04:44:35 EKS Cluster "nsm" successfully created!
2021/05/06 04:44:35 Updated context arn:aws:eks:ap-northeast-1:112327498748:cluster/nsm in /home/cloudshell-user/.kube/config
2021/05/06 04:44:35 Creating Amazon EC2 key pair "nsm-key-pair"...
2021/05/06 04:44:35 Amazon EC2 key pair "nsm-key-pair" successfully created!
2021/05/06 04:44:35 Creating Amazon EKS Worker Nodes on cluster "nsm"...

2021/05/06 04:44:40 Error: Unexpected stack status: CREATE_FAILED
exit status 1
make: *** [aws-start] Error 1
[cloudshell-user@ip-10-0-124-119 networkservicemesh]$ 

**note:** for GCP I am able to create cluster using "make gke-start" command. but AWS I am facing issue.

**Comment by denis-tingaikin** [comment]
@glazychev-art Could you have a look?
