### ISSUE TITLE
X-Factor CNFs - Define guidance similar to 12-factor app heuristics.

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#227]

**Comment by lixuna** [comment]
Reference: https://12factor.net/

**Comment by lixuna** [comment]
Notes: 

- outcome: to prepare a draft for Cloud Native Network Functions Seminar at OSS - Tuesday, August 28
- goal: to define how to build scalable Network Functions
- not limited to "12" because we may need to define more or fewer factors

**Comment by lixuna** [comment]
Notes: 

- first 12 will be rewritten with cloud native terminology
