### ISSUE TITLE
NSM CI in AWS

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#318]
[Cross Cloud-CI](https://github.com/crosscloudci/cross-cloud#quick-start-for-aws) runs on AWS.  As an extention of #316 it would be nice to get it running in AWS as well.

**Comment by edwarnicke** [comment]
Pointers on adding AWS to the Makefile machinery.

The Makefile machinery for NSM is designed to allow you to build/run NSM in different environments, including public cloud.  By default, its setup for local vagrant, but other environments may be selected by using three env variables:

1. CLUSTER_RULES_PREFIX -  selects which sets of rules to use to create/destroy/interact with the cluster.  Example: CLUSTER_RULES_PREFIX=vagrant
2. CONTAINER_BUILD_PREFIX - selects which sets of rules to use to build containers.  Example: CONTAINER_BUILD_PREFIX=docker
3. CONTAINER_REPO - selects which container repo to use for the containers you are building/deploying.  Example CONTAINER_REPO=networkservicemesh

The [.env directory](https://github.com/networkservicemesh/networkservicemesh/tree/master/.env) contains helpful files you can source into your shell to set those env variables for various platforms, for example [vagrant](https://github.com/networkservicemesh/networkservicemesh/blob/master/.env/vagrant.env) or [gke](https://github.com/networkservicemesh/networkservicemesh/blob/master/.env/gke.env)

These env variables get used in various rules in [.mk/k8s.mk](https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/k8s.mk).  They are imported from files like [.env/gcb.mk](https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/gcb.mk) and [.mk/gke.mk](https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/gke.mk).  To add aws you to the make machiner you will need to have:

1.  Something that can build the images and put them where AWS can easily get at them (see  [.env/gcb.mk](https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/gcb.mk) for how we id that for GKE)
2. Something that can start/destroy a cluster and make sure kubectl is pointing at it for the other make rules (see [.mk/gke.mk](https://github.com/networkservicemesh/networkservicemesh/blob/master/.mk/gke.mk) for an example).

**Comment by artem-belov** [comment]
Remote tests are all failed.
Routes on pods looks weird 
NSC interfaces and routes:
```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if57: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9001 qdisc noqueue state UP 
    link/ether fa:48:dd:05:59:11 brd ff:ff:ff:ff:ff:ff
    inet 192.168.117.135/32 brd 192.168.117.135 scope global eth0
       valid_lft forever preferred_lft forever
4: nsm0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
    link/ether 3e:26:7e:38:fe:b5 brd ff:ff:ff:ff:ff:ff
    inet 10.20.1.1/30 brd 10.20.1.3 scope global nsm0
       valid_lft forever preferred_lft forever
/ # ip route
default via 169.254.1.1 dev eth0 
8.8.8.8/30 dev nsm0 scope link 
10.20.1.0/30 dev nsm0 scope link  src 10.20.1.1 
169.254.1.1 dev eth0 scope link 
```
nsmd-dataplane interfaces and routes:
```
root@nsmd-dataplane-ip-192-168-123-27:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if55: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
    link/ether 9e:7d:dc:0f:e8:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.124.118/32 brd 192.168.124.118 scope global eth0
       valid_lft forever preferred_lft forever
root@nsmd-dataplane-ip-192-168-123-27:~# ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
```
nsmd-dataplane vpp configuration
```
vpp# show ip fib
ipv4-VRF:0, fib_index:0, flow hash:[src dst sport dport proto ] locks:[src:plugin-hi:2, src:default-route:1, ]
0.0.0.0/0
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:1 buckets:1 uRPF:7 to:[0:0]]
    [0] [@3]: arp-ipv4: via 169.254.1.1 host-eth0
0.0.0.0/32
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:2 buckets:1 uRPF:1 to:[0:0]]
    [0] [@0]: dpo-drop ip4
192.168.124.118/32
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:9 buckets:1 uRPF:8 to:[0:0]]
    [0] [@2]: dpo-receive: 192.168.124.118 on host-eth0
192.168.170.79/32
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:10 buckets:1 uRPF:7 to:[0:0]]
    [0] [@3]: arp-ipv4: via 169.254.1.1 host-eth0
224.0.0.0/4
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:4 buckets:1 uRPF:3 to:[0:0]]
    [0] [@0]: dpo-drop ip4
240.0.0.0/4
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:3 buckets:1 uRPF:2 to:[0:0]]
    [0] [@0]: dpo-drop ip4
255.255.255.255/32
  unicast-ip4-chain
  [@0]: dpo-load-balance: [proto:ip4 index:5 buckets:1 uRPF:4 to:[0:0]]
    [0] [@0]: dpo-drop ip4
vpp# show int 
              Name               Idx    State  MTU (L3/IP4/IP6/MPLS)     Counter          Count     
host-SRC-1-veth                   3      up          9000/0/0/0     rx packets                     6
                                                                    rx bytes                     252
                                                                    drops                          6
host-eth0                         1      up          9000/0/0/0     rx packets                     5
                                                                    rx bytes                     350
                                                                    tx packets                     6
                                                                    tx bytes                     252
                                                                    drops                          5
                                                                    ip6                            5
local0                            0     down          0/0/0/0       
vxlan_tunnel0                     2      up           0/0/0/0       tx packets                     6
                                                                    tx bytes                     468
vpp# show int addr
host-SRC-1-veth (up):
  L2 xconnect vxlan_tunnel0
host-eth0 (up):
  L3 192.168.124.118/32
local0 (dn):
vxlan_tunnel0 (up):
  L2 xconnect host-SRC-1-veth
vpp# 

```
Vpp Trace is empty after ping command from nsc

**Comment by edwarnicke** [comment]
Could you get me
``` ip neigh```
on the nsmd-dataplane Pod?

**Comment by artem-belov** [comment]
```
root@nsmd-dataplane-ip-192-168-123-27:~#  ip neigh
169.254.1.1 dev eth0 lladdr a2:98:59:e5:8b:28 PERMANENT

```

**Comment by edwarnicke** [comment]
@artem-belov OK... here's what's happening in AWS:

They are assigning a /32 to their eth0.
They are setting up a default route to a link local IP address 169.254.1.1
They are pinning up a permanent neighbor entry for that link local address.

My guess is that if you look at our routing code for mgmt interfaces, its not handling this approach.

My guess is that the reason why is because we aren't doing the equivalent of the static arp table entry.

You should be able to test this manually with:

https://docs.fd.io/vpp/19.04/clicmd_src_vnet_ethernet.html#clicmd_set_ip_arp

If that works, the relavent API for vpp-agent appears to be:

https://github.com/ligato/vpp-agent/blob/master/api/models/vpp/l3/arp.proto

**Comment by nickolaev** [comment]
#987 merged. Closing.
