### ISSUE TITLE
Set up Packet.net for NSM Demo backend

### ISSUE THREAD

**Issue by lixuna** [networkservicemesh/networkservicemesh#414]
Tasks:

- [ ] Document requirements for packet.net environment
- [ ]

**Comment by taylor** [comment]
@fkautz, @edwarnicke, what are the requirements for the demo including how many systems, type of network between nodes, specific hardware (eg. Intel vs Mellanox NICs).

Ideally we can identify what is a hard requirement vs nice to have.  For example Packet.net has lots of dual port mellanox NICs in systems that we can use immediately.
