### ISSUE TITLE
Walkthrough of how ICMP NSM was created

### ISSUE THREAD

**Issue by iawells** [networkservicemesh/networkservicemesh#463]
The ICMP responder example is about as simple an NSM as you can get.  Can we also write some documentation about how it's written, as an example to others about how they might write their own network services?

**Comment by edwarnicke** [comment]
:+1:

**Comment by nickolaev** [comment]
The SDK has a simple [README]( https://github.com/ligato/networkservicemesh/blob/master/sdk/README.md) that describes the basics of creating an Endpoint. That should mostly cover this issue.
I propose to close @edwarnicke.
