### ISSUE TITLE
Validate "namespace", "inline", and "omitempty" in CRD schemas

### ISSUE THREAD

**Issue by mestery** [networkservicemesh/networkservicemesh#58]
Namespaces were removed from the CRD schemas before #54 merged, and omitempty and inline were left intact. Explore if we need any of these or not post merge of #54.

**Comment by nickolaev** [comment]
@ivanayov can you please check if this comment is still relevant or we can close it?
Note that the code is quite old and probbaly hs nothing to do with whatever we have today, though.

**Comment by ivanayov** [comment]
This seems outdated now
