### ISSUE TITLE
Issues with startup instructions on NSM website

### ISSUE THREAD

**Issue by iawells** [networkservicemesh/networkservicemesh#609]
https://www.networkservicemesh.io/docs/setup/quick-start/

make k8s-build requires Go.  I don't know why, since it builds in a container, but it fails out if go is not present on the system.  If it's a requirement it should be listed in the instructions.

It's copying in 60MB of file to build every container, which seems a bit wacky; a base image would make more sense.

The recommended deployment uses vagrant with bento/ubuntu-18.04; fine, but it doesn't support the libvirt provider, and there's no mention of that.

**Comment by matrohon** [comment]
Concerning a libvirt compatible image, you can use #577

**Comment by nickolaev** [comment]
@iawells the observation about the non-optimal build process is correct. I have already proposed to split the core NSM components from examples and optimize the build infrsatructure which now has all kinds of handy targets.
I'm not sure what you mean by "base image". would that be "a base build image" so we don't do crazy copies all the time.

I believe here we have much better build instructions: https://github.com/ligato/networkservicemesh/blob/master/docs/BUILD.md

**Comment by nickolaev** [comment]
Added #610 to describe briefly my proposal.

**Comment by nickolaev** [comment]
I believe most of the concerns here are addressed already.
@edwarnicke shall we close this one?

**Comment by edwarnicke** [comment]
@iawells Do you feel like your concerns are addressed?
