### ISSUE TITLE
Split the repo to core NSM and examples

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#610]
In its current state the NSM repo contains at least these components:
 * the controlplane code
 * the vppagent dataplane glue code
 * examples
 * vagrant deployment scripts
 * Packet CI/CD deployment and test scripts
 * a rather complex build and deploy Makefile machinery

The proposal here is to split the repo to at least these 2:

 * everything that deplys today with `make k8s-infra-deploy`
 * all the rest - including examples, vagrant, CI/CD etc.

This way we can maintain the core development independent. Release docker images for point versions and latest/nightly. This, of course, would require rethinking the testing procedures, include more Unit tests etc.

**Comment by nickolaev** [comment]
I think that the core should be kept as simple as possible - i.e. nothing more then a way to build Docker images. All deplyment, vagrant setups, CI/CD should be in the other repo.

**Comment by matrohon** [comment]
I'm not sure about that. It's always more comfortable to have a single repo containing all the materials of the project, and not having to change to another repo just to manipulate and test new examples for instance.

**Comment by nickolaev** [comment]
@haiodo, #611 already proposes my thoughts around the SDK, so that's something that I believe we'll do.

**Comment by edwarnicke** [comment]
@nickolaev So I think you would be suggesting that we split out the SDK.  Generally I like the idea, but I think it sort of ends up being a bit of a circular repo dependency at this time if the examples stay in the main repo:

SDK depends on main repo, examples in main repo depends on SDK.

Note: I'm not arguing against a split here... just talking through the things we'd need to work out.

**Comment by nickolaev** [comment]
@edwarnicke actually I propose to have all NSCs and NSEs separated in the examples repo. i.e. the main repo should have the SDK too.
I understand that currently the CI that validates NSM is based on the examples being operational. The question is, is that what we want? I mean examples are just that - examples. IMHO the NSM integration should pass through dedicated tests which describe different test scenarios etc.

Note also that we have all this complex machinery that builds vagrant, deploys kubernetes etc. I somehow feel that this should not live in the main repo. Building the relevant Docker images for NSM shoudl be enough to live there.

I understand we'll need a longer discussion, but that is the purpose of the issue here.

**Comment by edwarnicke** [comment]
@nickolaev OK, that makes more sense :)

I think part of why we arrived were we are is that examples were built specifically to test certain aspects of the system.  I'm OK for looking at ways we can do so without necessarily having all the examples in repo.

It also is a good idea to think about how certain things would shift.

Say for example we do CI from examples built in a different repo, and deployed to docker hub (totally doable).  What would the procedure be if we discover for example we need to update the local.NetworkService API?  My guess is that we are solid enough that we can manage from  the tools protobuf gives us (or will be that solid shortly).  But its worth thinking through.

**Comment by iawells** [comment]
If we're going to split, I would suggest that actual working dataplane and network service code should separate from the main repo.  The main repo should contain the main code, the SDK that allows you to make those things (which we may at packaging time keep separate) and stuff to run those services.  The dataplane examples should contain code to install and run them in a running NSM, and something like a devstack plugin that would allow them to be run as part of a full NSM deployment.

Separating the SDK and NSM is probably not wise at this point since the two are going to be lockstep-versioned for now until we get through dev, and separating deployment from code is just going to make development harder along with having that same lockstep problem.

**Comment by edwarnicke** [comment]
## nsmd restarts

When an nsmd starts (or restarts) it currently waits for a Dataplane to Register.
Once the Dataplane has registered:

1. nsmd calls MonitorCrossConnects on Dataplane, and learns the set of all CrossConnects the Dataplane has.  
2. From the CrossConnects, nsmd can learn all of the CrossConnect.RemoteSource() and CrossConnect.RemoteDestinations().  Each of those are remote.Connections, and container the remote nsmd name, network service name, etc.
3. From that the nsmd can establish a new remote.MonitorConnection to each peer nsmd, learning what connections that peer believes itself to have with the nsmd.
4. from the CrossConnects, nsmd can learn all of the CrossConnect.LocalDestination() and thus the workspace.
5.  From the Workspace the nsmd can attempt to call local.MonitorConnections() on each workspace to get local NSE's opinions about their Connections. 

### Reconciling remotePeers
So for each remotePeers, the nsmd now has two views of reality: the remotePeer's, andthe Dataplane's.

These need to be reconciled.  The basic priniciples of reconciliation are:

1. If the Dataplane has a CrossConnect with a RemoteDestination() that is unknown to the remotePeers, first attempt to Request() the Connection learned from the Dataplane.  If that fails, carry out the autohealing procedure.
2. If the Datplane has a CrossConnect with a RemoteSource() that is unknown to the remotePeers, Close the Connection with the local NSE and Close the CrossConnect with the Dataplane
3. If the remotePeers has a Connection with the nsmd for which the nsmd is listed as the source nsmd the Connection is unknown to the Dataplane, send Close(Connection) to the remotePeers for those Connections


### Reconciling localPeers

For each localPeer, the nsmd now has two views of reality: the localPeer's, and the Dataplane's.

These need to be reconciled.  The basic principles of reconciliation are:

1.  If the Dataplane has a CrossConnect with a LocalDestination() that is unknown to the local NSE, Request() that local.Connection to the local NSE.
2. If the localPeer has a Connection that is unknown to the Dataplane, Close() the Connection with the local NSE.

**Comment by nickolaev** [comment]
Closing as the examples repo is alive now:
https://github.com/networkservicemesh/examples
