### ISSUE TITLE
Telemetry on Network Service Mesh

### ISSUE THREAD

**Issue by quangtamle** [networkservicemesh/networkservicemesh#621]
Hello everyone,

I work on a project about Telemetry on Network Service Mesh but I can not find any document about this topic. All I can find is Telemetry on Service Mesh from Istio community and I am wondering whether Telemetry on Istio architecture can be applied into Telemetry on Network Service Mesh.

Are there anyone have experienced about this topic ??? May you share with me some ideas or document about this topic ???

Thank you in advance

**Comment by matrohon** [comment]
Hi @quangtamle 

Can you describe what kind of metrics you expect?
for now, each nsmd (and dataplanes) reports about cross connections status, through a grpc stream. This is what skydive is using to display connections between nsm clients and endpoints.
I was planning to get more informations about number of packets for each connection by developing a vpp probe in skydive. But if we do so, those infos would be available through the skydive API not the nsm one.
Is this acceptable for you?

**Comment by quangtamle** [comment]
Hi @matrohon 
The kind of metrics i need are bandwidth between those connections (which i can see it on skydive), number of packets (sent, received, drop), delay, jiter...

Could you teach me how to develop a tool to get those info ? because right now i am learning about NSM and i need to learn as much as i can

Thank you in advance

**Comment by matrohon** [comment]
monitoring this kind of metrics is totally the scope of a tool such as skydive, as soon as skydive as a probe compatible with the dataplane in use by NSM (for now, vpp only AFAIK).

I don't know if NSM wants to do the monitoring by itself. @edwarnicke @fkautz @nickolaev do you have an opinion?

It could be done by expanding the current [Monitoring](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/crossconnect/crossconnect.proto) interface so that it sends statistics periodically.

@lobkovilya  recently introduced a monitoring of netns inodes to delete cross connects when netns are deleted. The same could be done to periodically gather metrics of interfaces concerned by nsm connections.

**Comment by edwarnicke** [comment]
@quangtamle @matrohon I think NSM would like to report out 'metrics' with its MonitorCrossConnectEvents, exactly as @matrohon suggests.  Its just one of those things we hadn't gotten to yet :)

@quangtamle It sounds like you are wanting traditional interface count kinds of things on each connection (or rather, each *end* of each connection), some latency metrics, jiter etc.  All super good things.

We also have some interesting additional possibilities by bringing in iOAM in some cases.  iOAM does lots of cool tracing, round trip latency, etc monitoring we could take advantage of.

We do have some tricky corners.  Example: If we have a NSC connected to an NSE via direct memif... we literally are not in the path of the traffic anymore, and thus we can't see things like counters etc... because its all directly over shared memory we are not part of.  But for anything cross connecting via vpp, we have *lots* of stats.

@quangtamle Did you have some thoughts for how to compute latency, jitter etc?

**Comment by edwarnicke** [comment]
More data on iOAM: https://github.com/CiscoDevNet/iOAM

**Comment by quangtamle** [comment]
Hi @matrohon @edwarnicke 

Thank you so much for your ideas !

I think that about latency, we can set a threshold (for example: 200ms), if the transmitted time > threshold, it get delayed. About Jiter, we can take the average of the transmitted time of all the packets.

Btw, i have some questions about skydive. Where is skydive stores all the metrics ??? is there any database (i.e. influxdb...) to store all the events and those metrics (just in case the operators want to check the behaviors of this network)

Thank you in advance

**Comment by matrohon** [comment]
@quangtamle skydive can use different storage backends (memory, elasticsearch, orientdb), to store the graph and metrics of each node. It also monitors flows, and store per flows metrics in a storage backend too.

**Comment by matrohon** [comment]
@quangtamle the skydive currently deployed with the NSM makefile machinery is using a [memory](https://github.com/ligato/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L31) storage backend.

**Comment by quangtamle** [comment]
Dear @matrohon @edwarnicke ,
As you said, the skydive currently uses a memory for starage backend. Could you specify what kind of memory resoures ??? is it RAM or hard disks ???
The skydive is used for telemetry purposes then do they need a large memory (DB) to store information in the long run ??? For instance, we need to check some information in the past to study the behavior of the services or troubleshooting the causes of the service's events
Thank you in advances !!!
Have a nice day !!!

**Comment by quangtamle** [comment]
Dear @matrohon @edwarnicke  ,

As you said, the skydive currently uses a memory for storage backend. Could you specify what kind of memory resources ??? is it RAM or hard disks ???
The skydive is used for telemetry purposes then do they need a large memory (DB) to store information in the long run ??? For instance, we need to check some information in the past to study the behavior of the services or troubleshooting the causes of the service's events.

Thank you in advances !!!
Have a nice day !!!

**Comment by edwarnicke** [comment]
@quangtamle Sounds like you are looking for time series topology... which is a concept dear to my heart :)

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Yes, That is what I am looking for. That's why I want to know what kind of memory resources that skydive uses in the context of NSM. Is it RAM or hard disks???

By the way, for the time series topology, How will skydive currently handle this for NSM ???

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle That's probably more of a conversation for the skydive team... I an tell you that the NSM calls skydive is calling are designed to stream data, so you could easily back them with a time series topology system... but I'm not clear on what the skydive teams plans are for time-series.

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Sorry for my inappropriate question, but what about Prometheus ??? because I see on the official website, it also mention time series topology and Istio also use Prometheus in Mixer. If it is inappropriate please forgive me !!! I didnt mean that.

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle Totally appropriate question.  Prometheus is certainly another possibility.  Does it understand topologies?

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Yes, you're right, as far as I know, prometheus can not show the topologies.
By the way, could you tell me what is the [memory](https://github.com/ligato/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L31) used in NSM ???

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle docker stats seems to indicate that:

1.  The nsmd Pod is uses about 15m of ram
2.  The vppagent-dataplane Pod uses about 50m of ram
3.  vppagent based NSEs use about 50m of ram

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

In my opinion, i think this amount of RAM are used to run the skydive service, am I right ??? because with that amount of RAM, i dont think it can store much information.

In order to use "time-series" feature, i think NSM need to have large enough DB to store all the information. Then where NSM store those information ??? 
because from the issue #502 , @matrohon he mention about this DB but not clear so I want to ask more detail about this DB.

"It also optionally send this global graph to a storage backend (typically elasticsearch)".

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle nsmd doesn't keep historical data, it just streams out information as state changes, so it shouldn't consume huge amounts of new memory over time.  Obviously, something we are streaming to as a time series database would need to be able to store the full size of history.

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

The first point I totally understand and agree.

In the second point, "a time series database" where is this DB in the NSM ??? and currently Is there any DB like this in NSM architecture ???

Thank you so much !!!

**Comment by edwarnicke** [comment]
@quangtamle We don't currently have a time series DB... interested in hooking us up to one?

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Thank you so much, I love to

**Comment by quangtamle** [comment]
Dear @edwarnicke @matrohon ,

Could you help me to explain
1. What is the purpose of the Jaeger in NSM ?
2. What does Jaeger monitor and analyze ?
3. Jaeger is another tool supporting for monitoring besides Skydive ?
4. How does it work ? because I see only one Jaeger pods deployed on kube worker

Thank you in advances

**Comment by nickolaev** [comment]
@quangtamle Let me try to answer these to the best of my knowledge:

1. The purpose of Jaeger is to provide better visibility and traceability in the operation of the NSM based infrastructure. This includes the NSMD and Dataplane but is also embedded in our SDK so all NS Clients (NSC) and NS Endpoints (NSE).

2. TOdday Jaeger monitors the gRCP calls between the said components, allowing for visually comprehensive tracing. For example, one can trace how the NS Client's Request gets propagated through the involved NSMDs, Dataplanes and the connecting NS Endpoint.

3. Skydive visually represents the NS instances and the links between them. It is more or less focused to show how the traffic flows through the NSM. It will show you that NSC1 is connected to NSE1 for example. On the other hand, Jaeger is monitoring the API communication between the NSM components. Jaeger will show you when particular events happen and the messages that occur in the control plane to implement the requested changes in the Client/Endpoint links.

4. You can think of Jaeger as a distributed logging architecture. You have once central Jaeger instance that collects the logs from the probes installed in all the components of the NSM.

I let the other colleagues with a better understanding of the subject amend and/or correct me.

**Comment by edwarnicke** [comment]
@quangtamle Think of skydive and jaeger as optional (but super helpful) components.  

Skydive lets us visualize topology.  
NSM works just fine without, but it's super handy to have that visibility.

NSM is instrumented with OpenTracing.  This gives us tracing of calls between NSM components, which is super helpful both for development and also for operational instrumentation.  Jaeger is simply one possible choice of OpenTracing collectors (a really good one).
NSM works just fine without Jaeger, there's just nothing to collect the OpenTracing data without it.

@quangtamle Does that answer your questions?

**Comment by quangtamle** [comment]
Dear @nickolaev @edwarnicke ,

Thank you so much for your answers !!!

Now i can run Jaeger along with your replies I can understand more about Jaeger in particular and OpenTracing in general.

By the way, I have a stupid question. I downloaded your NetworkServiceMesh prototype. I tried to understand how those files work together and I completely lost. There are a lot of folders and I didnt know where to start. In fact, I tried to start from the Makefile but it seems I can not go far after that.

Could you show me a way to understand to the networkservicemesh folder ?

Thank you in advances

**Comment by quangtamle** [comment]
Dear @matrohon @nickolaev @edwarnicke 

It looks like in the NSM, Bandwidth and packet drop have not been supported on Skydive. Because when I tried to generate 1000 or 1000000 packets and send it at once from A to B then A/B only send/receive around 300-400 packets.

1. Is there any way to monitor the bw and packet drop of the connection ??? 
2. Further, can we allocate the bw for one specific connection (on demand) ???

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle Could you describe your setup in greater detail?

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Actually, I am using your networkservicemesh packet. I need to understand how it works first before try to deploy a small prototype for myself.

**Comment by edwarnicke** [comment]
@quangtamle I mean: what sets of NSEs are you stringing together?  Are they landing on the same node or different nodes?  How are you generating traffic?  How are you measuring throughput? :)

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

NSE and NSC, I tried two cases: on the same node and different node. I used the generator and capture feature on the Skydive and It show me the flow table between NSC and NSE which include Tx Rx packets, Tx Rx bytes.

**Comment by edwarnicke** [comment]
Ah... OK, so something like the nsc and icmp-responder I presume?  I am not familiar with the skydive traffic gen stuff, @matrohon do you know anything about it?

**Comment by quangtamle** [comment]
Yes...something like that!!!

**Comment by edwarnicke** [comment]
@quangtamle Thank you for starting to poke at NSM in terms of traffic gen stuff... I am not sure how skydive is doing it, or whether that's the right way to poke at it... but what you are trying to do in general is quite good :)

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Thank you for that !!!! :))

In fact, I also dont know what I am doing with Skydive is right or wrong, that's why I want to ask you guys who are currently working on this project.

**Comment by quangtamle** [comment]
Dear @matrohon @edwarnicke ,

What are the probes using in NSM for Skydive (in term of data) ??? Is it VPP probes or something else ???

Thank you in advances

**Comment by matrohon** [comment]
Hi @quangtamle,

sorry for the late reply. Generating traffic and capture from Skydive to test the NSM dataplane is something I want to achieve too.
I assume you're generating/capturing traffic by selecting the corresponding namespaces in Skydive?
You'll probably be  interested in the Ongoing Spec related to traffic monitoring in NSM. This Spec is incubating here : https://docs.google.com/document/d/1hMoNRyMQvJd1IuAduG4lTbhRU5NdyYM82WpKz-XTkSI/edit

**Comment by quangtamle** [comment]
Dear @matrohon @edwarnicke 

Sorry for the late reply.

I am generating/capturing traffic by selecting the corresponding namespaces in Skydive. By the way, I try to log in to the VPP of the dataplan to ping as a way to generate the traffic.

But right now I have a problem, the Skydive is not shown the crossconnect, only the nodes after I ran the command "make k8s-deploy". What is the problem ???

Thank you in advances

**Comment by matrohon** [comment]
Hi @quangtamle 

I recently pushed a new skydive version which fixes the skydive issue. you should delete the skydive images in master and worker nodes and redeploy skydive (make k8s-infra-deploy for instance) in order to pull the new skydive image.

**Comment by quangtamle** [comment]
Dear @matrohon 

Thank you so much, let me try

**Comment by quangtamle** [comment]
Dear @matrohon 

Sorry I tried the new image matrohon/skydive but it didnt work. Did I use the right image ???

![image](https://user-images.githubusercontent.com/43220759/53412216-11b82000-39c9-11e9-9a0b-47601c5fd0bd.png)

**Comment by matrohon** [comment]
@quangtamle the  image id looks correct. What use case are you testing? I'm using the vpn deployment during my tests (make k8s-vpn-deploy), and it works correctly.

**Comment by quangtamle** [comment]
Dear @matrohon 

I am using both "k8s-vpn-deploy" and "k8s-deploy" but skydive only showed the topology, not crossconnections.

P/s: I waited around 30 min to refresh it, but it still didnt show the connection

**Comment by quangtamle** [comment]
it's like this 
![image](https://user-images.githubusercontent.com/43220759/53416988-e5a29c00-39d4-11e9-9feb-860e1efe1050.png)

**Comment by matrohon** [comment]
@quangtamle no need to wait, crossconnects should appear as soon as they are created.

did you rebuild and reload nsmd images recently?

can you send me a dump of the skydive-analyzer logs (kubectl logs skydive-analyzer-...)

@edwarnicke did you test my latest image? does work for you?

**Comment by quangtamle** [comment]
Dear @matrohon 

Here is my dump
[logskube.txt](https://github.com/networkservicemesh/networkservicemesh/files/2905750/logskube.txt)

**Comment by matrohon** [comment]
@quangtamle it really looks like an gRPC API issue between Skydive and nsmd. Can you try a fresh deployment after at least rebuilding nsmd and the dataplane?

git pull origin master
make k8s-save
make k8s-load-image
make k8s-infra-deploy
make k8s-vpn-deploy

I just tested after rebuildinf from the latest NSM code available on master, and it works correctly on my setup.

**Comment by quangtamle** [comment]
Dear @matrohon 
There are some problems while I am deploying k8s-infra-deploy
![image](https://user-images.githubusercontent.com/43220759/53418931-23a1bf00-39d9-11e9-8cae-da685c743cd7.png)

**Comment by quangtamle** [comment]
Dear @matrohon 

So sorry After I rebuild the new image, it still didnt work

![image](https://user-images.githubusercontent.com/43220759/53420212-a4fa5100-39db-11e9-8384-83119233df19.png)
![image](https://user-images.githubusercontent.com/43220759/53420255-bc393e80-39db-11e9-85da-b32f7650dfdf.png)
![image](https://user-images.githubusercontent.com/43220759/53420333-e559cf00-39db-11e9-9888-3edc48a4f257.png)

**Comment by quangtamle** [comment]
Dear @nickolaev 
it still didnt work, I tried many times, I tried new skydive image but it didnt work. The result is still the same as the above figures

**Comment by quangtamle** [comment]
Dear @nickolaev @matrohon 

By the way, I have a question related to the [memory](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L31) using in Skydive.

When you use the variable "memory" then how can the system know what the memory is ??? Is this the system variable or human defined variable ???

If I want to use another DB, not that memory then how can I modify it ???

Thank you in advances

**Comment by matrohon** [comment]
@quangtamle "memory" means that skydive will store its datas (topologies, flows) in the RAM. You can tell skydive to store those datas in DB instead, such as ElasticSearch or Orientdb, by configuring the [Storage](https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L333) section of the skydive config [file](https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L81)

**Comment by quangtamle** [comment]
Dear @matrohon 

Thank you so much for your answer !!! 

This is exactly what I am looking for because I can not find where the storage of Skydive is defined in NSM.

**Comment by quangtamle** [comment]
Dear @matrohon 

Is there any way to check the data (topologies, flows) are stored in the RAM (or OrientdDB) ???

Thank you in advances

**Comment by quangtamle** [comment]
Dear @matrohon @nickolaev 

I tried to use orientdb as DB for Skydive but it didnt work. 
Here is my config file, may you tell me what is the problem ???

Thank you in advances
[skydive.txt](https://github.com/networkservicemesh/networkservicemesh/files/3003720/skydive.txt)

**Comment by quangtamle** [comment]
Dear @matrohon @nickolaev 

I can use OrientDB as DB for Skydive. It works well

Thank you

**Comment by quangtamle** [comment]
Dear @matrohon @nickolaev 

What is [nsm] (network service mesh I assume)(https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L45) probes in skydive.yaml and where is it defined??? Because I can not find nsm probes in the [skydive config file](https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L185).

Thank you in advances

**Comment by matrohon** [comment]
@quangtamle the NSM section for skydive is provided by my patch, maintained in a dedicated for of skydive : https://github.com/Orange-OpenSource/skydive/tree/nsm

this is a dedicated [PR](https://github.com/skydive-project/skydive/pull/1636/files# ) to have skydive hosting the nsm probe, the work is still ongoing

**Comment by quangtamle** [comment]
Dear @matrohon 

Thank you so much for your information !!!

**Comment by quangtamle** [comment]
Dear @matrohon 

Could you tell me why the agent topology [probes](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L39) is docker but analyzer topology probes is [nsm](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/skydive.yaml#L45) ????

Thank you in advances

**Comment by matrohon** [comment]
@quangtamle in skydive, some probes are run by the agent while others are run by the analyzer. For nsm, we chose to run it in the analyzer, while the skydive team chose to run the docker probe in the agent.

**Comment by quangtamle** [comment]
Dear @matrohon 

Thank you for your answer !!!
If I want to use VPP probes for the agent, is it possible ??? Because as far as I know, Skydive is not supported VPP probes, am I right ????

**Comment by matrohon** [comment]
@quangtamle skydive [recently merged](https://github.com/skydive-project/skydive/commit/a793bf50089eb733576f3cf596ee242195f28108) the vpp probe so yes it is possible. I plan to use this probe to display VPP interfaces included in a nsm crossconnection. Don't hesitate to start the work if you want.

Also, pantheon guys [demonstrated](https://youtu.be/wl96kwRmS5I) an integration between skydive and vpp, that is really inspiring for NSM.

**Comment by quangtamle** [comment]
Dear @matrohon 

Thank you so much for your information !!!! This is so inspiring !!! I try it now

**Comment by quangtamle** [comment]
Hi everyone,

I have some questions related to the NSM:

1/ About secure-intra-connection case, after establish a cross-connect to VPN gateway pod (NSE) then what happend next ??? because in the point of view of Sarah, she would like to have a secure connection to other pods, not to VPN gateway pod. May you explain a little bit to me in this case ???

2/ Beside a label to say this pod a FW or VPN gateway, inside the pods (i mean the content of it), how can you define that pod is a FW or VPN gateway ???? is it in the scope of NSM or it is aldready defined before and we just need to put the label on it ???

Thank you in advances

**Comment by quangtamle** [comment]
Dear @edwarnicke , @nickolaev @matrohon 

I have some questions related to the NSM:

1/ About secure-intra-connection case, after establish a cross-connect to VPN gateway pod (NSE) then what happend next ??? because in the point of view of Sarah, she would like to have a secure connection to other pods, not to VPN gateway pod. May you explain a little bit to me in this case ???

2/ Beside a label to say this pod a FW or VPN gateway, inside the pods (i mean the content of it), how can you define that pod is a FW or VPN gateway ???? is it in the scope of NSM or it is aldready defined before and we just need to put the label on it ???

Thank you in advances

**Comment by quangtamle** [comment]
> @quangtamle in skydive, some probes are run by the agent while others are run by the analyzer. For nsm, we chose to run it in the analyzer, while the skydive team chose to run the docker probe in the agent.

Dear @matrohon ,

As far as I know, the analyzer collects the data from the agents. So if the analyzer has its own probes to collect data by itself, is it duplicated with the agent (suppose they use the same probe) ????

Thank you in advances

**Comment by matrohon** [comment]
@quangtamle each agent is sending the data it coliects to the analyzer which can perform deduplication to avoid identical entries in the graph.

**Comment by quangtamle** [comment]
Hi @matrohon 

Thank you so much !!!

**Comment by quangtamle** [comment]
Hi @matrohon 

I try to use neo4j instead of orientdb but it didnt work. Is it supported by skydive????

Thank you in advances

**Comment by quangtamle** [comment]
Hi @matrohon ,

I wonder are there any ways to highlight the NSC and NSE in case the connections are lost ??? for example: the node will turn into red or the symbol will turn into something else...

Thank you in advances

**Comment by matrohon** [comment]
@quangtamle it would be possible since we receive connections status. for now, I'm trying to better understand the meaning and the circumstances of those status update messages. see #1048

**Comment by quangtamle** [comment]
Dear @matrohon ,

Thank you for your answer !!!

**Comment by quangtamle** [comment]
Dear @matrohon 

AFAIK, NSM probe runs only in Analyzers, not Agent. My questions are

1. Analyzer runs in 1 node of k8s cluster what if there is no data related to NSM on that node but in the other node, can Analyzer get those data ???

2. Why there is no option to run NSM probe in [Agent](https://github.com/skydive-project/skydive/blob/master/agent/probes.go#L70) ???

Thank you in advances !!!

**Comment by quangtamle** [comment]
Dear @matrohon 

AFAIK, NSM probe runs only in Analyzers, not Agent. My questions are

1. Analyzer runs in 1 node of k8s cluster what if there is no data related to NSM on that node but in the other node, can Analyzer get those data ???

2. Why there is no option to run NSM probe in [Agent](https://github.com/skydive-project/skydive/blob/master/agent/probes.go#L70) ???

Thank you in advances !!!

**Comment by quangtamle** [comment]
Dear @matrohon 

I did "make k8s-deploy" and "make k8s-check", everything work fine but when I open Skydive, I can not see any connections. Could you help me figure it out ????

Thank you in advances
