### ISSUE TITLE
RegisterNSE/FindNetwortkService are slow

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#626]
There is in issue with scenario if multiple NSMd register name NSE in this case current NSMD-k8s works extremely slow.

And in case it is fixed it is still works abour ~600ms per NSE Find request.

**Comment by haiodo** [comment]
I was able to register 6k NSE with different NSMs and retrieval time become 1.2-1.5 seconds to find NSE.

**Comment by edwarnicke** [comment]
Also relavent: https://github.com/ligato/networkservicemesh/issues/618#issuecomment-450679333
