### ISSUE TITLE
Implement NSMD check for NSE troubles and initial Auto healing operation

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#647]
Right now NSMD select just one NSE and in case of error doesn't select another one, we need to update code base to support this scenarios.

- [x] Unify local and remote NSMs codebase to be one generic NSM implementation with two concrete for local/remote request handling.
- [ ] Add basic Auto heal functionality
- [x] Fix unit tests
- [x] Rebase to new repository naming schema

**Comment by edwarnicke** [comment]
👍

**Comment by haiodo** [comment]
Also will add initial Auto healing, and having one NSM with support for different kind of local/Remote communication from clients and to endpoints/NSMs.

**Comment by haiodo** [comment]
@edwarnicke @nickolaev I think this one could be closed already, since we have more generic one 
#697

**Comment by nickolaev** [comment]
Outdated. Closing.
