### ISSUE TITLE
Work out documentation infrastructure

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#65]
Considered options are a docs directory in the repo or gh wiki.

**Comment by mestery** [comment]
Thanks for opening this! I'd lean towards using the wiki for meeting minutes, and document in-tree using markdown as much as possible for other items.

**Comment by nickolaev** [comment]
@rdimitrov #771 is dealing with this old issue, I guess.

**Comment by nickolaev** [comment]
Our docs folder gets a lot of attention. Closing this one.
