### ISSUE TITLE
Integration testing for MonitorCrossConnect from nsmd

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#664]
We have wonderful go based integration testing in test/integration

Would be good to extend it to check to make sure MonitorCrossConnect from nsmd is working as expected as well :)

**Comment by nickolaev** [comment]
#689 merged

**Comment by nickolaev** [comment]
@lobkovilya the tests faile randomly with: https://circleci.com/gh/networkservicemesh/networkservicemesh/11122

If the CI is rerun, the tests do pass.

Reopening.

**Comment by matrohon** [comment]
This race may be due to the portforward error that happens before the seg fault, don't you think?

**Comment by matrohon** [comment]
the same error is happenig here : 

https://circleci.com/gh/networkservicemesh/networkservicemesh/11122

**Comment by matrohon** [comment]
Do you have any other occurrence of this failure?, I can't find some in CircleCI.

**Comment by nickolaev** [comment]
Ups, it did it again: https://circleci.com/gh/networkservicemesh/networkservicemesh/11314

I don't think it is normal to see:
```shell
panic: runtime error: invalid memory address or nil pointer dereference
```

Whatever happens, this nil pointer should be handled more gracefully at least.
@lobkovilya what do you think?

**Comment by edwarnicke** [comment]
Done.
