### ISSUE TITLE
Implement AutoHeal functionality

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#697]
We need to be sure all AutoHeal functionality is working.

- [x] Local NSE die
All good, we could easy recover.
- [x] Remote NSE die
All good, we close local Dataplane and let source NSMD to choose another NSE.

- [x] Local Dataplane die
All good, we could re-program Dataplanes, remote and local one.
- [x] Remote Dataplane die
All good, we let source NSMD to recover and call our Dataplane to heal.

- [x] Remote NSM die
- - [x] Track remote NSMD down
- - [x] NSE should re-connect to new NSMD.
- - [x] Dataplane should re-connect to new NSMD.
- - [x] NSMD should search for new NSE and connect to.

- [x] Local NSMD die
- - [x] If Dataplane is alive, find local NSE and restore from Dataplane active connections.
- - [ ] Both NSMD and Dataplane are die, Client is alive. Client Monitor enforces Request to heal connection.
- - [x] Remote NSMD should track source NSMD die, wait for timeout and if heal not received close NSE connection.

Workflow for implemented parts:

Startup process:
<img width="607" alt="NSM-Startup-Recovery" src="https://user-images.githubusercontent.com/477235/54074888-d7088e80-42ca-11e9-91a7-0d50fd9d8aef.png">

Healing process:
<img width="699" alt="NSM-Healing" src="https://user-images.githubusercontent.com/477235/54074892-da037f00-42ca-11e9-97ba-0fe8d280f7cd.png">

Request/Heal handling
<img width="1182" alt="NSM-Request" src="https://user-images.githubusercontent.com/477235/54074893-dcfe6f80-42ca-11e9-95a2-1dc928d048f5.png">

**Comment by haiodo** [comment]
Dataplane auto heal is a bit more complex, found 3 cases at the moment:

<img width="1100" alt="auto-heal dataplane" src="https://user-images.githubusercontent.com/477235/52044182-17f6e000-2574-11e9-89ae-7d6c301ee39f.png">

**Comment by haiodo** [comment]
Initial diagram of how it working inside.
<img width="1754" alt="explained" src="https://user-images.githubusercontent.com/477235/53025794-31fd5180-3494-11e9-9ac3-e04c5bb286a1.png">

**Comment by haiodo** [comment]
Short update:
* Working on remote NSM die Healing.
* NSM Die from Dataplane recovery healing, required to not have NSE resource leaking.

**Comment by haiodo** [comment]
NSMD die workflow, if dataplane is alive.

<img width="1100" alt="nsmd die" src="https://user-images.githubusercontent.com/477235/53304701-fb1ba700-38aa-11e9-9d7e-3a8ff4288c67.png">

**Comment by haiodo** [comment]
As discussed with @edwarnicke We will modify NSPD-dp to mount also folder with nsmd-server socket, so NSE/NSC could connect to it. Right now we will still use workspace to put client/nse client sockets to connect from NSMD. In future we could think about different mechanism of NSMD discovery. 

NSMD will on startup register NSM/registry server inside nsmd-server folder accessible by any NSC/NSE and NSE will do monitor of NSMD liveness and call RegisterNSE on recovery.

NSC/Monitor in future will do same liveness monitoring of NSMD and do Request() on recovery will be required.

@lobkovilya as discussed with @edwarnicke  we need some generic mechanism for all NSC/Dataplane/NSE liveness monitoring of NSMD, so let's sync on your work in area of NSMD-k8s registry,

**Comment by nickolaev** [comment]
@haiodo is there still work going on here?

**Comment by haiodo** [comment]
Hi @nickolaev One case is still left, 
Both NSMD and Dataplane are die, Client is alive. 
Client Monitor enforces Request to heal connection.

But I suppose we could create separate issue for this case.

**Comment by nickolaev** [comment]
@haiodo please create a new one and reference to this.

**Comment by edwarnicke** [comment]
@haiodo Do please create another one with reference to this.  Going to close :)
