### ISSUE TITLE
how to install NSM on okd or OpenShift ?

### ISSUE THREAD

**Issue by marhatha** [networkservicemesh/networkservicemesh#698]
Hi ,

Can someone pls provide me the reference on how to deploy/install NSM on OKD/OpenShift ?
thanks in advance,

**Comment by edwarnicke** [comment]
Marhartha,

Do you anticipate there being something different about running NSM on
OpenShift vs Vanilla K8s (which is what we currently have CI for)?
Or are you looking for general instruction on running NSM on K8s that could
simply be applied to OpenShift?

I don't know that anyone has tried NSM on OpenShift, so I'm super excited
to get you going :)

Ed

**Comment by edwarnicke** [comment]
@marhatha Do you still need assistance?
