### ISSUE TITLE
Missing netmesh.yaml file

### ISSUE THREAD

**Issue by williamcaban** [networkservicemesh/networkservicemesh#702]
The documentation describe running netmesh as DaemonSet with the following command: 

kubectl create -f conf/netmesh.yaml 

Where can I find an example of such Deployment file? It does not seems available under k8s/conf/ or the conf/ directories in the repo.

**Comment by edwarnicke** [comment]
Ah... that was a long time ago.  Where in the docs so we can correct it

**Comment by williamcaban** [comment]
I was following RUN.md -- https://github.com/networkservicemesh/networkservicemesh/blob/master/RUN.md

So, if not those, what is a good guide to follow to deploy and test this with plain Kubernetes? (either building the containers or just using the ones from docker hub). The documents seem to assume running the Makefile will be the only way to test them.

**Comment by edwarnicke** [comment]
Doh... we cleaned up the contents of our docs/ dir:

https://github.com/networkservicemesh/networkservicemesh/tree/master/docs

Follow that.

**Comment by edwarnicke** [comment]
I've pushed a PR to delete the obsolete docs:

https://github.com/networkservicemesh/networkservicemesh/pull/703

**Comment by williamcaban** [comment]
Thanks. Can you give me some guidance here? From what I gather from `docs/Build.md` instructions it is basically `make k8s-build` or `make k8s-save`. Then `make k8s-infra-deploy`. Now, all these assume I want to use a Vagrant based K8s cluster, which I don't. I like to try this on a stand alone cluster. That is why I'm trying to find out the correct order and the manual steps to deploy the nsmd and vppagent-database DaemonSets into an existing Kubernetes cluster, and then deploy anything else.

So far, I'm able to manually build all the containers specified under `docker/Dockerfile.<something>`

After this, I'm assuming I have to use the YAML files at `k8s/conf/*.yaml`. If that is the case, what is the correct order to deploy these? Also, is there a way to understand which of these are essential to networkservicemesh vs which are optional vs which are the sample app?

**Comment by edwarnicke** [comment]
nsmd then dataplane:

https://github.com/networkservicemesh/networkservicemesh/blob/master/.k8s.mk#L19


Ed

**Comment by edwarnicke** [comment]
Oh... one better... our make machinery is setup to have multiple backend providers.  If you set:

export CLUSTER_RULES_PREFIX=null

The make machinery will simply presume you have made the images you built accessible to your k8s cluster manually, whereever it may be, and will just do the kubectl parts of the incantation.

**Comment by edwarnicke** [comment]
@williamcaban Did we get you unstuck on this?  If not, how can I help? :)
