### ISSUE TITLE
Spec: Envoy Network Service

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#704]
Envoy is a cloud-native edge and service proxy designed to provide highly configurable networking capabilities to L4/L7 streams.

Provide a network service example which provides Envoy as a request-able Network Service.

https://docs.google.com/document/d/127t19SB5dTQ_ODTuISmKnWz5fGjmLWRgtYEuX42AnX4/edit?usp=sharing

**Comment by edwarnicke** [comment]
Bump
