### ISSUE TITLE
Spec: Mutating Admission Controller injecting NSM init container into pod spec

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#708]

**Comment by edwarnicke** [comment]
[Draft Spec](https://docs.google.com/document/d/19VzbWQj3Pgf_VSUIQUXCS5HXV-chNpuXNKjVziSWjio/edit#)

**Comment by nickolaev** [comment]
Reopening this one as we need to update the `docs/spec` with the draft doc here.

**Comment by nickolaev** [comment]
#1069 is merged. Closing back again.
