### ISSUE TITLE
Spec: Interdomain NSM

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#714]
[Draft Spec](https://docs.google.com/document/d/1QjdJbYvzzsn6ARFq2iQcdBG9RN9m-Lx9kOq53sasnH8/edit#)

**Comment by matrohon** [comment]
I'm not able  to comment the draft.
This spec covers the use case where the client knows about domains he can ask for network services, but doesn't cover the use case where client just ask for a net service without knowing about the domain topology, am I wrong?

**Comment by edwarnicke** [comment]
@artem-belov Updated the spec for pNSRs etc.  Please have a look and let me know what you think.

@nickolaev @haiodo @fkautz Please also have a look :)
