### ISSUE TITLE
Spec: Metrics in MonitorCrossConnects/MonitorConnections

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#715]

**Comment by matrohon** [comment]
https://docs.google.com/document/d/1hMoNRyMQvJd1IuAduG4lTbhRU5NdyYM82WpKz-XTkSI/edit?usp=sharing

**Comment by edwarnicke** [comment]
Marked this as pinned so that stale-bot will leave it alone :)

**Comment by haiodo** [comment]
I think this should be closed already.
