### ISSUE TITLE
Consider renaming connection.NetworkService to connection.NetworkServiceName

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#716]
@nickolaev [Brought up the possibility of renaming](https://github.com/networkservicemesh/networkservicemesh/pull/692/files#r250141156)

[local.Connection.network_service](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/connection.proto#L48) -> local.Connection.network_service_name

[remote.Connection.network_service](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto#L49) -> remote.Connection.network_service_name

I think this is a good idea to discuss, and so opened this issue to it.

**Comment by nickolaev** [comment]
OK so I think this is pretty obvious. The said fields area actually denoting the NS name (they are strings) and are not a "network service" as such. I think that clearer naming of 'things' in the project is a part of our effort to have better code.
So I vote +1.

**Comment by edwarnicke** [comment]
@fkautz Your opinion?

**Comment by matrohon** [comment]
make sense to me, :+1:

**Comment by fkautz** [comment]
I have mixed feelings on this. Yes it is more accurate but also feels overly verbose and pedantic.
