### ISSUE TITLE
Spec: SRv6 Remote Mechanism

### ISSUE THREAD

**Issue by dabernie** [networkservicemesh/networkservicemesh#724]
Segment-Routing IPv6 (SRv6) is a data plane implementation that implements segment-routing over an IPv6 network by leveraging an extension header https://tools.ietf.org/html/draft-ietf-6man-segment-routing-header-16 to encore the list of END nodes to pass through on the forwarding path.

These END nodes can be "programmed" with different behaviors has defined in https://tools.ietf.org/html/draft-filsfils-spring-srv6-network-programming-06 and can also a list of service behaviors (e.g. functions) referred has service programming (https://tools.ietf.org/html/draft-xuclad-spring-sr-service-programming-01)

Spec will provide an example of leveraging SRv6 as a remote mechanism for interconnecting Network Service Endpoints and Network Service Clients

**Comment by matrohon** [comment]
I can't wait to see the spec :)

**Comment by tfherbert** [comment]
Do we need traffic engineering or is this spec still to immature?

**Comment by tfherbert** [comment]
The traffic engineering reference points to 
https://tools.ietf.org/html/draft-ietf-idr-te-lsp-distribution-09

**Comment by dabernie** [comment]
working on it ... I unfortunately cannot seem to assign myself to it to move it in progress.
@tfherbert spec is a bit too early to add traffic engineering but if/when we are there we would integrate with the following references https://tools.ietf.org/html/draft-filsfils-spring-segment-routing-policy-06

**Comment by dabernie** [comment]
interesting aspects would be service composition between local and remote mechanisms and how to reflect both within a "service policy"
