### ISSUE TITLE
Create NSM CRD bundle yaml

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#736]
Today NSM registers its CRDs in NSMD-k8s here: https://github.com/networkservicemesh/networkservicemesh/blob/51295d0cd3bfdbe8c3a99e05ad8974d19c6d9a3a/k8s/cmd/nsmd-k8s/main.go#L112

They are removed when NSMD-k8s is killed here:
https://github.com/networkservicemesh/networkservicemesh/blob/51295d0cd3bfdbe8c3a99e05ad8974d19c6d9a3a/k8s/cmd/nsmd-k8s/main.go#L134

This add/remove procedure is not as robust as we would like. The proposed (and established) way of registering the project CRDs would be to have a dedicated yaml bundle that describes them.

These would become part of our cluster configuration, as we do with the RBACs here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/.k8s.mk#L29

We also want NSMD-k8s code to deal with CRDs add/remove to be deleted.

Note that the initializing the Packet cluster for the CI needs to be adapted for your CI to pass. It is done here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/scripts/prepare-circle-integration-tests.sh#L31

**Comment by ivanayov** [comment]
I can work on this
