### ISSUE TITLE
Spec: Securing NSM Connection Request/Close

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#737]

**Comment by lobkovilya** [comment]
https://docs.google.com/document/d/13uI2JnqIWwF8wkOPjVv0naJ5ClFhWgpbKBBrngNl28c/edit?usp=sharing

**Comment by edwarnicke** [comment]
Updated [#737 Security Spec](https://docs.google.com/document/d/1SR9_p3QvvGL-MoDQ9ekbiufOvS1M6S4sKDJ5Saijlo4/edit#)
