### ISSUE TITLE
Automate collection of vpp post mortem data from crashes

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#738]
The vppagent-dataplane has occasionally been observed crashing.  The vpp community tends to be really good about swiftly fixing bugs, but they understand dataplanes, not complex K8s systems.

The VPP folks have prepared [How to file Bugs](https://wiki.fd.io/view/VPP/BugReports#Capturing_post-mortem_data) attempting to describe how to
* Collect core files
* Collect corresponding images and debug symbols
* Collect api traces

supervisord provides mechanisms to [run a script on crash](https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/conf/supervisord/supervisord.conf#L30).  So we could write a script to be run on crash to:

* Collect core files
* Collect corresponding image and debug symbols
* [Collect api traces](https://wiki.fd.io/view/VPP/How_To_Use_The_API_Trace_Tools)
* Collect any other contextual info that might be helpful

And automatically save it somewhere (like CircleCI artifacts in CI) where it can be easily retrieved and used to file a high quality bug with the VPP folks.

**Comment by stepan-anokhin** [comment]
Hi @edwarnicke! I'll work on this one.

**Comment by nickolaev** [comment]
@stepan-anokhin I have sent you and invitation to join the project so I can assign this issue to you. Please confirm the invitation.

**Comment by stepan-anokhin** [comment]
@nickolaev, thanks!

**Comment by edwarnicke** [comment]
More hints (as I'm doing this by hand just now).  The original packages and their debug symbols are in the [ligato/dev-vpp-agent:v1.8](https://hub.docker.com/r/ligato/dev-vpp-agent) docker image.  They are in [/opt/vpp-agent/dev/vpp/build-root/](https://github.com/ligato/vpp-agent/blob/v1.8/docker/prod/Dockerfile#L28).

**Comment by stepan-anokhin** [comment]
ok, got it.

**Comment by edwarnicke** [comment]
Good info on this also showing up in #757

**Comment by stepan-anokhin** [comment]
Hi @edwarnicke! Thanks for the guidelines! 

I've created a Draft PR to highlight the current status: #762 

The problem with the current approach is that naive storing of core dumps actually circumvents container isolation. Specifying a custom `kernel.core_pattern`, as it turns out, affects host OS and all containers running on the same node. And there seems to be no out-of-the-box mechanism to do that in a clean and isolated fashion in Docker and k8s. Currently I'm investigating whether it could be implemented with gdb. 

I'm also going to extend go integration tests with similar features.

**Comment by stepan-anokhin** [comment]
Hi @edwarnicke 

I've updated the PR. The problem with leaking `kernel.core_pattern` is now resolved using the gdb. 
Now we attach to the running vpp process and dump a core image in clean isolated fashion. 

Unfortunately, production build of vpp doesn't include a gdb (which adds +100MB)  so I've added a new vppagent-dataplane-dev image derived from the [ligato/dev-vpp-agent](https://github.com/ligato/vpp-agent/blob/master/docker/dev/Dockerfile) for this purpose. The dev-image includes both gdb and vpp debug symbols. 

Core dumps of dev-vpp are really huge (~20GB), so collecting them is disabled by default. Stack-traces and other context information are always collected. 

Also go integration tests are now using new dev-image of vppagent-dataplane.

**Comment by haiodo** [comment]
@stepan-anokhin ouch, 20GB is big core dumps.

**Comment by stepan-anokhin** [comment]
I've fixed integration tests failures. 

We still need to retrieve postmortem data from the cluster during the build and save it as build artifacts.
This could be done in a two ways (at least): 
1. via extending go integration testing framework to collect postmortem data on `k8s.Cleanup()` using the k8s client-go (hints could be found in [kubectl cp](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cp/cp.go) implementation and k8s [e2e testing framework](https://github.com/kubernetes/kubernetes/blob/v1.6.1/test/e2e/framework/exec_util.go)) 
2. via retrieving files from the terraform cluster.

**Comment by stepan-anokhin** [comment]
One test failed but it seems to be unrelated to my changes: 
```
--- FAIL: TestNscDiesSingleNode (62.50s)
Error Creating Pod: nsmd-ci-14787-master Failed to deploy pod
```

**Comment by stepan-anokhin** [comment]
I've extended integration-testing framework to collect postmortem data on each k8s [cleanup](https://github.com/networkservicemesh/networkservicemesh/pull/762/commits/5e0a6e13c9dd348515d188c3ecd71f9e82956159#diff-844026f40ab25894a9c979430ef0cbd4R340). 
All collected backtraces and logs are now [stored](https://github.com/networkservicemesh/networkservicemesh/pull/762/commits/b443a8fbf17feb3e8bdd68cf7efcb6d9b1872e0e#diff-1d37e48f9ceff6d8030570cd36286a61R144) as build artifacts.

**Comment by stepan-anokhin** [comment]
Build fails because of [golang/ling](https://github.com/golang/lint/issues/436) issue

**Comment by stepan-anokhin** [comment]
Finally fixed the PR. Only VPN tests fail.

**Comment by edwarnicke** [comment]
@stepan-anokhin Is this issue completed?

**Comment by nickolaev** [comment]
Done!
