### ISSUE TITLE
Implement a Dataplane tests

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#752]
We should have a Dataplane integration tests with direct programming/re-programming of vppagent-dataplane with different parameters.

It needs testing between different pairings (kernel, kernel), (kernel, memif), (kernel,vxlan), (memif, memif), (memif, vxlan)

We could have two alphine pods, get linux namespaces from them and program.
May require small changes into vppagent-dataplane to listen using TCP/IP and do not connect to NSMD if some testing parameters are passed.

**Comment by haiodo** [comment]
@stepan-anokhin Please take care. Also I think we could create this tests with pure docker, to be able to more easy give instructions to vpp/vpp-agent guys in case of any error related to vpp.

@edwarnicke Thoughts?

**Comment by stepan-anokhin** [comment]
Ok, I'll take a look.

**Comment by nickolaev** [comment]
I believe this one is already taken care of. Closing.
