### ISSUE TITLE
Replace nsm.ligato.io/socket

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#755]
NSM uses `nsm.ligato.io/socket` as the name of the location of the NSM client socket. Let's rename this to `networkservicemesh.io/socket`.

@edwarnicke @fkautz need to approve this.

**Comment by haiodo** [comment]
@nickolaev  nsm.ligato.io/socket is name of resource passed to NSMDp, server/client sockets are passed as part of NSMDp environment variables passing to NSC/NSE NSM_SERVER_SOCKET/NSM_CLIENT_SOCKET but you are right in any case, name should be changed.
