### ISSUE TITLE
vpp crashes when attempting to run in Pod in host networking

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#757]
When attempting to run vpp in a Pod in host networking, it crashes immediately with:

```
/usr/bin/vpp[17659]: received signal SIGBUS, PC 0x7fd2f01d58ba
/usr/bin/vpp[17659]: #0  0x00007fd2f0c6697d 0x7fd2f0c6697d
/usr/bin/vpp[17659]: #1  0x00007fd2f07bc890 0x7fd2f07bc890
/usr/bin/vpp[17659]: #2  0x00007fd2f01d58ba 0x7fd2f01d58ba
/usr/bin/vpp[17659]: #3  0x00007fd2f054d4f2 0x7fd2f054d4f2
/usr/bin/vpp[17659]: #4  0x00007fd2f054f673 clib_pmalloc_create_shared_arena + 0x213
/usr/bin/vpp[17659]: #5  0x00007fd2f0c46cf3 vlib_physmem_shared_map_create + 0x23
/usr/bin/vpp[17659]: #6  0x00007fd2f0c1b561 vlib_buffer_main_init + 0x151
/usr/bin/vpp[17659]: #7  0x00007fd2f0c3b70a vlib_main + 0x12a
/usr/bin/vpp[17659]: #8  0x00007fd2f0c65a56 0x7fd2f0c65a56
/usr/bin/vpp[17659]: #9  0x00007fd2f053bfc4 0x7fd2f053bfc4
```
(note: log captured from different run than corefile, so take mem addresses with a grain of salt)

[vpp-deb.tar.gz](https://drive.google.com/file/d/1i-JBsO5PPKLszVxYaBDPg7XqCSZpaqd0/view?usp=sharing) contains the Debian packages (and debug files) needed to debug this problem with gdb.  See the README.md in the tarball for info on what git commit it was built from.  

You can download the [core file from the crash](https://drive.google.com/file/d/1sCeJw-bG3rzzJ49OFjRtfR_FV-e8mhID/view?usp=sharing)

**Comment by edwarnicke** [comment]
In the event you need to recreate the crash, I've created #758.

#758 simply sets up a pretty simple scenario where the vppagent-dataplane Pod runs without really doing anything, to allow you to run vpp there yourself.

To recreate follow these instructions to [setup core file capture on both master and worker](https://wiki.fd.io/view/VPP/BugReports#Core_Files).
```bash
make k8s-vppagent-dataplane-save
make k8s-vppagent-dataplane-deploy
kubectl get pods # To get the name of a vppagent-dataplane Pod
kubectl exec -it ${name of a vppagent-dataplane Pod} /bin/sh
```

Once execed into the Pod:
```bash
/usr/bin/vpp -c /etc/vpp/vpp.conf
```
This should crash immediately with a SIGBUS error.

**Comment by dmarion** [comment]
Can you be so kind and capture backtrace with gdb (one above is missing symbol names), so I don't need to download 1.1G core file?

Is this reproducible with simple docker image?

**Comment by edwarnicke** [comment]
@artem-belov To get the debug image going, you will want recreate the vppagent:v1.8 docker image but installing the vpp-dbg rather than the vpp deb packages.  That should be accomplishable by changing:

https://github.com/ligato/vpp-agent/blob/v1.8/docker/prod/Dockerfile#L28

From 
``` 
/opt/vpp-agent/dev/vpp/build-root/vpp_*.deb \
```
to 
```
 /opt/vpp-agent/dev/vpp/build-root/vpp-dbg_*.deb \
```
and

https://github.com/ligato/vpp-agent/blob/v1.8/docker/prod/Dockerfile#L34

from 
```
&& dpkg -i vpp_*.deb vpp-lib_*.deb vpp-plugins_*.deb \
```

to 
```
&& dpkg -i vpp-dbg_*.deb vpp-lib_*.deb vpp-plugins_*.deb \
```

**Comment by haiodo** [comment]
@edwarnicke There is docker/dev/build.sh doing this stuff already I suppose. At least I've used it to build local vppagent with debug vpp.

**Comment by edwarnicke** [comment]
@haiodo Awesome!  Lets do that :)

**Comment by edwarnicke** [comment]
@artem-belov @haiodo mentioned you were having some reproduction issues.

When running in Vagrant using either VMWare *or* Virtualbox (I tried both), everything works as long as I don't set ['hostNetwork: true'](https://github.com/edwarnicke/networkservicemesh/blob/fd03a20b7ea1a70da2a6d887a61908b9a7ad4d4b/k8s/conf/vppagent-dataplane.yaml#L11)... but if I set 'hostNetwork:true' I do get the SIGBUS error, and if I change it back... I still get the SIGBUS error... everytime I try, until I reboot the Vagrant (vagrant destroy -f;vagrant up)... 

So it should be quite reproducable from Vagrant.

**Comment by edwarnicke** [comment]
OK... just noticed something:

#764 passes CI... which strongly suggests the issue is specific to Vagrant.

**Comment by edwarnicke** [comment]
OK, additional observation:

When running in hostNetwork:true, I see:

```
/usr/bin/vpp[21872]: clib_sysfs_prealloc_hugepages:261: pre-allocating 7 additional 2048K hugepages on numa node 0
```

when running without hostNetwork:true, I see:

```
/usr/bin/vpp[7709]: buffer: vlib_physmem_shared_map_create: pmalloc_map_pages: failed to mmap 7 pages at 0x7f6d66000000 fd 4 numa 0 flags 0x2011: Cannot allocate memory
/usr/bin/vpp[7709]: buffer: falling back to non-hugepage backed buffer pool
```

**Comment by edwarnicke** [comment]
Also, I've built and pushed a edwarnicke/vpp-agent-debug:v1.8 docker container which is up in dockerhub... though it doesn't seem to produce any more data in the traces.

**Comment by artem-belov** [comment]
@edwarnicke Thank you, it helped. Just reproduced issue with **hostNetwork: true**

**Comment by artem-belov** [comment]
```
 if ((ftruncate (a->fd, size)) == -1)
	goto error;
...
va = pm->base + (((uword) vec_len (pm->pages)) << pm->def_log2_page_sz);
  if (mmap (va, size, PROT_READ | PROT_WRITE, mmap_flags, a->fd, 0) ==
      MAP_FAILED)
    {
      pm->error = clib_error_return_unix (0, "failed to mmap %u pages at %p "
					  "fd %d numa %d flags 0x%x", n_pages,
					  va, a->fd, numa_node, mmap_flags);
      goto error;
    }

  clib_memset (va, 0, size);
```
memset generates the SIGBUS

**Comment by nickolaev** [comment]
Oh that great work your're doing here!

**Comment by haiodo** [comment]
@artem-belov question here is how to fix :-)

**Comment by dmarion** [comment]
OK, so you are saying that mmap does not fail (rv != MAP_FAILED) but writing to mapped memory is causing sigbus. Correct?

**Comment by artem-belov** [comment]
@dmarion Correct

**Comment by edwarnicke** [comment]
@dmarion Could this be related to the difference in lines about Hugepages above?

It sort of feels like when running in hostNetwork:true, vpp can *see* that there are Hugepages, but lacks the permission to access them... but tries to use them anyway.

**Comment by edwarnicke** [comment]
Doing a bit more research, it looks like we are somehow discovering that hugepages are a theoretical possiblity even though we don't have a hugetlb cgroup needed to have proper access to them.

**Comment by edwarnicke** [comment]
@artem-belov @dmarion Would it possibly make sense to fstat the mmaped a->fd to see if its the size we expect?  since we are getting an errorless mmap and ftruncate, but clearly something is not as it should be?

**Comment by edwarnicke** [comment]
@artem-belov @dmarion This also looks promising:

https://stackoverflow.com/questions/37954675/getting-sigbus-after-mmap-for-huge-pages-even-though-hugepages-free-is-positive

**Comment by artem-belov** [comment]
@edwarnicke Size and permissions are correct. Ftruncate works properly.

**Comment by edwarnicke** [comment]
@artem-belov I presume that size and permission are from checking with fstat?

Did the mincore() suggestion yield any fruit?

**Comment by artem-belov** [comment]
@edwarnicke I will double check, but I think mincore helps to avoid sigbus.

**Comment by edwarnicke** [comment]
@artem-belov Does that mean we could use mincore to fix our crashing issue here?

**Comment by artem-belov** [comment]
@edwarnicke With that fix we will avoid crash by using non hugepage buffer

**Comment by artem-belov** [comment]
Created pull request
https://github.com/FDio/vpp/pull/13

**Comment by edwarnicke** [comment]
Please push to 
https://gerrit.fd.io/ .  The github.com is just a mirror of the Gerrit for fd.io at this time

**Comment by artem-belov** [comment]
https://gerrit.fd.io/r/#/c/17838/

**Comment by artem-belov** [comment]
I made fix to allocate 4 Kb pages skipping mincore . For some reason if Pod configured without
```
securityContext:
            privileged: true
```
mincore shows wrong allocation of 4 Kb page even if everything is correct.
Both fixes 757, 775 rebased to 6b4a32ded6d3db56d886e79154e8329bdfc0ed2a are available  here
https://github.com/artem-belov/vpp/commits/pr_huge_page_sigbus

**Comment by edwarnicke** [comment]
@artem-belov Cool... did this go upstream in https://gerrit.fd.io/r/#/c/17838/ ? :)

**Comment by artem-belov** [comment]
@edwarnicke Yes

**Comment by nickolaev** [comment]
@edwarnicke after the awesome work you and @artem-belov did, we could probably close this one?

**Comment by nickolaev** [comment]
@artem-belov @edwarnicke I'll close this one. Fill free to re-open if you think it is not solved.
