### ISSUE TITLE
Split integration testing

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#766]
Our integration testing is a really important part of the release process. We run the tests in the CI here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/.circleci/config.yml#L125

Since we add more and more tests, this step is taking a long time and is hard to track what is going on.
Therefore we can split the test execution into parts, differentiating by test's function:
 * basic - simple k8s tests (like [exect_test.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/exec_test.go)), basic nsmd deployment etc.
 * recover - all the healing tests ([death_handling_test.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/death_handling_test.go), [nse_dataplane_heal_test.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/nse_dataplane_heal_test.go), [nse_heal_test.go](https://github.com/networkservicemesh/networkservicemesh/blob/master/test/integration/nse_heal_test.go))
 * usecase - all the icmp and vpn tests
 
These are just proposed categories, one can come op with another split. The testfiles can be marked with [go build tags](https://golang.org/pkg/go/build/) and then each category can be run in a separate CircleCI `run` clause. Note we do not want separate jobs here, otherwise, we will end up in parallel execution and create problems. The test category selection happens by adding a flag `-tags basic` to the `go test` or `gotestsum` command line.

So each new test added has to choose a category and mark its file e.g. `// +build basic`. We can add a simple README in the test folder or in doc/spec if that is preferred, explaining the marking strategy.

New categories can be added or even split. I assume if we get enough usecase tests we can do `usecase_simple` and `usecase_complex` or similar.

**Comment by edwarnicke** [comment]
I like very much looking at breaking up by thematic groups... using build tags for them is an interesting way to automate :)

**Comment by edwarnicke** [comment]
@rdimitrov Was this resolved by #781 ?  If so, should we close this issue?

**Comment by rdimitrov** [comment]
@edwarnicke Indeed, we should close it. It's already resolved by that PR 👍
