### ISSUE TITLE
Improve Network Service Manager register/deregister

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#767]
Network Service Manager gets registered in the `RegisterNSE` call here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/pkg/registryserver/nse.go#L51

It is not a real problem since the manager can be registered only when the first Endpoint is deployed, but in reality, there is no need to do so before that. However, the NSE registration request is piggy backed to carry the Network Service Manager `url`:
https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/pkg/registryserver/nse.go#L46. And is actually invoked here:
https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/nsmd/nsmd.go#L161

The first proposal is to extend the registry [service NetworkServiceRegistry](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L60) with an additional API to have a dedicated RegisterNSMgr call.
Alternatively, one shoudl provide a DeregisterNSMgr call called on the way out of NSMd. The deregister might also happen on the exit of nsmd-k8s too.

**Comment by edwarnicke** [comment]
Interesting idea... might be good to start with a PR for the proposed API change?

**Comment by ivanayov** [comment]
@lobkovilya seems like #805 covers this. I there anything left? We don't do deregister explicitly, but I think it's unnecessary with the current implementation.

**Comment by lobkovilya** [comment]
@ivanayov yes, the only thing to do is deregister method , but I agree it's unnecessary now
