### ISSUE TITLE
Issues with setup instructions on the the quick start guide

### ISSUE THREAD

**Issue by bryclexiayongzhi** [networkservicemesh/networkservicemesh#768]
Run the script make k8s-save ,in the step 8/13 : Run go mod download ,It turns out the result below,why?
go: finding github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
go: finding github.com/go-errors/errors v1.0.1
go: finding github.com/gogo/protobuf v1.2.0
go: finding github.com/uber/jaeger-lib v1.5.0
go: finding github.com/evanphx/json-patch v4.1.0+incompatible
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/docker/distribution v2.7.1+incompatible
go: k8s.io/code-generator@v0.0.0-20190215220509-095ce2f23e83: unrecognized import path "k8s.io/code-generator" (https fetch: Get https://k8s.io/code-generator?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/apiserver@v0.0.0-20190111033246-d50e9ac5404f: unrecognized import path "k8s.io/apiserver" (https fetch: Get https://k8s.io/apiserver?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: gopkg.in/inf.v0@v0.9.1: unrecognized import path "gopkg.in/inf.v0" (https fetch: Get https://gopkg.in/inf.v0?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/elazarl/goproxy v0.0.0-20181111060418-2ce16c963a8a
go: finding github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: google.golang.org/grpc@v1.18.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/ligato/vpp-agent v0.0.0-20181004120253-d2ae51e30bb3
go: github.com/go-errors/errors@v1.0.1: unknown revision v1.0.1
go: github.com/uber/jaeger-lib@v1.5.0: unknown revision v1.5.0
go: github.com/docker/distribution@v2.7.1+incompatible: unknown revision v2.7.1
go: github.com/golang/protobuf@v1.2.0: unknown revision v1.2.0
go: github.com/evanphx/json-patch@v4.1.0+incompatible: unknown revision v4.1.0
go: github.com/gogo/protobuf@v1.2.0: unknown revision v1.2.0
go: finding github.com/gregjones/httpcache v0.0.0-20181110185634-c63ab54fda8f
go: finding github.com/golang/groupcache v0.0.0-20181024230925-c65c006176ff
go: finding github.com/rs/xid v1.2.1
go: finding github.com/ghodss/yaml v1.0.0
go: finding github.com/pkg/errors v0.8.1
go: k8s.io/client-go@v10.0.0+incompatible: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
go: github.com/docker/spdystream@v0.0.0-20181023171402-6480d4af844c: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/60dfa5c037476c38c09ec11ed0ec6b986ca3f4a132e4cfbfc39c9192de8456ef: exit status 128:
 fatal: unable to access 'https://github.com/docker/spdystream/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: github.com/ghodss/yaml@v1.0.0: unknown revision v1.0.0
go: github.com/rs/xid@v1.2.1: unknown revision v1.2.1
go: finding github.com/teris-io/shortid v0.0.0-20160104014424-6c56cef5189c
go: github.com/pkg/errors@v0.8.1: unknown revision v0.8.1
go: finding github.com/opentracing/opentracing-go v1.0.2
go: github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/e3da2a565352fc053fb7730886bf07c23545d2a92d4bc6bc166097f9c01f7a88: exit status 128:
 fatal: unable to access 'https://github.com/modern-go/reflect2/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: github.com/elazarl/goproxy@v0.0.0-20181111060418-2ce16c963a8a: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/e29e26be7ff527fb4d81ef752f9583f0b1edcb460d80ef53f57c935b54e310e8: exit status 128:
 fatal: unable to access 'https://github.com/elazarl/goproxy/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: golang.org/x/net@v0.0.0-20190107210223-45ffb0cd1ba0: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/klog@v0.1.0: unrecognized import path "k8s.io/klog" (https fetch: Get https://k8s.io/klog?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/api@v0.0.0-20181213150558-05914d821849: unrecognized import path "k8s.io/api" (https fetch: Get https://k8s.io/api?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/sirupsen/logrus v1.3.0
go: github.com/ligato/vpp-agent@v0.0.0-20181004120253-d2ae51e30bb3: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/f40bd33ee6dc95b8c3055923676aa199a36080ce593a1dd93277c9d723c89773: exit status 128:
 fatal: unable to access 'https://github.com/ligato/vpp-agent/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: finding github.com/googleapis/gnostic v0.2.0
go: golang.org/x/sys@v0.0.0-20190107173414-20be8e55dc7b: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/utils@v0.0.0-20190204185745-a326ccf4f02b: unrecognized import path "k8s.io/utils" (https fetch: Get https://k8s.io/utils?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/kubernetes@v1.13.2: unrecognized import path "k8s.io/kubernetes" (https fetch: Get https://k8s.io/kubernetes?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: github.com/gregjones/httpcache@v0.0.0-20181110185634-c63ab54fda8f: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/6501966d1331e1f5a2dbad92d2095aea1693033b492678e4ccee57beb108039c: exit status 128:
 fatal: unable to access 'https://github.com/gregjones/httpcache/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: github.com/golang/groupcache@v0.0.0-20181024230925-c65c006176ff: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/f7a002ff08195b00c4fb5bb7261149151f6e428ed0b5528aaeb02b6c48b497cf: exit status 128:
 fatal: unable to access 'https://github.com/golang/groupcache/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: github.com/opentracing/opentracing-go@v1.0.2: unknown revision v1.0.2
go: finding github.com/ventu-io/go-shortid v0.0.0-20171029131806-771a37caa5cf
go: github.com/opencontainers/go-digest@v1.0.0-rc1: unknown revision v1.0.0-rc1
go: finding github.com/imdario/mergo v0.3.6
go: gopkg.in/yaml.v2@v2.2.2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: google.golang.org/appengine@v1.4.0: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: golang.org/x/oauth2@v0.0.0-20181203162652-d668ce993890: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
go: finding github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: github.com/google/btree@v0.0.0-20180813153112-4030bb1f1f0c: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/4ff5de2528e697f9c44db2ba60956692d248fab9ff5138086b2b6aac5271bfa4: exit status 128:
 fatal: unable to access 'https://github.com/google/btree/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
go: finding github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
go: github.com/sirupsen/logrus@v1.3.0: unknown revision v1.3.0
go: github.com/spf13/pflag@v1.0.3: unknown revision v1.0.3
go: finding github.com/hashicorp/golang-lru v0.5.0
go: golang.org/x/time@v0.0.0-20181108054448-85acf8d2951c: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: k8s.io/apiextensions-apiserver@v0.0.0-20181213153335-0fe22c71c476: unrecognized import path "k8s.io/apiextensions-apiserver" (https fetch: Get https://k8s.io/apiextensions-apiserver?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
go: finding github.com/peterbourgon/diskv v2.0.1+incompatible
go: github.com/googleapis/gnostic@v0.2.0: unknown revision v0.2.0

**Comment by bryclexiayongzhi** [comment]
what's the reason of causing mistakes? how to solve it?

**Comment by nickolaev** [comment]
@bryclexiayongzhi are you behind a proxy?

```shell
proxyconnect tcp: tls: first record does not look like a TLS handshake
```

You might find this comment useful:
https://github.com/docker/for-linux/issues/415#issuecomment-453610657

**Comment by edwarnicke** [comment]
@bryclexiayongzhi A brief explanation of what's happening here.

We build using go modules.  What this means is that the first time you build, its going to download and build the dependencies.

That download process seems to be having an issue, from the looks of the errors because of a malfunctioning proxy.

The good news is, the way we constructed our docker layers, the go mod download should cache, so once you've done it once, layer caching will be your friend.

Was that helpful?

**Comment by bryclexiayongzhi** [comment]
> @bryclexiayongzhi are you behind a proxy?
> 
> ```shell
> proxyconnect tcp: tls: first record does not look like a TLS handshake
> ```
> 
> You might find this comment useful:
> [docker/for-linux#415 (comment)](https://github.com/docker/for-linux/issues/415#issuecomment-453610657)

But I can use the command curl to get the information through proxy， this maybe show proxy is ok. Besides there are some other mistakes ,for example: go: github.com/uber/jaeger-lib@v1.5.0: unknown revision v1.5.0, how to solve this issue.

**Comment by nickolaev** [comment]
@bryclexiayongzhi is `go mod download` working for you if you are not in the docker container? I.e. instead of running `make k8s-save` run `go mod download`. The purpose of this command would be to figure out if your host can download all the dependent modules (as you say curl works). Then you can see what settings you have on your host and check how to replicate them for your docker setup.
https://docs.docker.com/network/proxy/
