### ISSUE TITLE
How to create a k8s cluster without using vagrant

### ISSUE THREAD

**Issue by BoutheinaDab** [networkservicemesh/networkservicemesh#773]
TO create a two-VMs k8s cluster (master and worker node) without using vagrant.

**Comment by nickolaev** [comment]
@BoutheinaDab you shoudl check K8s docs for this:
https://kubernetes.io/docs/setup/pick-right-solution/

In our Vagrant based setup we rely on kubeadm to do this for us:
https://github.com/networkservicemesh/networkservicemesh/blob/master/scripts/vagrant/scripts/configureK8smaster.sh
https://github.com/networkservicemesh/networkservicemesh/blob/master/scripts/vagrant/scripts/configureK8sworker.sh
