### ISSUE TITLE
Fix sanity-check failures related to golint

### ISSUE THREAD

**Issue by stepan-anokhin** [networkservicemesh/networkservicemesh#789]
## Description 
All recent builds fail because of `golint` [issue](https://github.com/golang/lint/issues/436)
This blocks build system and all pending PRs from being verified. 

We need to circumvent the issue until some robust solution will be provided.

**Comment by stepan-anokhin** [comment]
@edwarnicke @nickolaev plese take a look at #788

**Comment by edwarnicke** [comment]
Merged #788
