### ISSUE TITLE
Factor out UpdateNSM into its own service (followup for #)786

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#799]
#786 places #UpdateNSM in the "Discovery" service.  Please factor it out into its own service.

[Comment on #786](https://github.com/networkservicemesh/networkservicemesh/pull/786#discussion_r262188954)

**Comment by lobkovilya** [comment]
Probably we could unite this issue with https://github.com/networkservicemesh/networkservicemesh/issues/767? 

So I will create something like:
```
service NsmRegistry {
    rpc RegisterNSM (NetworkServiceManager) returns (NetworkServiceManager);
    rpc UpdateNSM (NetworkServiceManager) returns (NetworkServiceManager);
    rpc RemoveNSM (NetworkServiceManager) returns (google.protobuf.Empty);
}
```

What do you think?

**Comment by nickolaev** [comment]
@lobkovilya I'd `+1` this suggestion.

**Comment by edwarnicke** [comment]
+1

**Comment by edwarnicke** [comment]
@lobkovilya Is this fixed?  If so, in what PR?

**Comment by lobkovilya** [comment]
Yes, it fixed in https://github.com/networkservicemesh/networkservicemesh/pull/805
