### ISSUE TITLE
Check for IPNeighbor without HW address in vppagent-dataplane and return error

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#811]
## Expected Behavior

#810 fixes an issue where a [IPNeighbor](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/connectioncontext/connectioncontext.proto#L24) without a HW Address was being returned from an NSE.

The vppagent-dataplane needs to properly detect and return an error should this happen in the future.
I suggest writing an [IsValid](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/connectioncontext/helpers.go) for ConnectionContext, and ensuring that's being called in vppagent-dataplane.

A way to test this would be to imitate the issue that revealed #810, and feed it an IPNeighbor with an ip of ::1 and no HWAddress.

## Current Behavior

Currently if an IPNeighbor does not have a HW Address, dataplane provisioning silently fails.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by edwarnicke** [comment]
@stepan-anokhin Is this bug resolved?  If so, by which PR?

**Comment by stepan-anokhin** [comment]
@edwarnicke it's still pending. I hadn't had a chance to take a look yet.

**Comment by denis-tingajkin** [comment]
In progress

**Comment by denis-tingajkin** [comment]
Seems to me this can be closed
