### ISSUE TITLE
Add nsmd-monitoring helm chart

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#837]
## Overview

The new helm charts in NSM are awesome.  The decision to only include the core nsm components in the nsm chart was a good one.  It appears however that there is no helm chart that will bring the skydive and jaeger pieces of NSM.  It would be good to have a separate helm chart that does so, perhaps named something like monitoring.

## References

Original Helm PR: #825 
Original Helm Issue: #747

**Comment by lobkovilya** [comment]
@edwarnicke there are skydive and jaeger charts, they located inside helm/nsm/charts directory and are treated like dependent charts for nsm:
https://github.com/networkservicemesh/networkservicemesh/tree/master/helm/nsm/charts
Also they are being installed along with nsm.
Is it what you are talking about?

**Comment by edwarnicke** [comment]
Ah... good to know :)

Question... is it possible to deploy nsm without those monitoring components?  I find the monitoring useful, but  could imagine someone wanting just the bare NSM components (nsmd and vppagent-dataplane).

**Comment by lobkovilya** [comment]
Yes, you are right :) All monitoring staff should be moved to separate chart to allow bare NSM installation

**Comment by nickolaev** [comment]
Thinking of the small ARM64 boards, bare NSMgr + Dataplane would be more than useful.
+1 to have these separate.

**Comment by nickolaev** [comment]
One more thing. Today we have `imagePullPolicy: IfNotPresent` which might not be the case for every situation. Can we extract this as a parameter? I can do another issue if needed.
