### ISSUE TITLE
Harvesting cluster CIDRs for exclude prefixes

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#839]
## Overview

This is a sub-issue of #838 - see that issue for broader context.

Kubernetes has two kinds of CIDRs (prefixes) that should alway be added to the exclude_prefix list in connection context:

1.  PodCIDRs
2. ServiceCIDRs

Pod CIDRs can be gleaned from the [NodeSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#nodespec-v1-core).

Some investigation will need to be done to figure out how to extract the ServiceCIDRs

I would recommend the writing of a super small container similar to nsmd-k8s to monitor the PodCIDRs for each Node in the system and add them to the exclude_prefix list, and whatever mechanism is used for Service CIDRs.  This small container should also allow adding additional prefixes via an env variable at its startup time.

I'd recommend running this small container in the nsmd Pod, and having the nsmd container expose a super simple GRPC API to allow it to tell the nsmd about exclude_prefixes.

**Comment by lobkovilya** [comment]
@edwarnicke after some research figured out that cluster's podCIDR and serviceCIDR could be harvested from kubeadm-config:
```
$ kubectl describe configmap kubeadm-config --namespace=kube-system
``` 
I assume that we could do it using kubeadm api. 

As soon as podCIDR and serviceCIDR are set only during cluster initialization, there is no need to monitor them in separate container. But cluster's podCIDR could be much greater than union of node's podCIDR, so we will get some unnecessary exclusions.

What do you think about this approach?

**Comment by edwarnicke** [comment]
Oh... that is cool! :). Good find :)

**Comment by edwarnicke** [comment]
One question though... is it always present?  Is it possible a cluster might be installed and not have that config map?

**Comment by edwarnicke** [comment]
Overall... let’s start with that... as it simple, but keep an eye out to see if there are circumstances its not present... knowing we have ways we could fall back to if need be :)

**Comment by edwarnicke** [comment]
@lobkovilya Has this issue been resolved?

**Comment by lobkovilya** [comment]
No, need to add harvesting from nodes for non kubeadm-config clusters

**Comment by nickolaev** [comment]
#957 merged
