### ISSUE TITLE
Device Plugin leads to tests failure

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#860]
Following tests are not stable:
* `TestNSMDDP`
* `TestNSMDRecoverNSE` 
* `TestNSMHealRemoteDieNSMD_NSE` 

All they do something like:
```
k8s.DeletePods(nodes_setup[1].Nsmd)
k8s.DeletePods(icmpPod)

nodes[0].Nsmd = k8s.CreatePod(pods.NSMgrPodWithConfig(nsmdName, nodes[0].Node, &pods.NSMgrPodConfig{})) // Recovery NSEs
icmpPod = nsmd_test_utils.DeployICMP(k8s, nodes[0].Node, "icmp-responder-nse-2", defaultTimeout)
```

Fail happens during attempt to deploy `icmp-responder-nse-2`, because there is no resource for it.

But adding sleep solves the problem:
```
k8s.DeletePods(nodes_setup[1].Nsmd)
k8s.DeletePods(icmpPod)

time.Sleep(10 * time.Second)

nodes[0].Nsmd = k8s.CreatePod(pods.NSMgrPodWithConfig(nsmdName, nodes[0].Node, &pods.NSMgrPodConfig{})) // Recovery NSEs
icmpPod = nsmd_test_utils.DeployICMP(k8s, nodes[0].Node, "icmp-responder-nse-2", defaultTimeout)
```

**Comment by artem-belov** [comment]
Pod deleting with GracePeriod=0 does not guarantee of pod full termination.

> warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.

Removing that delete option resolve the problem

**Comment by nickolaev** [comment]
@lobkovilya @artem-belov is there a PR coming?
Also, is there a chance that the tests hang for stale pod not terminating?

**Comment by artem-belov** [comment]
@nickolaev Pull request is created #861 

> Also, is there a chance that the tests hang for stale pod not terminating?

Tests will continue working with warning after timeout. The most likely all required resources will be freed in timeout even if pod is not fully deleted.

**Comment by edwarnicke** [comment]
@artem-belov @lobkovilya Is this issue still occurring?

**Comment by lobkovilya** [comment]
I believe it is not occurring (at least at packet.net), fixed by @artem-belov in https://github.com/networkservicemesh/networkservicemesh/pull/861
