### ISSUE TITLE
vppagent-firewall-nse doesn't unregister after deletion

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#894]
## Expected Behavior

After deleting the deployment k8s/conf/vppagent-firewall-nse.yaml, it shouldn't be seen with 

```
kubectl describe networkserviceendpoints.networkservicemesh.io
```

## Current Behavior

The endpoint is still listed as a valid endpoint in the registry

## Steps to Reproduce

1. kubectl apply -f k8s/conf/secure-intranet-connectivity.yaml
2. kubectl apply -f k8s/conf/vppagent-firewall-nse.yaml
3. kubectl describe networkserviceendpoints.networkservicemesh.io
4. kubectl delete -f k8s/conf/vppagent-firewall-nse.yaml
5. kubectl describe networkserviceendpoints.networkservicemesh.io

## Context

I've used a vagrant deployment.

**Comment by matrohon** [comment]
it probably has to do with the way kubernetes/supervisord are terminated the firewall daemon, which doesn't receive the correct signal...

I can observe the same bug with the icmp-responder-nse endpoint from time to time.

To workaround the issue, I have to unregister endpoints manually with : 

```
kubectl delete networkserviceendpoints.networkservicemesh.io "endpointName"
```

if the nsmgr restarts while some endpoints are not correctly unregistered, it fails as shown in #892

**Comment by nickolaev** [comment]
That is a great finding @matrohon. Have to look closer at the signal handling and ensuring deregistration.

**Comment by matrohon** [comment]
@nickolaev I tested a vppagent-firewall-nse with two containers:

- one running vpp and the vppagent, managed by supervisord
- one running the firewall-nse binary as an entrypoint

When I delete the deployment, then the firewall-nse correctly catch the signal and unregister the endpoint. So I think the issue comes from supervisord that not correctly forward the signal to the process it manages.

**Comment by nickolaev** [comment]
@matrohon I have a theory. If you look closer at our `supervisord.conf` you will see this at the bottom:

```ini
; This event listener waits for event of vpp or agent  exitting.
; Once received, it kills supervisord process and this makes
; subsequently the exit of docker container.
; You should also set agent's autorestart=false.
[eventlistener:vpp_or_agent_not_running]
command=/usr/bin/supervisord_kill.py
events=PROCESS_STATE_EXITED
```

The check out the priority order of the processes:
```ini
[program:vpp]
...
priority=1

[program:agent]
...
priority=2

[program:vppagent-firewall-nse]
...
priority=3
```

My thewory is that since our processes are with he lowest priority, they are queued by supervisord to send the TERM signal to them last. Can you try increasing the priority of our processes to 1, to be on par with VPP?

**Comment by matrohon** [comment]
@nickolaev I gave it a try yesterday by giving priority 0 to vppagent-firewall-nse, but I'll try alternative configs and have a closer look at supervisord_kill.py

**Comment by matrohon** [comment]
@nickolaev I think I've found the issue: supervisord is not the process 0 in the [base image](https://github.com/ligato/vpp-agent/blob/master/docker/dev/Dockerfile#L126), so supervisord doesn't receive kill signals from kubelet and can't forward them to the processes it manages.
