### ISSUE TITLE
Proposal for little improving of SDK

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#908]
## Overview
We have very cool SDK that allows to configure any type of NSC or NSEs. But definition of Composite NSE is hard to read and overall confusing:
```go
composite := composite.NewMonitorCompositeEndpoint(nil).SetNext(
		newVppAgentAclComposite(configuration).SetNext(
			newVppAgentXConnComposite(configuration).SetNext(
				composite.NewClientCompositeEndpoint(configuration).SetNext(
					composite.NewConnectionCompositeEndpoint(configuration)))))
``` 
But if `SetNext(next CompositeEndpoint)` will return `next` instead of `self` then definition of Composite NSE could be rewritten like:
```go
composite := composite.NewMonitorCompositeEndpoint(nil).
		SetNext(newVppAgentAclComposite(configuration)).
		SetNext(newVppAgentXConnComposite(configuration)).
		SetNext(composite.NewClientCompositeEndpoint(configuration)).
		SetNext(composite.NewConnectionCompositeEndpoint(configuration))
```

**Comment by lobkovilya** [comment]
@nickolaev what do you think about it?

**Comment by edwarnicke** [comment]
@lobkovilya Ah... fluent style... :)

**Comment by nickolaev** [comment]
@lobkovilya looks good but am not sure it will work exactly as you describe it. In any case, please submit a PR and we can discuss it there.

**Comment by nickolaev** [comment]
Merged. Closing.
