### ISSUE TITLE
Testing NSM helm charts on all envs

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#922]
## Overview

NSM has helm charts for icmp and vpn in deployments/helm/

Let's make sure we test those helm charts in Packet, GKE, EKS, AKS to make sure they work and keep working out of the box.

**Comment by nickolaev** [comment]
@bartsmykla Can you please check this one.

**Comment by bartsmykla** [comment]
@nickolaev sure, I'm on it! :-)

**Comment by ivanayov** [comment]
@bartsmykla I have something done already, now testing

**Comment by ivanayov** [comment]
@bartsmykla this is the branch: [helm-test-coverage](https://github.com/ivanayov/networkservicemesh/tree/helm-test-coverage)

**Comment by ivanayov** [comment]
@bartsmykla you can make use of #964

**Comment by nickolaev** [comment]
Done in #1425
