### ISSUE TITLE
Memif file socket descriptor is using on memif proxy closing

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#926]
## Expected Behavior

Memif file socket exists and the file descriptor is closed after memif proxy closed.

## Current Behavior

Memif file socket exists and the file descriptor is opened after memif proxy closed.

## Failure Information (for bugs)
listen unixpacket /var/lib/networkservicemesh/nsm-2/if1/memif.sock: bind: address already in use
## Steps to Reproduce

Case 1:
1. go to test bench_memif_test.go
2. set breakpoint at last line 
3. debug the test
4. when breakpoint triggered use command in console: kubectl exec -it [nsc-pod-name] bash
5. cd /var/lib/networkservicemesh
5. cd to the workspace folder
6. try to read/write to memif socket file

Case 2:
1. Inject new listening logic in memif_proxy.go after proxy stopped
2. Log the error if listen has failed
3. run in console: make k8s-vppagent-dataplane-save && make k8s-vppagent-dataplane-load-images
4. do steps 1..3 from Case 1
5. kubectl logs [dataplane-pod-name] | pbcopy
6. Search your log message from step2

## Failure Logs
2019-04-09 12:57:00,286 DEBG 'vppagent-dataplane' stdout output:
time="2019-04-09T12:57:00Z" level=error msg="listen unixpacket /var/lib/networkservicemesh/nsm-2/if1/memif.sock: bind: address already in use"

**Comment by nickolaev** [comment]
Fix merged. Closing.
