### ISSUE TITLE
NSM entry not removed from registry after nsmgr deletion

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#927]
## Expected Behavior

after running 

```
kubectl delete -f k8s/conf/nsmgr.yaml
```

the network service manager should not be seen with: 

```
kubectl describe networkservicemanagers.networkservicemesh.io
```

## Current Behavior

currently, deleting the nsmgr pod doesn't remove the entry from the registry

**Comment by nickolaev** [comment]
That was discussed in #767. I think there are the ideas.

**Comment by edwarnicke** [comment]
@ivanayov Some nuance here.  If a NSMgr restarts, we don't want to remove it's record.  It's not clear how to detect the difference between  deletion vs a restart or upgrade.

Additionally, there may be NSE records associated with that NSMgr that need to be cleaned up correctly.

One way we considered was possibly using the lastseen field in the NetworkServiceManager CRD...  the original idea was to have some period (5 minutes) and have the NSMgr update that field every that many minutes.  If its lastseen is more than three periods old, consider it gone.

The problem with the lastseen is it has some scaling issues.  If I have 5k Nodes in a cluster, each updating every 5 minutes... that means on average 5k/300s ~=17 updates/s... which then also means 17 updates mirrored out to each *node* per second (as nsmd-k8s subscribes to notifications for each  node).

All of these things are solvable... just wanted to point out its a more interesting problem than it might originally seem :)

**Comment by ivanayov** [comment]
We can use K8s Garbage collection ([1], [2], [3]) , i.e. add `ownerReferences` 
There are 3 kinds of policies: `foreground` - owner cannot be deleted before any other object it owns, `background` - once owner is deleted, all owned objects are deleted, `orphan` - owned objects are left orphaned, removing the reference to the owner. 
I’m checking how it can be configured together with liveness and readiness probes.

[1] https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
[2] https://thenewstack.io/deletion-garbage-collection-kubernetes-objects/
[3] https://blog.openshift.com/garbage-collection-custom-resources-available-kubernetes-1-8/

**Comment by matrohon** [comment]
this issue is related to #928

**Comment by ivanayov** [comment]
I have paused work on this issue and will be able to continue at the end of June.

**Comment by artem-belov** [comment]
@haiodo @matrohon Issue can be closed
