### ISSUE TITLE
NSMgr: manage loop crashes and node decomissioning

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#928]
Currently in NSM, nothing is specified about how to manage a loop crash of nsmd : 
- do we unregister endpoints?
- do we recreate crossconnects of the client?
- do we attach datapath/endpoint containers to a alternative nsmgr?

The same kind of question may raise for a k8s node decommissioning, except clients located on that node will be restarted on a node with a nsmgr alive.

In case of a single crash of the nsmgr pod, the current implementation should handle the case gracefully, and k8s cache informer should report a UPDATE resource message with the new URL of the nsmgr pod.

**Comment by edwarnicke** [comment]
I would suggest the first question is: how do we detect a crash loop?

**Comment by edwarnicke** [comment]
@matrohon Is this still an ongoing concern?

**Comment by haiodo** [comment]
I've not see this since July. Let's close and re-open if needed.
