### ISSUE TITLE
Strange ping result on first pinging memif interface

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#933]
## Expected Behavior

The console hasn't strange output on basic_memif_test running

## Current Behavior

You could see 'Failed: no egress interface' on the first endpoint pinging.

## Failure Information (for bugs)

Failed: no egress interface

## Steps to Reproduce

1. Go to basic_memif_test
2. Add log for a ping response in the test(or you can run from the branch https://github.com/networkservicemesh/networkservicemesh/pull/925)
3. Run test

## Failure Logs
=== RUN   TestSimpleMemifConnection
time="2019-04-11T01:44:16+07:00" level=info msg="Checking node: kube-master"
time="2019-04-11T01:44:16+07:00" level=info msg="Checking node: kube-worker"
time="2019-04-11T01:44:22+07:00" level=info msg="Started NSMgr/Dataplane: 5.969185092s on node kube-master"
time="2019-04-11T01:44:28+07:00" level=info msg="Executing: [vppctl ping 10.20.1.2 repeat 2] in pod vppagent-nsc:vppagent-nsc"
time="2019-04-11T01:44:28+07:00" level=info msg="Ping result: , attempt: 1"
time="2019-04-11T01:44:29+07:00" level=info msg="Executing: [vppctl ping 10.20.1.2 repeat 2] in pod vppagent-nsc:vppagent-nsc"
time="2019-04-11T01:44:31+07:00" level=info msg="**Ping result: Failed: no egress interface\r\nFailed: no egress interface\r\n\r\nStatistics: 0 sent, 0 received, 0% packet loss\r\n, attempt: 2**"
time="2019-04-11T01:44:31+07:00" level=info msg="Executing: [vppctl ping 10.20.1.2 repeat 2] in pod vppagent-nsc:vppagent-nsc"
time="2019-04-11T01:44:33+07:00" level=info msg="Ping result: \r\nStatistics: 2 sent, 0 received, 100% packet loss\r\n, attempt: 3"
time="2019-04-11T01:44:34+07:00" level=info msg="Executing: [vppctl ping 10.20.1.2 repeat 2] in pod vppagent-nsc:vppagent-nsc"
time="2019-04-11T01:44:36+07:00" level=info msg="Ping result: 116 bytes from 10.20.1.2: icmp_seq=2 ttl=64 time=5.1751 ms\r\n\r\nStatistics: 2 sent, 1 received, 50% packet loss\r\n, attempt: 4"
time="2019-04-11T01:44:36+07:00" level=info msg="Ping successful"

**Comment by denis-tingajkin** [comment]
today I've investigated this issue. 
**Failed: no egress interface** returned each time if memif interface is not initialized.
And from logs seems that's OK behavior. Because we pinging the interface which is not initialized yet.
Looks like this defect can be closed

**Comment by nickolaev** [comment]
Do you think the test can be updated to make reflect better the situation. Like force interface initialisation?
