### ISSUE TITLE
Add FOSSA

### ISSUE THREAD

**Issue by caniszczyk** [networkservicemesh/networkservicemesh#937]
Add FOSSA https://fossa.io

CNCF has a deal so just set it up and we will be good to go.

**Comment by edwarnicke** [comment]
@caniszczyk Both @nickolaev and I have tried... but we both got gummed up in the works with 'organization' ... do you have a pointer to a simple way to get unstuck there?  I think fossa is enabled for NSM... but I don't see it in Github apps.

**Comment by edwarnicke** [comment]
@caniszczyk I tentatively think we figured it out :)

**Comment by nickolaev** [comment]
We have FOSSA fully integrated now. The badge in the main repo shows the active license status `passing`.
