### ISSUE TITLE
List CNCF sandbox status prominently on website and readme

### ISSUE THREAD

**Issue by lixuna** [networkservicemesh/networkservicemesh#968]
## Overview

Sandbox Entry Requirements include:

- [x] List CNCF sandbox status prominently on website 
- [ ] List CNCF sandbox status prominently on readme

## Link to the Google Docs document

- n/a

## References

- https://github.com/cncf/toc/blob/master/process/sandbox.md#sandbox-entry-requirements

**Comment by fkautz** [comment]
Bump

**Comment by lixuna** [comment]
Example text to add to README: 

- Network Service Mesh is hosted by the [Cloud Native Computing Foundation](https://cncf.io/) (CNCF) as a Sandbox Level Project. 

- Network Service Mesh is hosted by the [Cloud Native Computing Foundation](https://cncf.io/) (CNCF) as a sandbox level project. If you are an organization that wants to help shape the evolution of technologies that are container-packaged, dynamically-scheduled and microservices-oriented, consider joining the CNCF. For details read the [Network Service Mesh CNCF project proposal](https://github.com/cncf/toc/pull/212).
