### ISSUE TITLE
Support nsm namespace for Azure, GKE and packet deployments

### ISSUE THREAD

**Issue by ivanayov** [networkservicemesh/networkservicemesh#973]
This should be a follow up of #770 and required for closing #754

The CI for Azure, GKE and packet deployments was failing with 
```
Post <server-ip>:<port>api/v1/namespaces: stream error: stream ID 1; INTERNAL_ERROR
```

This might be an RBAC issue.

Fixing is important, as the infra deployment now operates in `nsm-system` namespace, which will fail to be created for those environments.

As a temporary solution `NSM_NAMESPACE` can be set empty of `"default"` for Azure and GKE.

**Comment by nickolaev** [comment]
I suggest we remove `v0.1.0` label here.

**Comment by haiodo** [comment]
@ivanayov we do not use default namespaces right now. I've not seed any issues like this in latest version.
