### ISSUE TITLE
A little Typo 

### ISSUE THREAD

**Issue by Napoleon0621** [networkservicemesh/networkservicemesh#990]
https://github.com/networkservicemesh/networkservicemesh/blob/3ece13683fd36f2db60c4671a62251e7a4b86486/examples/cmd/vppagent-nsc/nsc.go#L65

**Comment by nickolaev** [comment]
:) can you propose a PR, it's worth it although small.

**Comment by Harshini-M** [comment]
I made a patch set for it, and raised a PR.

**Comment by nickolaev** [comment]
FIxed in #1052
